Thchang/beam elements update
CARTAvis/carta-frontend pull request #1085
Opened 2020-08-05 10:14 UTC by TienHao

closes #804 
Image viewer now shows beams of contour layers which are referencing active image. The center points of referencing beam are align with the center point of referenced beam(raster image).

![Screenshot 2020-08-05 18:11:53](https://user-images.githubusercontent.com/20379662/89401124-6aa3f000-d747-11ea-8702-85604f5757c0.png)

2020-08-05 10:23 UTC, veggiesaurus requested changes
- Crashes when loading a file without beam info
- Warnings displayed in dev console, because each node returned from `plotBeam` needs to have a unique key. I suggest you use the frame ID

2020-08-07 06:43 UTC, kswang1029 commented
this is what the console says when crashing

![Screen Shot 2020-08-07 at 2 42 32 PM](https://user-images.githubusercontent.com/20819712/89617181-4fa6bc80-d8bc-11ea-89c6-1c5c12f08eb1.png)

2020-08-07 10:42 UTC, veggiesaurus requested changes
beams for the active image are no longer shown. It's now only showing the beams of the contoured spatial siblings

2020-08-10 12:59 UTC, veggiesaurus approved these changes

2020-08-10 13:00 UTC, merged