Qi/issue 1098
CARTAvis/carta-frontend pull request #1104
Opened 2020-08-12 06:13 UTC by panchyo0

1. fixed #1098, replace `Tooltip` with `Popover` with minimal style (with `pointer-events: none` not solving the problem)
2. fixed #1099, since we have current file name displayed as title, only show file name in dropdown menu. This also save some  space.

2020-08-12 06:40 UTC, kswang1029 requested changes
when a catalog is just loaded, the catalog widget is a floating window with the catalog file name in the title. However, once we dock it, the file name disappears (only showing "Catalog"). 
<img width="965" alt="Screen Shot 2020-08-12 at 2 39 27 PM" src="https://user-images.githubusercontent.com/20819712/89983255-cae7e400-dca9-11ea-8d73-255bb9027558.png">

2020-08-12 06:42 UTC, kswang1029 commented
about the "tooltip" styling, this new approach works but it is not consistent with the tooltip in other places. Not sure which style we should adopt. @veggiesaurus ?

2020-08-12 06:43 UTC, veggiesaurus commented
> about the "tooltip" styling, this new approach works but it is not consistent with the tooltip in other places. Not sure which style we should adopt. @veggiesaurus ?

We should be consistent with the tooltip used elsewhere

2020-08-12 15:32 UTC, veggiesaurus commented on src/components/CatalogOverlay/CatalogOverlayComponent.tsx
> +        this.catalogFiles = new Map<number, string>();
This should be renamed to `catalogFileNames`

2020-08-13 11:29 UTC, veggiesaurus approved these changes

2020-08-13 11:29 UTC, merged