Angus/build updates
CARTAvis/carta-frontend pull request #1222
Opened 2020-10-07 11:43 UTC by veggiesaurus

Closes #321 and #706 

This is a rather large change to the build, because it now uses `create-react-app@3.4.3`, which comes with new build scripts. Some other changes:

- allows us to import SCSS files directly, no need to run all the CSS-watching stuff
- uses eslint (with typescript plugins) instead of tslint
- uses browserlist to ensure that we compile to a sensible target, rather than supporting ancient browsers

There are a few stricter eslint rules by default, and this has required a number of minor changes to the code. Hopefully this doesn't break anything. 

@kswang1029 can you do some testing of the frontend in general?
@ajm-asiaa can you try build electron apps using this branch?
@duidae @panchyo0 @TienHao can you check through the changes to the code itself? Most were suggested directly by eslint.

note: this seems to break the breadcrumbs fix by @ajm-asiaa, I'll look into solving this during the review process

2020-10-07 12:31 UTC, ajm-asiaa commented
@veggiesaurus Does the result of `npm run build` work for you? I only seem to get a blank screen. The debug console shows the following:
<img width="572" alt="Screenshot 2020-10-07 at 20 29 43" src="https://user-images.githubusercontent.com/20802551/95331059-04b91d80-08dc-11eb-9651-9c9c3ab113de.png">

2020-10-07 12:33 UTC, veggiesaurus commented
> @veggiesaurus Does the result of `npm run build` work for you? I only seem to get a blank screen. The debug console shows the following:
> <img width="572" alt="Screenshot 2020-10-07 at 20 29 43" src="https://user-images.githubusercontent.com/20802551/95331059-04b91d80-08dc-11eb-9651-9c9c3ab113de.png">
> 

Perhaps you need to force a hard reload?

2020-10-07 12:37 UTC, ajm-asiaa commented
> > @veggiesaurus Does the result of `npm run build` work for you? I only seem to get a blank screen. The debug console shows the following:
> > <img alt="Screenshot 2020-10-07 at 20 29 43" width="572" src="https://user-images.githubusercontent.com/20802551/95331059-04b91d80-08dc-11eb-9651-9c9c3ab113de.png">
> 
> Perhaps you need to force a hard reload?

That doesn't seem to work (holding shift and hitting reload). 
I see the automatic builds on the [Mix 'N Match](http://carta.asiaa.sinica.edu.tw/builds/) page have the same issue.

2020-10-07 12:48 UTC, veggiesaurus commented
> > > @veggiesaurus Does the result of `npm run build` work for you? I only seem to get a blank screen. The debug console shows the following:
> > > <img alt="Screenshot 2020-10-07 at 20 29 43" width="572" src="https://user-images.githubusercontent.com/20802551/95331059-04b91d80-08dc-11eb-9651-9c9c3ab113de.png">
> > 
> > 
> > Perhaps you need to force a hard reload?
> 
> That doesn't seem to work (holding shift and hitting reload).
> I see the automatic builds on the [Mix 'N Match](http://carta.asiaa.sinica.edu.tw/builds/) page have the same issue.

It might be because I removed the `homepage` setting in `package.json`. I've added it back, can you see if that solves it?

2020-10-07 13:19 UTC, ajm-asiaa commented
> > > > @veggiesaurus Does the result of `npm run build` work for you? I only seem to get a blank screen. The debug console shows the following:
> > > > <img alt="Screenshot 2020-10-07 at 20 29 43" width="572" src="https://user-images.githubusercontent.com/20802551/95331059-04b91d80-08dc-11eb-9651-9c9c3ab113de.png">
> > > 
> > > 
> > > Perhaps you need to force a hard reload?
> > 
> > 
> > That doesn't seem to work (holding shift and hitting reload).
> > I see the automatic builds on the [Mix 'N Match](http://carta.asiaa.sinica.edu.tw/builds/) page have the same issue.
> 
> It might be because I removed the `homepage` setting in `package.json`. I've added it back, can you see if that solves it?

Yes. That fixed the problem! It works now. It appears to work when put into Electron too.

2020-10-08 01:10 UTC, ajm-asiaa approved these changes
The building aspects seem to be fine. The production build works now and the Electron app version can still be produced. Using the Docker build process seems to work fine too.

2020-10-08 01:11 UTC, kswang1029 commented
I am trying to explore the GUI from time to time to see if there are odd things and report here.
PART1
1. the checkbox of the molecular line transition table in the spectral line query widget is broken.
![Screen Shot 2020-10-08 at 8 48 49 AM](https://user-images.githubusercontent.com/20819712/95403008-9f007c00-0943-11eb-9fc4-b3fa7903764f.png)
2. breadcrumbs in the file browser is broken
![Screen Shot 2020-10-08 at 9 03 40 AM](https://user-images.githubusercontent.com/20819712/95403584-36b29a00-0945-11eb-8373-0738d9959ad7.png)

2020-10-08 02:04 UTC, duidae commented on src/components/Shared/ProfilerInfo/ProfilerInfoComponent.tsx
> +    let infoTags = null;
seems previous PR #1216  is not merged

2020-10-08 02:07 UTC, duidae commented on src/stores/FrameStore.ts
> -        const imageX = Math.round(cursorPosImageSpace.x);
PR #1221 is also missed

2020-10-08 02:08 UTC, duidae requested changes
PR #1216 & #1221 are missing

2020-10-08 22:21 UTC, panchyo0 approved these changes

2020-10-08 22:21 UTC, panchyo0 commented on package.json
>          "react-scripts-ts": "^2.17.0",
should we remove "react-scripts-ts" from package.json?

2020-10-09 08:32 UTC, veggiesaurus commented
The breadcrumbs and checkbox issues have been fixed now. And we no longer need the `crumbs_fix` workaround :+1: 

@kswang1029 can you give it another try when you get the chance?

2020-10-09 15:00 UTC, kswang1029 commented
@veggiesaurus confirmed with mix n match: both breadcrumbs and checkbox work properly.

2020-10-13 02:49 UTC, duidae approved these changes

2020-10-13 09:52 UTC, TienHao approved these changes

2020-10-14 08:35 UTC, merged