showing selected statistic string in y-axis label of spectral profiler
CARTAvis/carta-frontend pull request #1227
Opened 2020-10-14 12:29 UTC by TienHao

closes #256

2020-10-19 02:11 UTC, kswang1029 approved these changes
Tested and it looks good. 

UPDATE: found a bug please refer to the following comment.

2020-10-19 02:15 UTC, kswang1029 requested changes
When we have a point region and a rectangle region with FluxDensity as statistic, switching between these two region results in the wrong unit in the point region profile (should be Jy/beam but it is Jy).

2020-10-22 09:28 UTC, veggiesaurus commented on src/components/SpectralProfiler/SpectralProfilerComponent.tsx
> +                if (region && region.regionType === CARTA.RegionType.POINT) {
couldn't this be more elegantly combined with the `if` statement above?

2020-10-28 07:54 UTC, veggiesaurus commented
@kswang1029 are you happy with these changes?

2020-10-28 09:22 UTC, kswang1029 commented
@veggiesaurus @TienHao tested 6bb934b and it works well. 👍

2020-10-28 09:40 UTC, merged