Thchang/unifying color selectors
CARTAvis/carta-frontend pull request #1249
Opened 2020-11-05 08:58 UTC by TienHao

closed #341.
Replacing AST color selectors with new color picker components, by turning AST palette(`Module.colors`) into a color set of AST plotting elements(`OverlayXXXSetting`: global, title, grid, border, ticks, axis, number, label).

2020-11-06 02:28 UTC, kswang1029 reviewed
this looks mostly good. Two minor issues:
1) could you add the default "blue" as the preset colors at the bottom of the color selector?
2) I see a slightly different color selector for NaN color which has an additional transparency control. Shell we make it more consistent elsewhere?
![Screen Shot 2020-11-06 at 10 24 27 AM](https://user-images.githubusercontent.com/20819712/98319024-ccac1400-201a-11eb-996c-2253accee796.png)
![Screen Shot 2020-11-06 at 10 24 45 AM](https://user-images.githubusercontent.com/20819712/98319028-cf0e6e00-201a-11eb-9d43-aadd53976c19.png)

2020-11-09 10:25 UTC, veggiesaurus commented
> 2. I see a slightly different color selector for NaN color which has an additional transparency control. Shell we make it more consistent elsewhere?

Do any other colours actually _need_ a transparent selector in the swatch?

2020-11-09 10:44 UTC, kswang1029 commented
> > 1. I see a slightly different color selector for NaN color which has an additional transparency control. Shell we make it more consistent elsewhere?
> 
> Do any other colours actually _need_ a transparent selector in the swatch?

I cannot think of any, even for NaN. Maybe we can remove it to keep it simple?

2020-11-09 10:54 UTC, kswang1029 commented
Oh wait, transparency is needed if we want to support transparent NaN rendering. It might be still useful to have it in some cases. So I suggest we just accept the current implementation with NaN with an additional control for transparency.

2020-11-11 07:37 UTC, veggiesaurus commented on src/stores/AppStore.ts
> +            const colors = [
this is a nice way of solving this issue!

2021-01-06 09:09 UTC, veggiesaurus commented
@kswang1029 please re-test

2021-01-07 02:11 UTC, kswang1029 commented
The default color in "image view settings" -> "Global" -> "Color" should be (R, G, B) = (18, 86, 146) instead of (20, 104, 175) which is lighter and not consistent with the entire UI. Other than this, we are ready to go. @TienHao Could you help to check the default color and make the change, please?

2021-02-17 05:50 UTC, kswang1029 commented
@TienHao could you check the default color then we can merge the PR and close this issue?

2021-02-17 10:04 UTC, TienHao commented
@kswang1029  I have changed the default color in "image view settings" -> "Global" -> "Color". Please take a look.

2021-02-17 10:32 UTC, kswang1029 commented
@TienHao Please set the default color to the following based on the color themes.

> Light theme
> R, G, B = 16, 107, 163
> 
> Dark theme
> R, G, B = 43, 149, 214

The main issue here is we need the same color in the following boxed color panel so that users can have a way to restore the default color.
![Screen Shot 2021-02-17 at 6 30 11 PM](https://user-images.githubusercontent.com/20819712/108191678-615ffb00-714e-11eb-8d55-4d5703b02d60.png)

2021-03-03 08:37 UTC, TienHao commented
the auto color picker component has been added, which uses color string: `<auto-XXX>` to display color depending on current theme. Colors set [here](https://blueprintjs.com/docs/#core/colors) (eg. `auto-blue` is `blue2` when using light theme, and `blue4` when using dark theme) 

https://user-images.githubusercontent.com/20379662/109773061-bbc28680-7c39-11eb-81f6-66ab7849589b.mov


auto color pickers are applied in 
- Image Settings(AST, Beam)
- Histogram
- Catalog
- Spectral Profiler
- Spectral Profiler
- Stokes Analysis
- Profile Smoothing

original color pickers are remained in
- Region color
- NaN color
- Contour

2021-03-03 11:49 UTC, veggiesaurus requested changes

2021-03-03 11:49 UTC, veggiesaurus commented on src/stores/PreferenceStore.ts
> +        astColor: "auto-blue",
I think we'll need to create a new preference schema (version 2) and will need to also add an upgrade path for going from v1 (astColor: number) -> v2 (astColor: string)

2021-03-03 11:49 UTC, veggiesaurus commented on src/stores/PreferenceStore.ts
> +        astColor: "auto-blue",
It _might_ be easier to rename this setting to overlayColor in the new schema, as this would prevent conflicts

2021-03-05 06:16 UTC, kswang1029 commented
![Screen Shot 2021-03-05 at 2 15 27 PM](https://user-images.githubusercontent.com/20819712/110075105-41227400-7dbd-11eb-9e9a-c0de8489b484.png)
can the dropdown element be narrower to be consistent with others? Otherwise in the above case we need a wider default window size.

2021-03-05 06:19 UTC, kswang1029 commented
minor CSS adjustment: apply padding just below "Other:" Suggest the size to be the same as the horizontal one. 
![Screen Shot 2021-03-05 at 2 17 39 PM](https://user-images.githubusercontent.com/20819712/110075302-8f377780-7dbd-11eb-8881-e9c0c269e9b1.png)

2021-03-05 06:23 UTC, kswang1029 commented
> original color pickers are remained in
> 
> * Region color
> * NaN color
> * Contour

@TienHao Just curious, any reason why these three keep the same as before?

2021-03-05 06:28 UTC, veggiesaurus commented
> ![Screen Shot 2021-03-05 at 2 15 27 PM](https://user-images.githubusercontent.com/20819712/110075105-41227400-7dbd-11eb-9e9a-c0de8489b484.png)
> can the dropdown element be narrower to be consistent with others? Otherwise in the above case we need a wider default window size. 

Why do we need a dropdown here instead of just using a colour picker?

2021-03-05 10:38 UTC, veggiesaurus commented
> > original color pickers are remained in
> > 
> > * Region color
> > * NaN color
> > * Contour
> 
> @TienHao Just curious, any reason why these three keep the same as before?

surely the region and contour colours are independent of the theme, since they're on a colourmapped backdrop?

2021-03-05 10:40 UTC, kswang1029 commented
> surely the region and contour colours are independent of the theme, since they're on a colourmapped backdrop?

Right. Then it is fine to have those three as before. 👍

2021-03-08 07:54 UTC, veggiesaurus commented
> > surely the region and contour colours are independent of the theme, since they're on a colourmapped backdrop?
> 
> Right. Then it is fine to have those three as before.

@TienHao can you revert the change you made to those three?

2021-03-10 09:48 UTC, TienHao commented
> ![Screen Shot 2021-03-05 at 2 15 27 PM](https://user-images.githubusercontent.com/20819712/110075105-41227400-7dbd-11eb-9e9a-c0de8489b484.png)

> 
> Why do we need a dropdown here instead of just using a colour picker? Isn't that what #341 is describing?

@veggiesaurus 
The dropdown is for setting auto color string `auto-<xxx>`, because the color picker components of react-color can only accept hex, rgb, hsl, and "transparent".
Therefore, I combined the original two color pickers into a new one to meet the need of theme-aware colors.

2021-03-10 10:17 UTC, veggiesaurus commented
> @veggiesaurus
> The dropdown is for setting auto color string `auto-<xxx>`, because the color picker components of react-color can only accept hex, rgb, hsl, and "transparent".
> Therefore, I combined the original two color pickers into a new one to meet the need of theme-aware colors.

I see the complication. Hmm. Well, for the auto-picker, surely we con't need the swatch as well?
Also, could we not just have the text "Other", rather than an additional button? Having a button inside of a select seems a little clunky, and not needed, since changing the value in the colour picker updates the value displayed in the select anyway. Alternatively, the picker popup should pop up from the location you click, not the top of the select

https://user-images.githubusercontent.com/592504/110614042-9b934a00-819a-11eb-8e0d-3741c9fff178.mp4

2021-03-10 13:23 UTC, TienHao commented
> I see the complication. Hmm. Well, for the auto-picker, surely we con't need the swatch as well?

The color pickers in the _CatalogOverlaySettingPanel_ and _LinePlotSettingsPanel_ have "transparent" in the presetColors. Should we keep the swatch in the auto-color picker?

2021-03-15 08:04 UTC, kswang1029 commented
> > I see the complication. Hmm. Well, for the auto-picker, surely we con't need the swatch as well?
> 
> The color pickers in the _CatalogOverlaySettingPanel_ and _LinePlotSettingsPanel_ have "transparent" in the presetColors. Should we keep the swatch in the auto-color picker?

With those if we select transparent "color" what we actually see is black. This is same in v1.4. Wonder if this is due to Plotly scattergl? In any case, I think this PR is ready to go.

2021-03-15 08:04 UTC, kswang1029 approved these changes

2021-03-22 13:09 UTC, veggiesaurus approved these changes

2021-03-22 13:09 UTC, merged