fixed issue 453 578
CARTAvis/carta-frontend pull request #1317
Opened 2021-02-11 23:22 UTC by panchyo0

1. fixed issue #453 
2. fixed issue #578

2021-02-16 09:47 UTC, veggiesaurus requested changes
changes look good. Please just remove the `.eslintcache` file from the commit. In fact, we should add it to the `.gitignore`

2021-02-19 13:36 UTC, veggiesaurus approved these changes
looks good. @kswang1029 can you confirm this fixes both issues?

2021-02-20 03:30 UTC, kswang1029 commented
@panchyo0 @veggiesaurus good to merge 👍

2021-02-20 03:30 UTC, kswang1029 approved these changes

2021-02-20 04:07 UTC, merged