hide the whole toolbar when no image loaded
CARTAvis/carta-frontend pull request #1341
Opened 2021-03-05 03:12 UTC by YuHsuan-Hwang

This fixed issue https://github.com/CARTAvis/carta-frontend/issues/1330.
Hide the whole toolbar when no image loaded on x/y/z/ profile and stokes analysis dialogs.

2021-03-05 05:48 UTC, kswang1029 approved these changes
Tested 👍

2021-03-05 06:20 UTC, duidae commented on src/components/Shared/LinePlot/LinePlotComponent.tsx
> +                {(this.props.data !== undefined || (this.props.multiPlotPropsMap && this.props.multiPlotPropsMap.size > 0)) &&
can use optional chaining for simpler code 
`this.props.multiPlotPropsMap?.size > 0`

2021-03-05 06:21 UTC, duidae requested changes
can use optional chaining for simpler code
`this.props.multiPlotPropsMap?.size > 0`

2021-03-05 06:26 UTC, veggiesaurus requested changes

2021-03-05 06:26 UTC, veggiesaurus commented on src/components/Shared/ScatterPlot/ScatterPlotComponent.tsx
> +                {(this.props.data !== undefined || (this.props.multiPlotPropsMap && this.props.multiPlotPropsMap.size > 0)) &&
Optional chaining ( .? ) would simplify this

2021-03-08 02:17 UTC, YuHsuan-Hwang commented
@duidae @veggiesaurus Changed to optional chaining.

2021-03-08 05:41 UTC, duidae approved these changes

2021-03-08 07:53 UTC, merged