Yuhsuan/issue 48 header search
CARTAvis/carta-frontend pull request #1342
Opened 2021-03-05 10:15 UTC by YuHsuan-Hwang

This PR is for new feature requested in https://github.com/CARTAvis/carta/issues/48.
Some details:
- The button becomes visible when hovering on the information panel.
- The search panel can be easily closed by clicking anywhere outside.
- Pressing enter moves to the next matched string.
- The style of highlighting and scrolling is similar to the text search in Chrome browser, but other suggestions are welcome.

2021-03-05 11:27 UTC, kswang1029 approved these changes
This works nicely 👍  

this issue https://github.com/CARTAvis/carta-frontend/issues/1230 (cannot select by mouse) seems fixed too (tested with my local dev build 🤔)

2021-03-05 14:20 UTC, veggiesaurus requested changes
this is _really_ nice! I only have one minor request: The search icon looks a bit weird when you have a header that requires a scroll tab

Firefox: 
![image](https://user-images.githubusercontent.com/592504/110127478-5f44a000-7dce-11eb-9f1b-ea32bec74904.png)

Chrome:
![Screenshot from 2021-03-05 16-18-52](https://user-images.githubusercontent.com/592504/110127733-a6329580-7dce-11eb-8ed5-72def7d33e64.png)

Wonder if we should move it in a bit?

2021-03-05 14:29 UTC, veggiesaurus commented
It's pretty quick when handling large headers as well! :+1: 

https://user-images.githubusercontent.com/592504/110128593-a67f6080-7dcf-11eb-8955-4e8f707e1a8d.mp4

One thing that we might want to fix is the search bar disappearing when you scroll, because you can't actually see all the highlighted results.

2021-03-05 14:47 UTC, kswang1029 commented
The location of the search button is tricky as different browsers seem to have different scroll bar widths and may expand when hovering. If the button is too far away from the bottom right corner, it is weird too🙈

2021-03-05 14:54 UTC, YuHsuan-Hwang commented
Different Chrome version also seems to have different scroll bar width

2021-03-05 15:05 UTC, kswang1029 commented
@YuHsuan-Hwang could you also implement the same behavior as “enter” for the “previous” and “next” button? That will make the UX even better I guess.

2021-03-10 02:57 UTC, YuHsuan-Hwang commented
@veggiesaurus @kswang1029  Some changes:
1. Fixed #1230. Please help checking.
2. The search panel can be closed only by clicking the button. This avoids closing the panel when the users scroll.
3. Keep the buttons pressed will continuously scroll through the matched strings. Pressing enter after clicking the buttons will move forward/backward (the same as clicking the buttons). Pressing enter after clicking the text input will move forward.
4. The position of the button is not changed. It seems to be hard to fit all kinds of scroll bar.

2021-03-10 06:42 UTC, duidae approved these changes

2021-03-10 08:28 UTC, veggiesaurus commented
@YuHsuan-Hwang this is looking good. One issue: if you search for something, and then select another file, the search results persist and are buggy:

![image](https://user-images.githubusercontent.com/592504/110599309-63d0d600-818b-11eb-95a2-2b3804f3c910.png)

2021-03-10 08:29 UTC, veggiesaurus commented
I also encountered a hard-crash: 

```
Uncaught TypeError: Cannot read property 'forEach' of undefined
    at FileInfoComponent.highlightString
```

2021-03-10 08:32 UTC, veggiesaurus commented on src/components/FileInfo/FileInfoComponent.tsx
> +        function addHighlightedString(sliceStart: number, sliceEnd: number) {
please make this an arrow function instead,.

2021-03-10 08:32 UTC, veggiesaurus commented on src/components/FileInfo/FileInfoComponent.tsx
> +            highlighClassName = "";
typo

2021-03-11 03:07 UTC, YuHsuan-Hwang commented
@veggiesaurus Fixed the issues. Thanks for checking.

2021-03-17 09:38 UTC, veggiesaurus approved these changes

2021-03-17 09:38 UTC, merged