change log and power scaling
CARTAvis/carta-frontend pull request #1353
Opened 2021-03-16 09:24 UTC by YuHsuan-Hwang

This PR fixed issue https://github.com/CARTAvis/carta-frontend/issues/1351.
Adjusted the scaling formulas of Log and Power.

2021-03-16 09:31 UTC, veggiesaurus requested changes
We also need to change the scaling functions in `math.ts` (these are used in the contour generator) and update the log and power PNGs in `static/equations` to make these changes consistent.

2021-03-17 03:30 UTC, YuHsuan-Hwang commented
@veggiesaurus I changed the icons and the scaling functions for the contour generator. The impact to the contour generator is also negligible since alpha is always set to be 1000.

2021-03-17 08:57 UTC, veggiesaurus approved these changes

2021-03-17 09:02 UTC, kswang1029 approved these changes

2021-03-17 09:03 UTC, merged