Fix 1393
CARTAvis/carta-frontend pull request #1408
Opened 2021-04-19 03:11 UTC by duidae

closes #1393

2021-04-19 08:42 UTC, veggiesaurus requested changes

2021-04-19 08:42 UTC, veggiesaurus commented on wasm_src/ast_wrapper/ast_wrapper.cc
> +            return nullptr;
if we're returning `nullptr` here, we should call `astDelete` first, shouldn't we? otherwise we're leakingWebAssembly  memory

2021-04-19 08:42 UTC, veggiesaurus commented on wasm_src/ast_wrapper/post.ts
> +Module.getFrameFromFitsChan = Module.cwrap("getFrameFromFitsChan", "number", ["number", "boolean"]);
`cwrap` [only supports ](https://emscripten.org/docs/api_reference/preamble.js.html#cwrap)`number` and `string`. That's why we've used `number` elsewhere.

2021-04-19 08:49 UTC, veggiesaurus commented
@duidae also a couple of merge conflicts now that #1362 has been merged into `dev`.

2021-04-21 07:03 UTC, veggiesaurus approved these changes
looks ok to me

2021-04-26 13:40 UTC, veggiesaurus commented
@kswang1029 can we merge this in?

2021-04-26 14:06 UTC, veggiesaurus commented
@confluence can you test with this branch please?

2021-04-27 01:50 UTC, kswang1029 approved these changes

2021-04-28 05:33 UTC, duidae commented
@veggiesaurus can I merge this PR?

2021-04-28 05:34 UTC, veggiesaurus commented
Ok sure 👍🏼

2021-04-28 05:35 UTC, duidae commented
> Ok sure 👍🏼

thank u!

2021-04-28 05:35 UTC, merged