Angus/1214 manual reconnection
CARTAvis/carta-frontend pull request #1414
Opened 2021-04-21 12:27 UTC by veggiesaurus

Closes #1214 by implementing a manual reconnection strategy: 

- Initially, the frontend will attempt to connect to the backend up to 15 times (with a one second delay between connection attempts).
- If this fails, the user will be required to manually click the "Retry" button to reconnect
- If the connection drops later on, the frontend will not attempt to automatically reconnect. The user will have to manually click "Retry".

2021-04-21 13:05 UTC, kswang1029 commented
@veggiesaurus tested with a local build and it works properly. I don't have the environment to test the case with an auth system (eg controller).🤔

2021-04-22 09:18 UTC, veggiesaurus commented
I've tested it with the latest controller package, seems to work ok. Perhaps @ajm-asiaa could test it though?

2021-04-23 02:57 UTC, ajm-asiaa commented
I put this frontend on our "cartaviewer" server. I think it works. When I manually killed the backend process in a terminal I see the "Retry" notification window.
![Screenshot 2021-04-23 at 10 53 44](https://user-images.githubusercontent.com/20802551/115811567-86107180-a422-11eb-9f8d-c385fbc92f5b.png)

2021-04-23 02:59 UTC, kswang1029 commented
> I put this frontend on our "cartaviewer" server. I think it works. When I manually killed the backend process in a terminal I see the "Retry" notification window.
> ![Screenshot 2021-04-23 at 10 53 44](https://user-images.githubusercontent.com/20802551/115811567-86107180-a422-11eb-9f8d-c385fbc92f5b.png)

what's the behavior with auth? When trying to reconnect, no auth is required as long as it is not expired?

2021-04-23 03:06 UTC, ajm-asiaa commented
> > I put this frontend on our "cartaviewer" server. I think it works. When I manually killed the backend process in a terminal I see the "Retry" notification window.
> > ![Screenshot 2021-04-23 at 10 53 44](https://user-images.githubusercontent.com/20802551/115811567-86107180-a422-11eb-9f8d-c385fbc92f5b.png)
> 
> what's the behavior with auth? When trying to reconnect, no auth is required as long as it is not expired?

How do you test that? I didn't need to log in again if that is what you mean? But I just clicked Retry straight away. How long does it take for the auth to expire?

2021-04-23 03:12 UTC, kswang1029 commented
> > > I put this frontend on our "cartaviewer" server. I think it works. When I manually killed the backend process in a terminal I see the "Retry" notification window.
> > > ![Screenshot 2021-04-23 at 10 53 44](https://user-images.githubusercontent.com/20802551/115811567-86107180-a422-11eb-9f8d-c385fbc92f5b.png)
> > 
> > 
> > what's the behavior with auth? When trying to reconnect, no auth is required as long as it is not expired?
> 
> How do you test that? I didn't need to log in again if that is what you mean? But I just clicked Retry straight away. How long does it take for the auth to expire?

My question is, if the previous authentication expired (eg google or LDAP) and the user hits the retry button, what would happen? I am not sure how to test this... Maybe you need another CARTA tab and logout manually via the dashboard. Then go back to the original tab and hit retry.

2021-04-23 09:20 UTC, veggiesaurus commented
> > > > I put this frontend on our "cartaviewer" server. I think it works. When I manually killed the backend process in a terminal I see the "Retry" notification window.
> > > > ![Screenshot 2021-04-23 at 10 53 44](https://user-images.githubusercontent.com/20802551/115811567-86107180-a422-11eb-9f8d-c385fbc92f5b.png)
> > > 
> > > 
> > > what's the behavior with auth? When trying to reconnect, no auth is required as long as it is not expired?
> > 
> > 
> > How do you test that? I didn't need to log in again if that is what you mean? But I just clicked Retry straight away. How long does it take for the auth to expire?
> 
> My question is, if the previous authentication expired (eg google or LDAP) and the user hits the retry button, what would happen? I am not sure how to test this... Maybe you need another CARTA tab and logout manually via the dashboard. Then go back to the original tab and hit retry.

the reconnection will fail if they are no longer authenticated. If they re-authenticate, it will succeed.

2021-04-26 09:07 UTC, duidae commented on src/App.tsx
> +    renderAlertComponent = (alertStore: AlertStore, darkTheme: boolean) => {
private

2021-04-26 09:07 UTC, duidae commented on src/App.tsx
> +    }
semi-colon

2021-04-26 09:07 UTC, duidae commented on src/App.tsx
> +        let alertComponent = this.renderAlertComponent(appStore.alertStore, appStore.darkTheme);
const

2021-04-26 09:08 UTC, duidae requested changes

2021-04-26 09:08 UTC, duidae commented on src/stores/AppStore.ts
> +    }
semi-colon

2021-04-26 09:11 UTC, duidae requested changes

2021-04-26 09:11 UTC, duidae commented on src/stores/AlertStore.ts
> +    }
semi-colon

2021-04-26 10:39 UTC, veggiesaurus commented
thanks @duidae, have fixed the minor issues

2021-04-26 11:10 UTC, TienHao approved these changes

2021-04-26 12:20 UTC, YuHsuan-Hwang approved these changes

2021-04-26 12:41 UTC, merged