Thchang/file browser progress bar
CARTAvis/carta-frontend pull request #1422
Opened 2021-04-26 07:35 UTC by TienHao

closes #1303 to support backend issue(CARTAvis/carta-backend#431). 

Add progress bar with cancel button in the file browser. The file browser will show the progress bar after receiving a progress message from the backend. The cancel button will cancel the file list loading process and return to the previous directory.

companion backend branch: [mark/431_file_list_interruption](https://github.com/CARTAvis/carta-backend/tree/mark/431_file_list_interruption) (CARTAvis/carta-backend#777)
companion protobuf branch: [mark/stop_getting_file_list](https://github.com/CARTAvis/carta-protobuf/tree/mark/stop_getting_file_list)

2021-04-27 05:25 UTC, kswang1029 approved these changes
Feature-wise this looks good. 

One issue I spotted (not due to this PR) is that when we load _another_ image from a folder with lots of files, initially we will see the file list saying "Empty folder" before the long file list arrives. Will file this as a new issue. 


https://user-images.githubusercontent.com/20819712/116189706-ef162300-a75b-11eb-8e4c-77857c2c6c28.mp4

2021-04-30 09:54 UTC, veggiesaurus requested changes
I've requested changes on the protobuf repo itself, which will affect both frontend and backend PRs

2021-04-30 09:54 UTC, veggiesaurus commented on src/components/Dialogs/FileBrowser/FileBrowserDialogComponent.tsx
> +    private handleFileBrowserRequestingCancelled = () => {
rename to `handleFileBrowserRequestCancelled`

2021-04-30 09:54 UTC, veggiesaurus commented on src/components/Dialogs/FileBrowser/FileBrowserDialogComponent.tsx
> +                    contentText={`loading files ${fileBrowserStore.loadingCheckedCount} / ${fileBrowserStore.loadingTotalCount}`}
Should this be `Loading`?

2021-05-03 08:17 UTC, veggiesaurus commented
@TienHao will you update this branch to make use of the new protobuf approach @markccchiang has implemented?

2021-05-03 10:02 UTC, TienHao commented
merged with dev and updated with new protobuf

2021-05-03 10:30 UTC, veggiesaurus requested changes

2021-05-03 10:30 UTC, veggiesaurus commented on src/stores/FileBrowserStore.ts
> +    @action cancelRequestingFile = () => {
can't we just combine this into one function? `this.browserMode` can be used to determine the `FileListType`

2021-05-03 11:44 UTC, veggiesaurus approved these changes

2021-05-05 08:01 UTC, merged