Thchang/issue 961
CARTAvis/carta-frontend pull request #1441
Opened 2021-05-12 06:20 UTC by TienHao

closes #961. Fixed region create button, which was not activated immediately by click when catalog selection mode was enabled.

2021-05-19 06:39 UTC, kswang1029 approved these changes

2021-05-21 09:24 UTC, veggiesaurus requested changes

2021-05-21 09:24 UTC, veggiesaurus commented on src/components/ImageView/Toolbar/ToolbarComponent.tsx
>      private handelActiveLayerClicked = (layer: ImageViewLayer) => {
can you fix this typo at the same time? `handel` -> `handle`

2021-05-27 10:02 UTC, veggiesaurus approved these changes

2021-05-27 10:04 UTC, merged