Jason/performance improve region view pan zoom line region
CARTAvis/carta-frontend pull request #1664
Opened 2021-10-07 03:29 UTC by duidae

closes https://github.com/CARTAvis/carta/issues/90

2021-10-11 07:40 UTC, veggiesaurus commented on src/components/ImageView/ImagePanel/ImagePanelComponent.tsx
> +    private regionViewRef;
shouldn't this be typed?

2021-10-11 07:47 UTC, veggiesaurus commented on src/stores/FrameStore.ts
> +    public requiredFrameViewForRegionRender;
can you add type info here?

2021-10-11 07:48 UTC, veggiesaurus approved these changes
Code looks good to me. Two minor typing additions requested, but other than that looks fine. A lot of code changes though, so careful testing by @kswang1029 needed

2021-10-12 01:58 UTC, kswang1029 requested changes
I see an out-of-sync issue when we have matched images.


https://user-images.githubusercontent.com/20819712/136878103-0669f2ca-d9ad-4dec-ad85-b4e4e35dfadf.mov

2021-11-01 06:46 UTC, kswang1029 commented
found an out-of-sync issue when panning the image. Please focus on the center part of the movie and focus on the relative positions between the regions and image features. If we pan slightly, sometimes we see the image and regions are synchronized but sometimes they are not. 

https://user-images.githubusercontent.com/20819712/139632147-5d21b6a5-7902-4401-824f-d1a7e62c9ca1.mov

2021-11-02 01:51 UTC, duidae commented
> found an out-of-sync issue when panning the image. Please focus on the center part of the movie and focus on the relative positions between the regions and image features. If we pan slightly, sometimes we see the image and regions are synchronized but sometimes they are not. The example is with 2000 point regions.
> 
Fixed, please have a look.

2021-11-02 03:59 UTC, kswang1029 approved these changes
this looks good as far as I can tell. 👍

2021-11-05 08:21 UTC, merged