Qi/online catalog vizier
CARTAvis/carta-frontend pull request #1673
Opened 2021-10-15 19:20 UTC by panchyo0

This PR should go after PR #1651 
Catalog query feature for vizier

2021-10-29 02:42 UTC, kswang1029 commented
@panchyo0 could you update protobuf to 6571a44afc486902b322fbd68f81a12e96eb075e?

2021-11-01 07:20 UTC, kswang1029 commented
@panchyo0 a quick question: when we make a query to VizieR, does the frontend retrieve _all_ matched table to the frontend first? Then we use the multi-select menu to select which catalogs to be displayed?

2021-11-01 07:23 UTC, kswang1029 commented
Question: when the "Key words (Catalog title)" is filled, what are the query parameters here? Are the "Key words", plus the coordinate info and search radius all together as the query parameters?

![Screen Shot 2021-11-01 at 3 21 07 PM](https://user-images.githubusercontent.com/20819712/139635860-3591e009-43b8-4524-9693-cbea2b3daeb9.png)

2021-11-01 16:53 UTC, panchyo0 commented
> we make a query to VizieR, does the frontend retrieve _all_ matched table to the frontend first? Then we use the multi-select menu to select which catalogs to be displayed?

That's right

2021-11-01 17:03 UTC, kswang1029 commented
> > we make a query to VizieR, does the frontend retrieve _all_ matched table to the frontend first? Then we use the multi-select menu to select which catalogs to be displayed?
> 
> That's right

Ok. My real question is actually performance. It is quite slow to retrieve all catalogs before selecting which to display. Is it possible to just get the titles of catalogs first? Then based on user selection the frontend retrieves data afterwards. 🤔

2021-11-03 02:04 UTC, panchyo0 commented
> > > we make a query to VizieR, does the frontend retrieve _all_ matched table to the frontend first? Then we use the multi-select menu to select which catalogs to be displayed?
> > 
> > 
> > That's right
> 
> Ok. My real question is actually performance. It is quite slow to retrieve all catalogs before selecting which to display. Is it possible to just get the titles of catalogs first? Then based on user selection the frontend retrieves data afterwards. 🤔

Thanks for the suggestion, now we only load tables names at the first step. it's about 2 times faster than before. But sometime loading data for user selected tables is time consuming. That is out of our control 😞

2021-11-03 04:07 UTC, kswang1029 commented
> > > > we make a query to VizieR, does the frontend retrieve _all_ matched table to the frontend first? Then we use the multi-select menu to select which catalogs to be displayed?
> > > 
> > > 
> > > That's right
> > 
> > 
> > Ok. My real question is actually performance. It is quite slow to retrieve all catalogs before selecting which to display. Is it possible to just get the titles of catalogs first? Then based on user selection the frontend retrieves data afterwards. 🤔
> 
> Thanks for the suggestion, now we only load tables names at the first step. it's about 2 times faster than before. But sometime loading data for user selected tables is time consuming. That is out of our control 😞

Thanks @panchyo0. Yes now it performs better. 👍 

Overall this looks good and will be handy for users. Just one minor concern about "Max Number of Objects" field. It makes sense when making a query to SIMBAD but it is less sensible for VizieR. At the moment it still sets as the upper limit when loading a specific catalog from VizieR. However we cannot see from the catalog title how many sources there are per catalog. So it might be the case that I only partially load one catalog. I would suggest for VizieR catalog, we don't apply such "Max Number of Objects" limitation but instead we load the full catalog for completeness. This should be more realistic use case when a user would like to study the content for a given catalog. So my suggestion would be when VizieR is selected, we don't show that field and we don't apply any cutoff when loading a VizieR catalog.

2021-11-03 22:48 UTC, panchyo0 commented
>  So my suggestion would be when VizieR is selected, we don't show that field and we don't apply any cutoff when loading a VizieR catalog.

@kswang1029 There is a performance issue when we load large catalog form vizier via internet. I added a `Cutoff` switch button, so user can have option to choose use the cutoff or not. Please check. 

load 15 tables without limit, it takes about 9mins to download those catalogs
![Screen Shot 2021-11-03 at 4 38 44 PM](https://user-images.githubusercontent.com/22226157/140215924-80b33445-abac-4506-b6b1-93570bd8e463.png)

load same table with `Max number of Objects =10` only takes 153 ms for downloading part
![Screen Shot 2021-11-03 at 4 31 31 PM](https://user-images.githubusercontent.com/22226157/140216065-5c97ec18-196d-4ee1-9101-9e53d0b9104a.png)

2021-11-04 04:28 UTC, kswang1029 commented
@panchyo0 I see. Good point. Then I would suggest to remove the toggle but just change the title from "Max number of objects" to "Max number of objects per catalog" when VizieR is selected. When it is SIMBAD, we use "Max number of objects"

2021-11-04 22:00 UTC, panchyo0 commented
@kswang1029  please, check again

2021-11-05 11:21 UTC, veggiesaurus requested changes

2021-11-05 11:21 UTC, veggiesaurus commented on src/stores/CatalogOnlieQueryConfigStore.ts
> +    @action resetVizirR() {
typo?

2021-11-05 11:21 UTC, veggiesaurus commented on src/utilities/CatalogApiProcessed.ts
> +export type VizieResource = {
typo? `VizieRResource`?

I think perhaps we should be consistent and use a lowercase `r` in `vizier` everywhere except user-facing strings.

2021-11-08 08:02 UTC, kswang1029 approved these changes

2021-11-11 09:33 UTC, veggiesaurus approved these changes

2021-11-11 09:33 UTC, merged