Mylin/1667 fix pa change when set length
CARTAvis/carta-frontend pull request #1674
Opened 2021-10-18 08:10 UTC by acdo2002

fixed #1667 

I found when given a length, the sin and cos in x and y is different(i.e. opposite) to setRotation action in carta-frontend/src/stores/RegionStore.ts
I make them consistent to setRotation action then the issue fixed.

I also found the existingValue in handleLengthChange should be the length of 2D point rather than just region.size.x, otherwise the existingValue could be negative.

2021-10-18 08:49 UTC, veggiesaurus approved these changes

2021-10-18 09:09 UTC, kswang1029 reviewed
It would be good to add a comment why sin and cos need to be swapped. The usual rotation matrix requires an additional offset to meet the PA=0 definition in astronomy.

2021-10-18 09:46 UTC, acdo2002 commented
The setLength will calculate the length in x and y direction based on the current PA.
I add description: rotation is in degrees counter-clockwise of north(N).
PA = 0 in North direction and increased counter-clockwise.

Thus the length in x-direction should be sin(rotation) and length in y-direction should be cos(rotation).
The calculation in PA is correct, however I have no idea why in setLength, the calculation changes to cos(rotation) in x-direction and sin(rotation) in y-direction?
I just fixed it then the setLength works normal as we expect.

2021-10-19 02:43 UTC, YuHsuan-Hwang commented on src/components/Dialogs/RegionDialog/LineRegionForm/LineRegionForm.tsx
>          const existingValue = this.props.region.size.x;
also change this line to `length2D(this.props.region.size)`

2021-10-19 02:55 UTC, kswang1029 commented
> The setLength will calculate the length in x and y direction based on the current PA. I add description: rotation is in degrees counter-clockwise of north(N). PA = 0 in North direction and increased counter-clockwise.
> 
> Thus the length in x-direction should be sin(rotation) and length in y-direction should be cos(rotation). The calculation in PA is correct, however I have no idea why in setLength, the calculation changes to cos(rotation) in x-direction and sin(rotation) in y-direction? I just fixed it then the setLength works normal as we expect.

This is because the rotation matrix is different from the usual one we learned from math course. The usual rotation matrix is
cos -sin
sin cos
if 0 deg is aligned with +x axis and the angle increases counter-clockwise. In astronomy, however, the 0 deg is aligned with +y axis and the angle increases counter-clockwise. So the rotation matrix needs to be modified with the additional 90deg offset hence we see cos<->sin with a proper +/-1 applied.

2021-10-28 03:53 UTC, acdo2002 commented
@kswang1029 & @YuHsuan-Hwang 
I add the short comment to explain the PA and why cos<->sin with a proper +/-1 applied.
please check it.

2021-10-28 05:23 UTC, YuHsuan-Hwang approved these changes

2021-10-28 06:16 UTC, kswang1029 requested changes
// rotation is in degrees counter-clockwise of north(N)
// additional 90 deg offset hence we see cos<->sin with a proper +/-1 applied

the comments may be revised as the following:

the rotation angle is defined to be 0 at North (mostly in +y axis) and increases counter-clockwisely. This is different from the usual definition in math where 0 degree is in the +x axis. The extra 90-degree offset swaps cos and sin with a proper +/-1 constant applied.

2021-10-28 06:52 UTC, acdo2002 commented
@kswang1029 
Thanks for the suggestion, the comments have been revised now!

2021-10-28 07:10 UTC, kswang1029 commented
the pa and length part are fixed. Just noticed that if we change the center manually, PA will be changed too...

2021-10-28 07:38 UTC, acdo2002 commented
Same problem but in the src/stores/RegionStore.ts.
Now it should be fixed when changing length & centre position (both image and world coordinate), the PA will not be changed.

2021-10-28 09:36 UTC, kswang1029 approved these changes

2021-10-29 02:41 UTC, YuHsuan-Hwang reviewed
shall we also add the same comments for line 433 in `RegionStore.ts` `setRotation()`?

2021-10-29 02:53 UTC, acdo2002 commented
@YuHsuan-Hwang Yes, `setRotation()` in `RegionStore.ts` is the original function I followed.
I put the description in the line 433.

2021-10-29 02:56 UTC, YuHsuan-Hwang approved these changes

2021-11-08 13:06 UTC, veggiesaurus approved these changes

2021-11-08 13:07 UTC, merged