Jason/issue 648 unit conv
CARTAvis/carta-frontend pull request #1707
Opened 2021-11-22 02:58 UTC by duidae

closes #648

2021-11-22 05:14 UTC, kswang1029 requested changes
Did a quick check of converting Jy/beam to Kelvin. The result is not consistent with the casaviewer. In the example below, the peak should be ~10 K but the converted value in CARTA is ~2.2x10^-3 K. 


<img width="1689" alt="Screen Shot 2021-11-22 at 1 11 38 PM" src="https://user-images.githubusercontent.com/20819712/142804563-e81cb3ea-e4dc-482f-a6f1-8f9ab90e60c3.png">

2021-11-22 05:32 UTC, kswang1029 requested changes
cdelt1 from the header is usually a negative number so we need to apply abs() to it, otherwise the profile will get flipped up side down.

2021-11-22 05:37 UTC, kswang1029 requested changes
When the input image is in Jy/beam, the conversion to Jy/pixel should be forbidden because this conversion involves image deconvolution.

2021-11-22 07:05 UTC, duidae commented
> Did a quick check of converting Jy/beam to Kelvin. The result is not consistent with the casaviewer. In the example below, the peak should be ~10 K but the converted value in CARTA is ~2.2x10^-3 K.
> 
> <img alt="Screen Shot 2021-11-22 at 1 11 38 PM" width="1689" src="https://user-images.githubusercontent.com/20819712/142804563-e81cb3ea-e4dc-482f-a6f1-8f9ab90e60c3.png">

tried correcting the value of bmaj/bmin in this file,
bmaj = 1.884508960777E-04
bmin = 1.530597441726E-04
and applies the formula 
![image](https://user-images.githubusercontent.com/25971696/142817479-9ae37b59-546f-4acb-be34-0a2b9ff6090c.png)

but there is still a 1e-11 scale difference, and also see this formula in NRAO's site (https://science.nrao.edu/facilities/vla/proposing/TBconv)
![image](https://user-images.githubusercontent.com/25971696/142817726-385b6025-150a-4e07-907f-cd386e38a90b.png)

guessing the difference 1e-11 is from 1e3(typo of formula) * 1e4(scale of bmaj) * 1e4(scale bmin), @kswang1029 not sure the logic is correct or not.

2021-11-22 07:12 UTC, kswang1029 commented
> > Did a quick check of converting Jy/beam to Kelvin. The result is not consistent with the casaviewer. In the example below, the peak should be ~10 K but the converted value in CARTA is ~2.2x10^-3 K.
> > <img alt="Screen Shot 2021-11-22 at 1 11 38 PM" width="1689" src="https://user-images.githubusercontent.com/20819712/142804563-e81cb3ea-e4dc-482f-a6f1-8f9ab90e60c3.png">
> 
> tried correcting the value of bmaj/bmin in this file, bmaj = 1.884508960777E-04 bmin = 1.530597441726E-04 and applies the formula ![image](https://user-images.githubusercontent.com/25971696/142817479-9ae37b59-546f-4acb-be34-0a2b9ff6090c.png)
> 
> but there is still a 1e-11 scale difference, and also see this formula in NRAO's site (https://science.nrao.edu/facilities/vla/proposing/TBconv) ![image](https://user-images.githubusercontent.com/25971696/142817726-385b6025-150a-4e07-907f-cd386e38a90b.png)
> 
> guessing the difference 1e-11 is from 1e3(typo of formula) * 1e4(scale of bmaj) * 1e4(scale bmin), @kswang1029 not sure the logic is correct or not.

the formula with 10^3 instead of 10^6 from NRAO is because the input I is mJy instead of Jy. So we see a factor 1000 difference. Could you check if theta_a and theta_b are in "arcsec" unit? BMAJ and BMIN from header is in degree mostly. We will need to convert from degree to arcsec (1 deg = 60 arcmin, 1 arcmin = 60 arcsrc, so 1 deg = 3600 arcsec). Also the  "nu" should be in GHz.

2021-11-22 07:17 UTC, duidae commented
> the formula with 10^3 instead of 10^6 from NRAO is because the input I is mJy instead of Jy. So we see a factor 1000 difference. Could you check if theta_a and theta_b are in "arcsec" unit? BMAJ and BMIN from header is in degree mostly. We will need to convert from degree to arcsec (1 deg = 60 arcmin, 1 arcmin = 60 arcsrc, so 1 deg = 3600 arcsec). Also the "nu" should be in GHz.

how can we know the unit of bmaj/bmin? through which header?

2021-11-22 07:19 UTC, kswang1029 commented
> > the formula with 10^3 instead of 10^6 from NRAO is because the input I is mJy instead of Jy. So we see a factor 1000 difference. Could you check if theta_a and theta_b are in "arcsec" unit? BMAJ and BMIN from header is in degree mostly. We will need to convert from degree to arcsec (1 deg = 60 arcmin, 1 arcmin = 60 arcsrc, so 1 deg = 3600 arcsec). Also the "nu" should be in GHz.
> 
> how can we know the unit of bmaj/bmin? through which header?

BMAJ and BMIN (and BPA) are not included in the FITS standard. Mostly people use degree as the implicit unit when creating the FITS file. We will have to assume it is in degree.

2021-11-22 07:20 UTC, duidae commented
> BMAJ and BMIN (and BPA) are not included in the FITS standard. Mostly people use degree as the implicit unit when creating the FITS file. We will have to assume it is in degree.

ok thanks.

2021-11-25 05:40 UTC, kswang1029 commented
@duidae if we load a cube with the unit as Jy/beam, when we launch the spectral profiler, the ylabel is displayed as "Value" without the unit in the (). Could you fix this regression please?

2021-11-25 05:51 UTC, kswang1029 commented
@duidae the conversion from Jy/beam (the input cube) to Jy/arcsec^2 seems not correct. 
![Screen Shot 2021-11-25 at 1 46 49 PM](https://user-images.githubusercontent.com/20819712/143386683-fb133859-59ba-402b-929d-dc591b7d023c.png)

Could you double check if the unit is correct? The calculation of Omega (beam solid angle) requires the theta_a and theta_b in "rad".

2021-11-28 02:56 UTC, kswang1029 commented
@duidae do you think with the same PR we can support unit conversion when the multiple profile plot mode is enabled? For example, there are two images loaded, one is in Jy/beam and the other is in K. Then when the two images are matched and show region spectral profiles in the multiple profile plot mode, if the user selects K, then the profile with Jy/beam needs to be converted to K before plotting, and vice versa. This feature is a common use case in radio astronomy.

2021-11-29 07:58 UTC, duidae commented
Jy/beam <=> Jy/arcsec^2, ylabel fixed, please test. @kswang1029 can you remember to use "request Change" for notification?

2021-11-29 10:55 UTC, kswang1029 commented on src/models/SpectralDefinition.ts
> +    const coefficient = (cdelta1 * cdelta2) / (2.350443 * 1e-11);
please check the units of cdelta1 and cdelta2. They should be in rad, not degree.

2021-11-29 11:33 UTC, kswang1029 commented on src/stores/widgets/SpectralProfileWidget/SpectralProfileWidgetStore.ts
> +                const beam = frame.frameInfo.beamTable[0];
If the input image has per-plane-beam table (ie there are bmaj, bmin, and bpa _per_ channel), do you consider the beam size _as a function of channel_ in the Jy/beam <-> K conversion? For line 344, do you quote the 0th elements in the beamTable as a representative bmaj and bmin for the conversion?

2021-11-30 04:53 UTC, kswang1029 approved these changes
checked all the conversion pairs (with and without required headers) and the per-plane-beam case. All now work fine.

2021-12-01 11:59 UTC, veggiesaurus commented
code looks fine to me. Just one question: I see it's relying on `CDELT` header entries. What about situations where the WCS is specified using `PC` or `CD` matrices?

2021-12-01 12:01 UTC, kswang1029 commented
> code looks fine to me. Just one question: I see it's relying on `CDELT` header entries. What about situations where the WCS is specified using `PC` or `CD` matrices?

we might use the same approach as https://github.com/CARTAvis/carta-frontend/pull/1719 ? 🤔

2021-12-02 02:45 UTC, YuHsuan-Hwang commented
> we might use the same approach as #1719 ? 🤔
> 
> @YuHsuan-Hwang do we have pixel size info stored elsewhere already?

stored in private `regionUnitSize` under `frameStore`. Can be used by public functions `getWcsSizeInArcsec`, `getImageXValueFromArcsec`, and `getImageYValueFromArcsec`. We may change `regionUnitSize` to a more general name if we are using it for other purposes.

2021-12-02 06:46 UTC, duidae commented
> > we might use the same approach as #1719 ? thinking
> > @YuHsuan-Hwang do we have pixel size info stored elsewhere already?
> 
> Yes, stored in private `regionUnitSize` under `frameStore`. Can be used by public functions `getWcsSizeInArcsec`, `getImageXValueFromArcsec`, and `getImageYValueFromArcsec`. We may change `regionUnitSize` to a more general name if we are using it for other purposes.

change the source of cdelta1 cdelta2 to regionUnitSize, please check.

2021-12-02 06:54 UTC, veggiesaurus approved these changes

2021-12-02 06:54 UTC, veggiesaurus commented
looks good to me. @kswang1029 can you just check that it still behaves correctly with this change?

2021-12-02 09:01 UTC, kswang1029 approved these changes

2021-12-02 09:02 UTC, kswang1029 commented
> looks good to me. @kswang1029 can you just check that it still behaves correctly with this change?

@veggiesaurus yes, conversions involving pixel size are still correct.

2021-12-02 09:22 UTC, merged