Jason/issue 1697
CARTAvis/carta-frontend pull request #1711
Opened 2021-11-23 06:05 UTC by duidae

closes #1697

2021-11-23 06:18 UTC, veggiesaurus approved these changes

2021-11-24 02:46 UTC, YuHsuan-Hwang approved these changes

2021-11-24 08:04 UTC, kswang1029 requested changes
could you check the case when holding "shift" key and drag the corner control point? On a Retina display, we can see resizing that way has the same issue. 

https://user-images.githubusercontent.com/20819712/143198425-04ba062d-a6f6-415c-ab19-a6959fe0e56f.mov

2021-11-24 08:52 UTC, kswang1029 approved these changes

2021-11-24 14:00 UTC, merged