Yuhsuan/1717 1718 colorbar gradient fix
CARTAvis/carta-frontend pull request #1720
Opened 2021-11-26 08:19 UTC by YuHsuan-Hwang

Closes #1717 and #1718: fixed the positions of the colorbar gradient

2021-11-26 09:53 UTC, veggiesaurus approved these changes

2021-11-26 11:34 UTC, kswang1029 requested changes
Thanks for the quick fix. Now the color blocks and tick marks are consistent. Additional issue I spotted (not sure if they are related):
- 1px mis-alignment between coordinate box and colorbar box (this might be the same root cause as the next one). This is also observed when the colorbar is vertical.
- the boundary between adjacent color blocks is not sharp (cf the pixel rendering which is sharp between the pixel boundary

<img width="1106" alt="Screen Shot 2021-11-26 at 7 30 27 PM" src="https://user-images.githubusercontent.com/20819712/143574635-78ae9413-417a-4336-a241-fc646df24428.png">

2021-11-29 04:34 UTC, YuHsuan-Hwang commented
> * 1px mis-alignment between coordinate box and colorbar box (this might be the same root cause as the next one). This is also observed when the colorbar is vertical.

Fixed: avoided the 1 px border and ticks rendered with 2 px on Retina displays

> * the boundary between adjacent color blocks is not sharp (cf the pixel rendering which is sharp between the pixel boundary

This is expected in our current approach. We generate a list of colors and positions, and render a gradient in a box. Will need special handling for the discrete color scale if we want to remove the blurry boundary.

2021-11-29 05:32 UTC, kswang1029 approved these changes

2021-11-29 05:42 UTC, merged