rescale pixels appropriately before rounding in shader
CARTAvis/carta-frontend pull request #1759
Opened 2022-01-13 17:24 UTC by veggiesaurus

Closes #1708 by first scaling the smaller pixel dimension up before rounding (and then scaling back down).

This approach keeps the `floor` function which fixed the issues described in #1529.

2022-01-15 03:12 UTC, kswang1029 requested changes
I am still seeing (on a Retina display for now as I am out of town with a MBP16)
- artifacts at top and right side of the image
- panning image is still jumpy

2022-01-17 07:19 UTC, veggiesaurus commented
> * panning image is still jumpy

I think this is a separate issue, unrelated to the actual shader code or rendering artifact.

2022-01-18 03:59 UTC, kswang1029 commented
@veggiesaurus This is what I see on both retina and non-retina displays. Test image attached. 

![Screen Shot 2022-01-18 at 11 57 47](https://user-images.githubusercontent.com/20819712/149868475-32bf86e0-2387-4a92-83e8-68067b7924c7.png)

[image_4_4.fits.zip](https://github.com/CARTAvis/carta-frontend/files/7886078/image_4_4.fits.zip)

2022-01-18 04:01 UTC, kswang1029 commented
> > * panning image is still jumpy
> 
> I think this is a separate issue, unrelated to the actual shader code or rendering artifact.

Will the jumpy fix be in this PR too?

2022-02-25 07:23 UTC, veggiesaurus commented
> @veggiesaurus This is what I see on both retina and non-retina displays. The artifacts appear at higher zoom levels. Test image attached.
> 
> ![Screen Shot 2022-01-18 at 11 57 47](https://user-images.githubusercontent.com/20819712/149868475-32bf86e0-2387-4a92-83e8-68067b7924c7.png)
> 
> [image_4_4.fits.zip](https://github.com/CARTAvis/carta-frontend/files/7886078/image_4_4.fits.zip)

@kswang1029 are the pixel errors better or worse than the issue that this PR fixes? To me, #1708 is far more critical.

2022-02-25 07:29 UTC, kswang1029 commented
> > @veggiesaurus This is what I see on both retina and non-retina displays. The artifacts appear at higher zoom levels. Test image attached.
> > ![Screen Shot 2022-01-18 at 11 57 47](https://user-images.githubusercontent.com/20819712/149868475-32bf86e0-2387-4a92-83e8-68067b7924c7.png)
> > [image_4_4.fits.zip](https://github.com/CARTAvis/carta-frontend/files/7886078/image_4_4.fits.zip)
> 
> @kswang1029 are the pixel errors better or worse than the issue that this PR fixes? To me, #1708 is far more critical.

Those edge artifacts are similar before/after the current fix. Yes, jumpy pan is far more critical than these edge artifacts.

2022-02-25 07:30 UTC, veggiesaurus commented
> > @kswang1029 are the pixel errors better or worse than the issue that this PR fixes? To me, #1708 is far more critical.
> 
> Those edge artifacts are similar before/after the current fix. Yes, jumpy pan is far more critical than these edge artifacts.

Ok, then shall we merge this in?

2022-02-25 08:56 UTC, merged