Ajm/remove circleci format test
CARTAvis/carta-frontend pull request #1809
Opened 2022-03-22 10:55 UTC by ajm-asiaa

2022-03-22 10:56 UTC, ajm-asiaa commented
@veggiesaurus Actually, I forgot that the _frontend_ format check was not actually using CircleCI! It was actually running through Jenkins. So the title here is misleading!

Anyway, the Jenkins format check is now removed.  It seems to work OK without the "n 12 / n 14 / n16" lines so maybe they are no longer necessary. 

For the Github actions, I think 

> on:
>   push:
>     branches:
>       - '**'

will be enough to run on every commit and likely pull requests too (Let's see).

2022-03-23 12:07 UTC, veggiesaurus requested changes

2022-03-23 12:07 UTC, veggiesaurus commented on .github/workflows/continuous_integration.yml
> +      - '**'
same comment as the other PR. You can just use `on: push` here, to trigger on all branches. See [here](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-events-to-trigger-workflows) for details.

2022-03-23 12:46 UTC, merged

2022-03-23 12:46 UTC, ajm-asiaa commented
I thought I would also shorten the name so it fits on the list better if that is OK with you?
I changed `Continuous Integration` to `CI`.
![Screen Shot 2022-03-23 at 8 43 09 PM](https://user-images.githubusercontent.com/20802551/159702113-162f0aee-07ed-4a60-bd11-007e19464e57.png)

2022-03-23 12:48 UTC, ajm-asiaa commented
Yes. Looks better now
![Screen Shot 2022-03-23 at 8 47 39 PM](https://user-images.githubusercontent.com/20802551/159702679-636b5715-db5a-4277-ae9c-04aa3b85f3c7.png)