Angus/refactoring
CARTAvis/carta-frontend pull request #1810
Opened 2022-03-22 12:19 UTC by veggiesaurus

Refactoring: moves per-Frame stores to a `stores/Frame` subfolder. The rest of the changes are just adjusting the imports

2022-03-22 12:21 UTC, veggiesaurus commented on src/models/LayoutConfig.ts
> +import {smoothStepOffset} from "utilities/math";
this seems to be necessary to prevent a circular dependency

2022-03-23 06:13 UTC, kswang1029 approved these changes
All current e2e tests are passing. I assume this is fine. 👍

2022-03-23 13:04 UTC, YuHsuan-Hwang requested changes

2022-03-23 13:04 UTC, YuHsuan-Hwang commented on src/models/CatalogControlMap.ts
> +
remove extra line

2022-03-23 13:04 UTC, YuHsuan-Hwang commented on src/stores/Frame/index.ts
> +export * from "./ContourConfigStore";
remove duplicate line

2022-03-23 14:01 UTC, YuHsuan-Hwang approved these changes

2022-03-28 07:58 UTC, merged