Mylin/1617 support spatial profile line polyline
CARTAvis/carta-frontend pull request #1812
Opened 2022-03-25 09:07 UTC by acdo2002

Fixed #1617 
The corresponding backend [PR1020](https://github.com/CARTAvis/carta-backend/pull/1020)

2022-04-14 09:54 UTC, kswang1029 commented
I have had a preview of this branch and found few issues that need to be addressed:
1. when the region is point or cursor, the x label of the profile plot is "X coordinate" or "Y coordinate" (with an implicit unit of "pixel". When the region is line (not polyline), the x label should be revised to offset with a unit (eg Offset (arcsec). The actual unit (arcsec, arcmin, or degree) is determined by the angular size of the line region and the backend should already have a handle on this based on the implementation of pv generator. When the region is polyline, the x label should be "Distance" with a unit. 
2. the backend supports cancellation of spatial profile calculations. That is, if we update the line or polyline region, old calculations will be terminated and new calculations will start. So before the new results come in, we need to have visual indication that the backend is working on it. Similar to region spectral profilers, we should set the old profile dimmer.
3. the red vertical line should disappear when the region type is line and polyline.

2022-04-15 09:11 UTC, acdo2002 commented
@kswang1029 
I have shown the current frontend to Tien-Hao and already discussed with Tien-Hao.
1. may need the modification of ICD message, I leave it later.
2. may need the modification of ICD message, I leave it later.
3. Fixed, I have let the red vertical line to be transparent if the region is line/polyline. (the enhancement please issue it in the future)
4. It is because once the region (no matter the region is line/polyline) is deleted, the cursor will show the previous cursor spatial profile data. If you move the cursor (slightly around the region) before you delete the region, the cursor will show a relatively correct value. We think this is another issue.
5. Fixed the coordinate string, now it will show "Profile: Region # number" in the spatial profiler widget
6. Fixed the scss.

2022-04-17 04:02 UTC, kswang1029 commented
> 4. It is because once the region (no matter the region is line/polyline) is deleted, the cursor will show the previous cursor spatial profile data. If you move the cursor (slightly around the region) before you delete the region, the cursor will show a relatively correct value. We think this is another issue.

issue filed at https://github.com/CARTAvis/carta-frontend/issues/1831

2022-04-26 05:59 UTC, kswang1029 commented
@acdo2002 the displayed unit in the cursor info text string needs to be sync'd to the actual unit of the line/polyline region.
![Screen Shot 2022-04-26 at 13 57 48](https://user-images.githubusercontent.com/20819712/165231692-6af94ac0-88d0-429d-abfc-66718e59dd1d.png)

2022-04-26 06:12 UTC, kswang1029 commented
@acdo2002 when it is line or polyline profile being displayed, the header of the exported tsv file needs to be updated and include the line or polyline information. At the moment it is still a point region. 
![Screen Shot 2022-04-26 at 14 10 36](https://user-images.githubusercontent.com/20819712/165233658-8bc3659b-8544-4003-8e97-82d5c3c2c79a.png)

2022-04-26 06:40 UTC, kswang1029 commented
@acdo2002 spotted a frontend crash. If we explicitly set the image dropdown to an image (not "Active") and explicitly set the region dropdown to a line region (not "Active"), then if we delete the region, frontend will crash.
![Screen Shot 2022-04-26 at 14 38 31](https://user-images.githubusercontent.com/20819712/165237622-0406989c-4b77-49b8-a58c-a8a48fc26cff.png)

2022-04-26 14:53 UTC, kswang1029 commented
@TienHao as we have a new “compute” tab in the settings dialog, please add a placeholder for the in-app help.

2022-04-27 03:44 UTC, kswang1029 commented
@TienHao Please help to refine the cursor info:
1. when the region is line or polyline, we don't need to show world coordinate in the cursor info
2. please switch to scientific notation to show distance or offset. %.5e should be good enough. 

![Screen Shot 2022-04-27 at 11 41 38](https://user-images.githubusercontent.com/20819712/165435690-dd8a0872-4e47-42c3-a3dc-7c21964ca60d.png)

2022-04-27 03:57 UTC, kswang1029 commented
@TienHao The tsv header needs another tweak. When the profile is from line or polyline region, we should say "Region Profile" instead of "X profile" in the first line.
![Screen Shot 2022-04-27 at 11 55 05](https://user-images.githubusercontent.com/20819712/165436945-17328e20-d8f4-4cbe-a5bb-d94b90c60b18.png)

2022-04-27 04:46 UTC, kswang1029 commented
@TienHao please enable auto y-scale when zooming for a line or polyline profile, just like point or cursor region profile.

2022-04-27 05:28 UTC, kswang1029 commented
@TienHao The title of the settings dialog needs a tweak too. In addition, the show mean/rms function does not work for line/polyline profile. 
![Screen Shot 2022-04-27 at 13 26 18](https://user-images.githubusercontent.com/20819712/165447207-c39b602d-9c1b-4502-8728-0ef56ef53678.png)

2022-04-29 09:55 UTC, kswang1029 commented
@YuHsuan-Hwang @veggiesaurus I have had brief tests during the draft PR stage. Now it is ready for code review. I will continue my tests before approving.

2022-05-03 05:09 UTC, kswang1029 approved these changes
@TienHao @acdo2002 this works nicely. 👍

2022-05-06 04:15 UTC, YuHsuan-Hwang requested changes
The changes look good to me. only very minor issues.

2022-05-06 04:15 UTC, YuHsuan-Hwang commented on src/components/SpatialProfiler/SpatialProfilerComponent.tsx
> +        const plotName = `${this.lineAxis ? "" : isXProfile ? "X" : "Y"} profile`;
remove extra space for line regions in filename
<img width="677" alt="image" src="https://user-images.githubusercontent.com/43841102/167063125-d74418f4-6796-447a-8d43-ffa6d2707827.png">

2022-05-06 04:15 UTC, YuHsuan-Hwang commented on src/stores/Frame/RegionStore.ts
> +                return `Line (pixel) [[${this.controlPoints[0].x}, ${this.controlPoints[0].y}], [${this.controlPoints[1].x}, ${this.controlPoints[1].y}]]`;
Shall we fix the precision to 6 and add unit `pix`? Shall we show "[Invalid]" if the value does not exist?

2022-05-06 04:15 UTC, YuHsuan-Hwang commented on src/stores/Frame/RegionStore.ts
> +                    polylineProperties += isFinite(point.x) && isFinite(point.y) ? `[${toFixed(point.x, 6)}, ${toFixed(point.y, 6)}]` : "[Invalid]";
Shall we add unit `pix`?

2022-05-06 12:49 UTC, acdo2002 commented on src/components/SpatialProfiler/SpatialProfilerComponent.tsx
> +        const plotName = `${this.lineAxis ? "" : isXProfile ? "X" : "Y"} profile`;
Fixed!

2022-05-06 12:50 UTC, acdo2002 commented on src/stores/Frame/RegionStore.ts
> +                return `Line (pixel) [[${this.controlPoints[0].x}, ${this.controlPoints[0].y}], [${this.controlPoints[1].x}, ${this.controlPoints[1].y}]]`;
I add the lineProperties, making the format similar to polygonProperties & polylineProperties.

2022-05-06 12:50 UTC, acdo2002 commented on src/stores/Frame/RegionStore.ts
> +                    polylineProperties += isFinite(point.x) && isFinite(point.y) ? `[${toFixed(point.x, 6)}, ${toFixed(point.y, 6)}]` : "[Invalid]";
Fixed!

2022-05-06 13:52 UTC, acdo2002 commented
@YuHsuan-Hwang I try my best to solve the merge conflicts (as well as solve the minor issue you suggested), could you check whether this branch is working fine or not?
At least this branch can build successfully on my MacOS 11 laptop, I will try to build on my Ubuntu laptop in the weekend.

2022-05-06 14:51 UTC, YuHsuan-Hwang approved these changes
> @YuHsuan-Hwang I try my best to solve the merge conflicts (as well as solve the minor issue you suggested), could you check whether this branch is working fine or not?
At least this branch can build successfully on my MacOS 11 laptop, I will try to build on my Ubuntu laptop in the weekend.

@acdo2002 looks fine to me 👍

2022-05-09 06:04 UTC, acdo2002 commented
I have tried to build it on ubuntu 20.04, it looks fine.

2022-05-10 17:03 UTC, merged