Angus/1155 vector fields
CARTAvis/carta-frontend pull request #1829
Opened 2022-04-13 08:46 UTC by veggiesaurus

Draft PR for #1155. Still to do:

- [ ] Correct handling of intensity/angle Stokes coordinates
- [ ] Adding overlay toggle icon to the image view widget
- [ ] Support spatial matched images (if identical FoV/projection) when not in tiled view
- [ ] Include vector overlay output when saving images

To handle in later PRs:
- Support spatially matched images using control maps
- Support ZFP compression when requesting tiles

2022-04-14 08:03 UTC, kswang1029 commented
@veggiesaurus @markccchiang here is a set of issues I spotted so far. Most of them are minor.  

[frontend] When debiasing toggle is on, the Apply button is not greyed out after a click.

[frontend] Pixel Averaging text input should correct user input if it is not an allowed value (eg 1, 3 or -1 etc).

[frontend] default Line Length Max to 20 (better UX in my opinion). 

[backend / frontend] possibly there are vector components rendered on top of empty pixels (ie outside the image) or on top of NaN pixels. 

[frontend] UI element alignment in the Styling tab. The ones in the Configuration tab are well aligned. 

[frontend] when the mode is "Angle Only (lines)", the radio buttons of "Polarization intensity" need to be greyed out.

[frontend / backend] I see the default threshold is 0 and is set in the SET_VECTOR_OVERLAY_PARAMETERS message and the backend applies it to the vector field data calculation. The default threshold should be NaN so that the backend does not apply a threshold in the calculations. 

[frontend] default contour color becomes white? (Should be green IIRC)

2022-04-20 11:26 UTC, veggiesaurus commented
@kswang1029 

- [x] [frontend] When debiasing toggle is on, the Apply button is not greyed out after a click.
- [x] [frontend] default Line Length Max to 20 (better UX in my opinion).
- [x] [frontend] UI element alignment in the Styling tab. The ones in the Configuration tab are well aligned.
- [x] [frontend] when the mode is "Angle Only (lines)", the radio buttons of "Polarization intensity" need to be greyed out.
- [x] [frontend / backend] I see the default threshold is 0 and is set in the SET_VECTOR_OVERLAY_PARAMETERS message and the backend applies it to the vector field data calculation. The default threshold should be NaN so that the backend does not apply a threshold in the calculations.
- [x] [frontend] default contour color becomes white? (Should be green IIRC)
- [x] [frontend] could you add a new UI field as "extra rotation" in degrees please? Then we will need to apply this angle offset to the computed PA. The use case is to turn polarization orientation to magnetic field orientation (here it is 90 degrees offset).
- [x] [frontend] refine the checker for threshold text input field. Usually the value is quite small such as 0.0001. At the moment it is tricky to refine the value from 0.0001 to 0.0002 for example.
- [x] [frontend] for line length (px) min and max, it will have better UX if it is a spin box so users can continuously change length by multiple clicking the spin up/down button and see the results changing.

> [frontend] Pixel Averaging text input should correct user input if it is not an allowed value (eg 1, 3 or -1 etc).

Can we fix this in a separate PR? It's more related to the actual input element's display. The value itself gets corrected.

> [backend / frontend] possibly there are vector components rendered on top of empty pixels (ie outside the image) or on top of NaN pixels.

Confirmed non-issue

2022-04-20 12:01 UTC, veggiesaurus commented
The one remaining issue before marking as ready for review is the incorrect length and thickness of markers. They're correct on the spatial reference image (left), but not on other images.

![C fits-C_pxScaled_0 05 fits-image-2022-04-20-14-00-29](https://user-images.githubusercontent.com/592504/164225894-3391e16c-0f0d-4202-a535-1ee51bffed4e.png)

2022-04-22 03:23 UTC, kswang1029 commented
@veggiesaurus found a critical issue, likely our old friend "deviceRatio" 🙈
On a Retina display the spatial matching does not work properly. 
![Uploading HD142527_Stokes_IQU.fits-HD142527_Stokes_IQU_lpoli.image.fits-image-2022-04-22-11-19-32.png…]()

2022-04-22 05:36 UTC, kswang1029 commented
@veggiesaurus found another odd behavior when spatial matching is on:
The example here is I have two sources on the sky (one at North, the other at South), and I have two images with each centered at different sources. 
<img width="1064" alt="Screen Shot 2022-04-22 at 13 35 48" src="https://user-images.githubusercontent.com/20819712/164610032-e3e69144-36c5-4a46-9263-c8002084caec.png">

Now I load them, match them and use the first image as the data source to generate the vector field layers. As we can see the vector field is not matched properly on the second image. 

<img width="1069" alt="Screen Shot 2022-04-22 at 13 30 21" src="https://user-images.githubusercontent.com/20819712/164609715-fd2983d5-8356-4191-aa0c-ea7d3104b2ef.png">

if we enable threshold, the vector field on the second image becomes even odd.
<img width="1062" alt="Screen Shot 2022-04-22 at 13 34 10" src="https://user-images.githubusercontent.com/20819712/164609917-efdeae6d-cd45-4b25-a9d6-ae8815b49d73.png">

2022-04-22 06:03 UTC, kswang1029 commented
@veggiesaurus other minor comments to consider:

1. [optional UX enhancement] auto-select "Computed PA" and "Computed PI" if the Data Source has Stokes QU

2. Allowing pixel averaging factor options to include 1

3. Set the threshold unit to the image pixel unit instead of % when fractional is selected. I had some experiments with the help from Mark to see if we can use fractional % for masking but the result is bad. So we will need to use Stokes I (or PI, TBD) value for masking in order to get good results.

4. if it is Fractional selected, the "Intensity (Jy/beam)" in Styling tab should be revised to "Fractional (%)" I think. 

5. [question] I haven't tried this extreme case but can we have layers of one raster + multiple contours + multiple catalogs + multiple vector field layers at the same time? I remembered Qi mentioned a limitation of WebGL instances a while ago when he was trying to use WebGL acceleration from plotly for all plots?

6. Just for consistency: "Angular source" -> "Angular Source", "Intensity source" -> "Intensity Source". Question: is it angular source or angle source more sensible? 

7. When streaming vector data, do we show the green cloud indicator at the top right corner too?

2022-04-22 09:13 UTC, YuHsuan-Hwang reviewed
I have some minor comments about the dialog UI

2022-04-22 09:13 UTC, YuHsuan-Hwang commented on src/components/Dialogs/VectorOverlayDialog/VectorOverlayDialogComponent.tsx
> +                    <SafeNumericInput placeholder="Pixel Averaging" min={2} max={64} value={this.pixelAveraging} majorStepSize={2} stepSize={2} onValueChange={this.handlePixelAveragingChanged} />
Shall we also allow `pixelAveraging = 1`?

2022-04-22 09:13 UTC, YuHsuan-Hwang commented on src/components/Dialogs/VectorOverlayDialog/VectorOverlayDialogComponent.tsx
> +                        <option value={VectorOverlaySource.Computed}>Computed PA (if available)</option>
Would it be more clear to the users if we hide this option when PA is not available?

2022-04-22 09:13 UTC, YuHsuan-Hwang commented on src/components/Dialogs/VectorOverlayDialog/VectorOverlayDialogComponent.tsx
> +                        <option value={VectorOverlaySource.Computed}>Computed PI (if available)</option>
Same comment when PI is not available

2022-04-22 09:13 UTC, YuHsuan-Hwang commented on src/components/Dialogs/VectorOverlayDialog/VectorOverlayDialogComponent.tsx
> +                <FormGroup inline={true} label="Polarization Intensity" disabled={this.intensitySource === VectorOverlaySource.None}>
The unit can be displayed with `labelInfo`. Same comments for all the other `FormGroup` elements.

2022-04-22 09:13 UTC, YuHsuan-Hwang commented on src/components/Dialogs/VectorOverlayDialog/VectorOverlayDialogComponent.tsx
> +            <FormGroup label={`Intensity (${frame.unit})`} inline={true}>
Shall we disable these inputs when intensity source is None?
Also the column widths seems to change after applying the vectors.
<img width="402" alt="image" src="https://user-images.githubusercontent.com/43841102/164650910-01c9bcd7-ed7b-49d8-b2eb-d722504630ac.png">
<img width="402" alt="image" src="https://user-images.githubusercontent.com/43841102/164651014-f789bf84-57e7-4501-90ed-0a20dbb1f860.png">

2022-04-22 09:13 UTC, YuHsuan-Hwang commented on src/components/Dialogs/VectorOverlayDialog/VectorOverlayDialogComponent.tsx
> +    @action setDefaultVectorOverlayParameters() {
may change to an arrow function

2022-04-22 09:13 UTC, YuHsuan-Hwang commented on src/components/Dialogs/VectorOverlayDialog/VectorOverlayDialogComponent.tsx
> +                            <SafeNumericInput min={config.lengthMin} disabled={angleOnly} value={config.lengthMax} onValueChange={val => config.setLengthRange(config.lengthMin, val)} />
Seems that max length is applied when `angleOnly`. Shall we allow users change this value when `angleOnly`?

2022-04-22 09:13 UTC, YuHsuan-Hwang commented on src/components/Dialogs/VectorOverlayDialog/VectorOverlayDialogComponent.tsx
> +                        <AnchorButton intent={Intent.SUCCESS} onClick={this.handleApplyOverlay} disabled={!this.configChanged && dataSource.vectorOverlayConfig.enabled} text="Apply" />
maybe we could disable Apply button when both angle and intensity source is None

2022-04-27 16:06 UTC, veggiesaurus commented
> @veggiesaurus found another odd behavior when spatial matching is on (this is again with retina display): The example here is I have two sources on the sky (one at North, the other at South), and I have two images with each centered at different sources. <img alt="Screen Shot 2022-04-22 at 13 35 48" width="1064" src="https://user-images.githubusercontent.com/20819712/164610032-e3e69144-36c5-4a46-9263-c8002084caec.png">
> 
> Now I load them, match them and use the first image as the data source to generate the vector field layers. As we can see the vector field is not matched properly on the second image.
> 
> <img alt="Screen Shot 2022-04-22 at 13 30 21" width="1069" src="https://user-images.githubusercontent.com/20819712/164609715-fd2983d5-8356-4191-aa0c-ea7d3104b2ef.png">
> 
> if we enable threshold, the vector field on the second image becomes even odd. <img alt="Screen Shot 2022-04-22 at 13 34 10" width="1062" src="https://user-images.githubusercontent.com/20819712/164609917-efdeae6d-cd45-4b25-a9d6-ae8815b49d73.png">

> 
> UPDATE: the above issue can only be reproduced with a Retina display.

Weird, it seems to work fine for me, with `devicePixelRatio = 2` or `1` :thinking: 
![member uid___A001_X13a_X15d w51e2 StokesIQU clean image fits-member uid___A001_X13a_X15d w51e8 StokesIQU clean image fits-image-2022-04-27-18-02-59](https://user-images.githubusercontent.com/592504/165562529-f1cd22fe-1e7e-41a6-b1a1-1eec8e3de2e7.png)

2022-04-27 16:34 UTC, veggiesaurus commented on src/components/Dialogs/VectorOverlayDialog/VectorOverlayDialogComponent.tsx
> +                    <SafeNumericInput placeholder="Pixel Averaging" min={2} max={64} value={this.pixelAveraging} majorStepSize={2} stepSize={2} onValueChange={this.handlePixelAveragingChanged} />
fixed :+1:

2022-04-27 17:18 UTC, veggiesaurus commented
> @veggiesaurus other minor comments to consider:
> 


- [ ] 1. [optional UX enhancement] auto-select "Computed PA" and "Computed PI" if the Data Source has Stokes QU
- [ ] 2. Allowing pixel averaging factor options to include 1
- [ ]  3. Set the threshold unit to the image pixel unit instead of % when fractional is selected. I had some experiments with the help from Mark to see if we can use fractional % for masking but the result is bad. So we will need to use Stokes I (or PI, TBD) value for masking in order to get good results.
- [ ]  4. if it is Fractional selected, the "Intensity (Jy/beam)" in Styling tab should be revised to "Fractional (%)" I think.
- [ ]  6. Just for consistency: "Angular source" -> "Angular Source", "Intensity source" -> "Intensity Source". Question: is it angular source or angle source more sensible?
- [ ] > 7. When streaming vector data, do we show the green cloud indicator at the top right corner too?

> 5. [question] I haven't tried this extreme case but can we have layers of one raster + multiple contours + multiple catalogs + multiple vector field layers at the same time? I remembered Qi mentioned a limitation of WebGL instances a while ago when he was trying to use WebGL acceleration from plotly for all plots?

Shouldn't be a problem. We only have a single webgl instance for each feature (raster, contour, catalog, overlay), versus per-image.

> 8. when the color mode is color-mapped, do we map Intensity Min and Intensity Max (as defined in the same Styling tab) to the colormap?

We scale from [intensity min, intensity max] to [0, 1] linearly and then map that to the colormap. Same process as contours (where we scale from [lowest contour level, highest contour level] to [0, 1]

2022-04-29 01:58 UTC, kswang1029 commented
@veggiesaurus 
> * [x]  2. Allowing pixel averaging factor options to include 1

If we click the spin down button to set the pixel averaging factor to 1 and click spin up button, we will see odd factors. Maybe we need a toggle to disable pixel averaging instead (factor =1)? 🤔

2022-04-29 03:11 UTC, kswang1029 commented
@veggiesaurus @YuHsuan-Hwang 
Safari (Version 15.4 (17613.1.17.1.13)) is naughty!  It appears that the rendered line segments have an upper limit in total number. Following is with AMD GPU (so no my weird matching issue from my intel  GPU) at different averaging factors. With Chrome it is free of this issue.

![Screen Shot 2022-04-29 at 11 04 04](https://user-images.githubusercontent.com/20819712/165879697-7b3e79a7-3b95-439b-a502-def1765d183b.png)

![Screen Shot 2022-04-29 at 11 04 16](https://user-images.githubusercontent.com/20819712/165879698-25c4c615-3b82-4cbc-8fe1-68f7b1b7c99c.png)

![Screen Shot 2022-04-29 at 11 03 23](https://user-images.githubusercontent.com/20819712/165879686-1d9a10f4-ec93-4616-8ed8-9304208600a8.png)

![Screen Shot 2022-04-29 at 11 03 48](https://user-images.githubusercontent.com/20819712/165879694-d7c1f858-8c28-4590-b2c5-ecf12b157faf.png)

2022-04-29 03:24 UTC, kswang1029 commented
> We scale from [intensity min, intensity max] to [0, 1] linearly and then map that to the colormap. Same process as contours (where we scale from [lowest contour level, highest contour level] to [0, 1]

@veggiesaurus ok. If there is one image only, then color-mapped vector field rendering works as expected. However, if there is a matched image, it does not. The scale changes in an unexpected way and it appears changing to a different colormap does not work.

2022-05-04 07:54 UTC, veggiesaurus commented
> If we click the spin down button to set the pixel averaging factor to 1 and click spin up button, we will see odd factors. Maybe we need a toggle to disable pixel averaging instead (factor =1)? thinking

ok, we can do that instead.

2022-05-05 03:34 UTC, kswang1029 commented
@veggiesaurus I had some tests with the latest commit [d647780](https://github.com/CARTAvis/carta-frontend/pull/1829/commits/d647780c57d298bf4ceaac4632dcad50c94ce7ca) and here is probably the last set of comments:

1. The unit of Threshold should be the same as the unit of the image when Polarization intensity is Absolute or Fractional. Typo in the unit: {Jy/beam)

2. When there is a matched image, the color mode "color-mapped" is not working (eg changing a different colormap does not work correctly, you can try grey but we will see yellow vector segments) 

3. When Polarization Intensity is Fractional, in the Styling tab the unit of the Intensity Min/Max should be %.

2022-05-05 08:12 UTC, veggiesaurus commented
> When there is a matched image, the color mode "color-mapped" is not working (eg changing a different colormap does not work correctly, you can try grey but we will see yellow vector segments)

@kswang1029 I will just try to fix this and then re-request reviews.

2022-05-05 09:39 UTC, kswang1029 commented
@veggiesaurus @YuHsuan-Hwang happy to report that with [1785db7](https://github.com/CARTAvis/carta-frontend/pull/1829/commits/1785db751117fe83bc2eba9a782482c715b7d146) the spatial matching issue with my local intel GPU is gone~

2022-05-05 09:57 UTC, kswang1029 commented
> @veggiesaurus @YuHsuan-Hwang Safari (Version 15.4 (17613.1.17.1.13)) is naughty! It appears that the rendered line segments have an upper limit in total number. Following is with AMD GPU (so no my weird matching issue from my intel GPU) at different averaging factors. With Chrome it is free of this issue.
> 
> ![Screen Shot 2022-04-29 at 11 04 04](https://user-images.githubusercontent.com/20819712/165879697-7b3e79a7-3b95-439b-a502-def1765d183b.png)
> 
> ![Screen Shot 2022-04-29 at 11 04 16](https://user-images.githubusercontent.com/20819712/165879698-25c4c615-3b82-4cbc-8fe1-68f7b1b7c99c.png)
> 
> ![Screen Shot 2022-04-29 at 11 03 23](https://user-images.githubusercontent.com/20819712/165879686-1d9a10f4-ec93-4616-8ed8-9304208600a8.png)
> 
> ![Screen Shot 2022-04-29 at 11 03 48](https://user-images.githubusercontent.com/20819712/165879694-d7c1f858-8c28-4590-b2c5-ecf12b157faf.png)

To add more clues on this, if we load an image as 512 x 512 and render the vector field overlay with an averaging factor of 2 (so there are 256 x 256 elements), it works fine. But if there no averaging, meaning to rendering 512 x 512 elements, then it does not work properly.

2022-05-06 02:29 UTC, kswang1029 commented
@veggiesaurus shall we add a "lock" icon next to the data source dropdown too?

![Screen Shot 2022-05-06 at 10 28 15](https://user-images.githubusercontent.com/20819712/167056949-c340edd1-38bd-44ff-8033-48024815e79b.png)

2022-05-06 06:15 UTC, veggiesaurus commented
> @veggiesaurus shall we add a "lock" icon next to the data source dropdown too?
> 
> ![Screen Shot 2022-05-06 at 10 28 15](https://user-images.githubusercontent.com/20819712/167056949-c340edd1-38bd-44ff-8033-48024815e79b.png)

can we add this as a separate issue?

2022-05-06 06:16 UTC, kswang1029 commented
> > @veggiesaurus shall we add a "lock" icon next to the data source dropdown too?
> > ![Screen Shot 2022-05-06 at 10 28 15](https://user-images.githubusercontent.com/20819712/167056949-c340edd1-38bd-44ff-8033-48024815e79b.png)
> 
> can we add this as a separate issue?

ok

2022-05-06 07:55 UTC, kswang1029 approved these changes

2022-05-06 08:22 UTC, YuHsuan-Hwang requested changes
The shaders look good to me. I have only minor comments.
About file naming, would it be clearer if we rename the files as "..._shader_vectors.glsl"?

2022-05-06 08:22 UTC, YuHsuan-Hwang commented on src/components/Dialogs/VectorOverlayDialog/VectorOverlayDialogComponent.tsx
> +        this.pixelAveraging = value;
We may still need `Math.floor(value * 0.5) * 2.0` when users input non integer values.

2022-05-06 08:22 UTC, YuHsuan-Hwang commented on src/stores/Frame/FrameStore.ts
> +    @computed get requiredStokesName(): string {
looks like an unused variable

2022-05-06 08:22 UTC, YuHsuan-Hwang commented on src/components/ImageView/VectorOverlayView/VectorOverlayView.tsx
> +        this.gl.uniform1f(shaderUniforms.CanvasSpaceLineWidth, lineThickness);
Could we simplify to `pixelRatio * frame.vectorOverlayConfig.thickness` and remove `lineThickness`?

2022-05-09 08:49 UTC, veggiesaurus commented
> The shaders look good to me. I have only minor comments. About file naming, would it be clearer if we rename the files as "..._shader_vectors.glsl"?

Can we do this in a separate branch? Since this means changes across multiple features

2022-05-09 08:53 UTC, veggiesaurus commented
@YuHsuan-Hwang I've implemented the changes you suggested

2022-05-09 09:03 UTC, YuHsuan-Hwang commented
> > The shaders look good to me. I have only minor comments. About file naming, would it be clearer if we rename the files as "..._shader_vectors.glsl"?
> 
> Can we do this in a separate branch? Since this means changes across multiple features

Ok

2022-05-09 09:03 UTC, YuHsuan-Hwang approved these changes

2022-05-09 13:18 UTC, merged