Thchang/1546 exporting full resolution data in the spatial profiler
CARTAvis/carta-frontend pull request #1865
Opened 2022-05-23 07:24 UTC by TienHao

closes #1546: exporting full resolution data when showing decimated data in the plotting of the spatial profiler

changes:
- added `exportData` in LinePlotComponentProps to export data which are different from the plotting `data`.
- applied `exportData` to contain full resolution(un-decimated) data in the spatial profiler.

2022-05-24 08:42 UTC, veggiesaurus requested changes

2022-05-24 08:42 UTC, veggiesaurus commented on src/components/Shared/LinePlot/LinePlotComponent.tsx
> +            const data = this.props.exportData?.length > 0 ? this.props.exportData : this.props.data;
I'd prefer it if we used something like `fullResolutinoData` instead of `exportData`, as we may reuse this elsewhere.

2022-05-25 02:57 UTC, YuHsuan-Hwang commented on src/components/Shared/LinePlot/LinePlotComponent.tsx
> +    exportData?: {x: number; y: number; z?: number}[];
Maybe not related to the fix, but I wonder if we can remove `z` and use `Point2D[]` for `exportData` and also `data`. Seems that `z` is not used, and it was for inheritance in `ScatterPlot`.

2022-05-26 06:46 UTC, kswang1029 approved these changes
👍

2022-05-26 07:41 UTC, TienHao commented on src/components/Shared/LinePlot/LinePlotComponent.tsx
> +            const data = this.props.exportData?.length > 0 ? this.props.exportData : this.props.data;
modified!

2022-05-26 07:44 UTC, TienHao commented on src/components/Shared/LinePlot/LinePlotComponent.tsx
> +    exportData?: {x: number; y: number; z?: number}[];
modified!

2022-05-27 05:08 UTC, YuHsuan-Hwang approved these changes

2022-05-27 05:55 UTC, veggiesaurus requested changes

2022-05-27 05:55 UTC, veggiesaurus commented on src/components/SpatialProfiler/SpatialProfilerComponent.tsx
> +            let fullResolutionValues: Array<{x: number; y: number}>;
Can't we use Point2D here?

2022-05-27 09:35 UTC, TienHao commented on src/components/SpatialProfiler/SpatialProfilerComponent.tsx
> +            let fullResolutionValues: Array<{x: number; y: number}>;
fixed

2022-05-27 09:44 UTC, veggiesaurus approved these changes

2022-05-27 10:00 UTC, merged