Thchang/1831 fixed no updating of spatial profilers after region deleting
CARTAvis/carta-frontend pull request #1869
Opened 2022-05-26 08:25 UTC by TienHao

this PR closes #1831. 

The spatial profiler did not update profile from a non-cursor region(selected in the region dropdown) to the cursor region after the non-cursor region was deleted. This was caused by not removing deleted region id from the `regionIdMap` of `SpatialProfilerWidgetStore`, a subclass of `RegionWidgetStore`. I also found this problem in the PV generator for same reason.

changes:
- removing the deleted region id from the `regionIdMap` of all widget stores which extend `RegionWidgetStore`
- refactoring code of closing image and removing frame from `RegionWidgetStore`

2022-05-30 04:39 UTC, kswang1029 requested changes
@TienHao Could you investigate the following case on why the image 1 with active region (ie cursor) does not update a profile after a region is deleted? Image 0 with active region (cursor) does update its profile.


https://user-images.githubusercontent.com/20819712/170918213-6068fd05-1a09-415f-80cf-eeacd2292ba8.mov

2022-05-30 09:21 UTC, TienHao commented
> @TienHao Could you investigate the following case on why the image 1 with active region (ie cursor) does not update a profile after a region is deleted? Image 0 with active region (cursor) does update its profile.

This is related to issue #1855. The regionMaps of `RegionWidgetStore` did not clear previous region id after image matching/unmatching or regions of spatial matching were deleted.

2022-05-31 04:51 UTC, kswang1029 approved these changes
tested manually with the spatial profiler, histogram, and statistics widgets. The behavior is now correct. 👍 e2e tests are all passing.

2022-06-02 07:46 UTC, YuHsuan-Hwang approved these changes

2022-06-08 06:22 UTC, merged