Thchang/1313 fixed stokes scatter plot indicator
CARTAvis/carta-frontend pull request #1872
Opened 2022-06-02 07:09 UTC by TienHao

**Description**
This PR closes #1313: unable to switch channel by clicking scatter plot in stokes widgets when coordinate type is not `channel`.

change: fixed this issue by adding a missing check in onScatterChannelChanged of stokes widgets from PR #827.

**Checklist**
- [x] changelog updated / ~no changelog update needed~
- [ ] e2e test passing / added corresponding fix
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed

2022-06-06 04:13 UTC, kswang1029 commented
@TienHao confirmed this PR does not result in any regressions that the current e2e tests are capable to capture. Manual tests are on the way before approving the PR.

2022-06-06 06:53 UTC, kswang1029 requested changes
Hmm the issue remains. Only it works only when the spectral convention is channel. The expected behavior is when we click a given point in the scatter plot, effectively we switch to that channel so we see the correct channel image and the red vertical lines in the profile plots are rendered at the correct channel. 


https://user-images.githubusercontent.com/20819712/172110658-017df89f-47e4-47e5-a300-4204ef986abd.mov

2022-06-21 02:19 UTC, kswang1029 approved these changes
confirmed the fix works. no regression is observed from the e2e tests.

2022-06-22 06:40 UTC, YuHsuan-Hwang approved these changes

2022-06-22 10:44 UTC, veggiesaurus approved these changes

2022-06-23 06:54 UTC, merged