ksw/update v3 in app help
CARTAvis/carta-frontend pull request #1924
Opened 2022-07-25 03:04 UTC by kswang1029

**Description**
This PR is to address #1833. 

In addition to the help context, I also made minor adjustment of UI labels or default widget size so that UI elements can be displayed properly. 

**Checklist**
- [x] ~~changelog updated~~ / no changelog update needed
- [ ] e2e test passing / added corresponding fix
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed

2022-07-25 09:21 UTC, confluence reviewed
Still reviewing; just saving all my comments so far.

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/AnimatorHelpContent.tsx
> +            The polarization slider includes the Stokes components defined in the image header, as well as the <em>computed</em> components from the Stokes components, such as:
I suggest "components computed from the Stokes components"

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/CatalogHistogramPlotHelpContent.tsx
> +            You may use the <code>Statistic Source</code> dropdown menu to select a numeric column from a catalog to show basic statistical quantities, including data count, mean, rms, standard devia
This is very minor, but I think it would be more appropriate to use `can` here and in other similar phrases.

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/CatalogSettingsColorHelpContent.tsx
> +            This dialog provides options to set a color or a colormap to source markers of an image overlay. The shape of the marker can be set with the <code>Shape</code> dropdown menu. If the <code
I'd say either "apply a color or a colormap to..." or "set the color or the colormap of..."

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/CatalogSettingsColorHelpContent.tsx
> +            colormaps, or clip bounds can be applied. When a source or a set of sources are selected, the marker color is changed to the color as specified with the <code>Overlay Highlight</code> dro
I think this should be "is selected" (both "source" and "set" are singular).

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/CatalogSettingsOrientationHelpContent.tsx
> +            markers are rendered without applying an additional rotation. You may assign a numeric data column for orientation mapping with the <code>Column</code> dropdown menu. Different scaling fu
"without any additional rotation"

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/CursorInfoHelpContent.tsx
> +            The cursor information widget is a centralized place to show cursor information for multiple images. Active image is highlighted in boldface text style. If the cursor is on an unmatched i
"The active image..."

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/CursorInfoHelpContent.tsx
> +            is displayed. If the cursor is on a matched image, the cursor information of all the matched images is displayed respectively. The image matching process can be achieved with the image li
Instead of "The image matching process can be achieved with the image list widget" maybe "The image matching settings can be changed with the image list widget" or "Image matching can be set in the image list widget"?

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/FileBrowserHelpContent.tsx
> +            By default (<code>Filter by file content</code>), only files that met the supported image formats are listed in the image file browser. If you often work with a directory with lots of mix
"If you often work with a directory with lots of mixed kinds of files" -> "If you often work with directories which contain many different types of files" ?

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/FileBrowserHelpContent.tsx
> +            By default (<code>Filter by file content</code>), only files that met the supported image formats are listed in the image file browser. If you often work with a directory with lots of mix
Also "you may wish to"

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/FileBrowserHelpContent.tsx
> +            switch to the alternative image file list generation modes, <code>Filter by extension</code> or <code>All files</code> to speed up the process. This is configurable in the <code>Global</c
"switch to an alternative image file list generation mode"

comma after `<code>All files</code>`

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/FileBrowserHelpContent.tsx
> +            format via <strong>File</strong> -&gt; <strong>Save image</strong>. Note that images can only be saved if appropriate write permissions are configured on the server. Optionally, you may s
"set a new rest frequency in..." or "apply a new rest frequency to...".

I think "may" is fine in phrases like this (where it is describing an optional action).

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/FileBrowserHelpContent.tsx
> +            When an image file is selected, its basic image properties are summarized in the <code>File Information</code> tab on the right-hand side. Full image header is shown in the <code>Header</
"The full image header..."

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/FileBrowserHelpContent.tsx
> +            Region files can be imported via <strong>File</strong> -&gt; <strong>Import regions</strong>. When a region file is selected, its content is shown in the <code>Region Information</code> t
I would change "Regions or a subset of regions" to something like "Some or all regions".

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/FileBrowserHelpContent.tsx
> +            exported as a region text file via <strong>File</strong> -&gt; <strong>Export regions</strong>. CASA and ds9 region text file definitions in world or image coordinate are supported. Note
Is the singular "coordinate" definitely right here? It sounds a bit odd.

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/FileInfoHelpContent.tsx
> +            File header dialog provides a full image header (<code>Header</code> tab) and a summary of the properties of the active image (<code>File Information</code> tab). To view the file headers
"The file header dialog..."

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/FileInfoHelpContent.tsx
> +        The image coordinate in FITS definition is 1-based, meaning that the image coordinate at the center of the bottom-left corner pixel is (1, 1). In CARTA, image coordinate is 0-based so that th
I would write "coordinates" (plural) throughout this paragraph.

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/HistogramHelpContent.tsx
> +            Histogram widget displays a histogram plot based on the selections in the <code>Image</code>, <code>Region</code>, and <code>Polarization</code> dropdown menus. When there is no region or
"The histogram widget..."

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/HistogramHelpContent.tsx
> +            The <code>Region</code> dropdown menu defaults to &quot;Active&quot; region which means a selected region in the image viewer. You can select a region by clicking one in the image viewer,
"by clicking on one"

"clicking on a region entry in the region list widget"

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/HistogramHelpContent.tsx
> +            region list widget. Histogram plot of the selected region will be updated accordingly. When there is no region or no region is selected (active), the entire image is used to compute the h
"The histogram plot"

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/HistogramHelpContent.tsx
> +            The <code>Polarization</code> dropdown menu defaults to &quot;Current&quot; which means the selection as in the animator widget. Beside the Stokes components as defined in the image heade
"Besides the Stokes components..."

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/HistogramHelpContent.tsx
> +            polarization intensity, or polarization angle, etc. are also available.
comma after `etc.` (needs full stop *and* comma)

2022-07-25 09:21 UTC, confluence commented on src/components/HelpDrawer/HelpContent/HistogramHelpContent.tsx
> +        <p>In the current release, the number of histogram bins is automatically derived as the square root of the product of the region bounding box sizes.</p>
"derived from"

2022-07-25 12:37 UTC, confluence requested changes
The may/can usage is complicated and subjective, so maybe it would better to leave it for a separate issue.

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageFittingHelpContent.tsx
> +            The image fitting dialog allows you to fit multiple 2D Gaussian components to your image. The default <code>Data Source</code> is the active image which is the current image in the image
"in single-panel mode"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageFittingHelpContent.tsx
> +            image highlighted with a red box if it is multi-panel mode. You may select other images as the input image with the <code>Data Source</code> dropdown menu. In the current implementation,
"in multi-panel mode"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageFittingHelpContent.tsx
> +            <code>Amplitude</code>, <code>FWHM</code>, and <code>P.A. (deg)</code> (position angle). In the current implementation, center and FWHM are defined in pixels. In a future release, these t
"In a future release, it will also be possible to define these two parameters..."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageFittingHelpContent.tsx
> +            <code>Full Log</code> tab, more information of the fitting results is provided, including the best-fit solution in the image coordinate.
"more information about"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageViewHelpContent.tsx
> +            The image viewer widget serves as the core component of CARTA. It allows you to visualize images as rasters, contours, or vector fields. Region of interests can be defined interactively w
"Region of interests" -> "Regions of interest"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageViewHelpContent.tsx
> +            then top-down order. The image order can be rearranged with the image list widget by <code>drag-and-drop</code>.
"In the multi-panel view mode, the loaded images are rendered in order from left to right and then from top to bottom."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageViewHelpContent.tsx
> +            Information of world coordinate and image coordinate at the cursor position is shown at the top of the image viewer. Pixel value, spectral information, and polarization information are al
"Information about the world coordinates and image coordinates..."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageViewHelpContent.tsx
> +            cursor position, press <code>F</code> key. Different modes to display the cursor information are available in the <code>WCS and Image Overlay</code> tab of the preferences dialog (<strong
"the F key"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageViewHelpContent.tsx
> +            Zoom action can be triggered in different ways. The most common one is to use a mouse and scroll wheel. By scrolling up, the image is zoomed in, while by scrolling down, the image is zoom
"The zoom action"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageViewHelpContent.tsx
> +            Zoom action can be triggered in different ways. The most common one is to use a mouse and scroll wheel. By scrolling up, the image is zoomed in, while by scrolling down, the image is zoom
"You can use the mouse scroll wheel: scroll up to zoom in, and scroll down to zoom out."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageViewHelpContent.tsx
> +            Pan action is achieved by <code>drag-and-drop</code> as default. This default can be changed via the <code>Global</code> tab of the preferences dialog (<strong>File</strong> -&gt; <strong
"The pan action"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageViewHelpContent.tsx
> +            mode is <code>click</code>, which causes the clicked pixel to be centered in the image viewer. When it is the <code>drag-and-drop</code> pan mode, you can temporarily switch to the altern
"When the <code>drag-and-drop</code> pan mode is enabled..."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageViewHelpContent.tsx
> +        <p>A vector field overlay layer can be generated via the vector overlay configuration dialog. Vector field overlay of spatially matched images is re-projected precisely to other spatially mat
"The vector field overlay..."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageViewSettingsHelpContent.tsx
> +        <p>This section allows you to change the ticks properties, including location, density, color, line width, and length of major and minor ticks.</p>
I wonder if it's worth adding a tip that it's not possible to set the visibility of the ticks because of a limitation in the implementation, but that you can set the width to a very small non-zero number to make them effectively invisible.

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageViewSettingsHelpContent.tsx
> +        <p>This section allows you to change the appearance of a beam overlay (visibility, color, type, and line width) and adjust its position in the image viewer.</p>
"the beam overlay"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/ImageViewSettingsHelpContent.tsx
> +            This allows conversions of the spectral axis of a position-velocity image. For example, if the image header supports required information, the axis labels can be displayed as offset v.s.
"if the image header contains the required information"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/LayerListHelpContent.tsx
> +            To change a reference image, <code>right-click</code> on a row to bring up the context menu. The spatial reference image, the spectral reference image, and the raster scaling reference im
"be independently defined" -> "be defined independently"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/LayerListHelpContent.tsx
> +            rule. To change the order, <code>drag-and-drop</code> an image in the list to a desired new order.
"to the desired new position"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/LogHelpContent.tsx
> +            When you believe there is something wrong, please contact the <a href="mailto:support@carta.freshdesk.com">helpdesk</a> or file an issue on{" "}
"If you believe that something is wrong"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/OnlineCatalogQueryHelpContent.tsx
> +            When the database is VizieR, after clicking the <code>Query</code> button, a set of catalog <em>titles</em> will be displayed once you click the <code>VizieR Catalog</code> field. Then yo
"If the database is VizieR, after you have clicked the <code>Query</code> button..."

"You can then select..."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/OnlineCatalogQueryHelpContent.tsx
> +            Sometimes the query process takes some time. You may click the <code>Cancel</code> button to abort the query if it is needed.
"You may click the <code>Cancel</code> button if you wish to abort the query."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/PreferencesHelpContent.tsx
> +            <li>Save last used directory: when this is enabled, the starting directory of a new CARTA session will be the one used to load an image in the previous CARTA session</li>
"the last one used"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/PreferencesHelpContent.tsx
> +            <li>Region size (px): the size of a region in screen pixel when it is created with a click</li>
"pixels"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/PvGeneratorHelpComponent.tsx
> +            When a PV image is being computed, a progress bar will show up to let you know the progress of the PV image generation. The generation process may be canceled by clicking the <code>Cancel
"show up" --> "appear"

"You may abort the generation process by clicking..."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/PvGeneratorHelpComponent.tsx
> +            process is finished, the resulting PV image will be appended automatically. The PV image is stored in memory. If you would like to keep it for further analysis, you can save it on disk (<
"save it to disk"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/RegionDialogHelpContent.tsx
> +            The selected region can be centered in the image viewer by clicking the <code>Focus</code> button at the bottom of the dialog. The region can be locked to prevent accidental modification
"You can center... by clicking..."

"You can lock the region to prevent... by clicking..."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/RegionListHelpContent.tsx
> +            The <code>Lock</code> button for each region entry is to prevent editing a region accidentally. Locked regions will appear slightly dimmer in the image viewer. The <code>Focus</code> butt
"is used to prevent"

"is used to center"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/RegionListHelpContent.tsx
> +            For unmatched images, they can have their own set of regions. If an image is spatially matched to the spatial reference image, a union set of regions is created and registered to the refe
"Unmatched images can have their own sets of regions." (?)

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/RegionListHelpContent.tsx
> +            shared to all spatially matched images. Shared regions are approximated as polygon regions so that on the spatially matched images, we may see region distortion due to projection effect.
"Shared regions are approximated as polygon regions, so on the spatially matched images we may see region distortion as a result of projection."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/RenderConfigHelpContent.tsx
> +            <code>Clip Max</code> fields. These fields can be manually edited and the clip level will be switched to <code>Custom</code>. The clip boundaries are visualized as two vertical lines (dra
"If these fields are edited manually, the clip level..." or "These fields can be edited manually; if they are, the clip level..."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/RenderConfigHelpContent.tsx
> +            green dashed line represents the mean value of the histogram. The green shaded area represents the +/- one RMS.
"represents +/- one RMS"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/RenderConfigHelpContent.tsx
> +            Different scaling functions and colormaps can be chosen via the <code>Scaling</code> and <code>Color map</code> dropdown menus, respectively. A colormap might be inverted via the <code>In
It seems inconsistent to use "color map" in the UI labels, but "colormap" in the docs -- should these all be changed to "color map"?

"may be inverted"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpatialProfilerHelpContent.tsx
> +            The cursor position may be fixed in the image viewer by pressing <code>F</code> key. Pressing again will unfreeze the cursor. For a line region or a polyline region, an averaging width al
"You can fix... by pressing..."

"the F key"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpatialProfilerSettingsComputationHelpContent.tsx
> +            The <code>Width</code> spinbox is used to define the averaging width along a line region or a polyline region when calculating a spatial profile. If the image is considered as <em>flat</e
"when a spatial profile is calculated"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpatialProfilerSettingsComputationHelpContent.tsx
> +            the image is considered as <em>wide</em> with noticeable projection distortion, the width is in unit angular step. This ensures adjacent samples along the region have approximately the sa
I'm not sure about the "considered as" here and in several other places. Maybe just "considered", or "considered to be", or "treated as"?

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpatialProfilerSettingsComputationHelpContent.tsx
> +            the image is considered as <em>wide</em> with noticeable projection distortion, the width is in unit angular step. This ensures adjacent samples along the region have approximately the sa
"ensures that"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralLineQueryHelpContent.tsx
> +            ). The query is made by defining a range in frequency or wavelength (rest frame) and optionally a lower limit of CDMS/JPL line intensity (log value). The spectral range can be defined as
"You can make a query by defining..."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerHelpContent.tsx
> +            When none of the checkboxes is selected, the spectral profiler widget displays one spectrum at a time only. You can view a region spectral profile (via the <code>Region</code> dropdown me
"only one spectrum at a time"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerHelpContent.tsx
> +            <code>Image</code> dropdown menu) with a specific statistic (via the <code>Statistic</code> dropdown menu; default as mean). If the polarization axis exists, you may view a specific polar
"the default is mean"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerHelpContent.tsx
> +        <p>The cursor information of each profile is displayed at the bottom-left corner. The cursor information box is resizable when it is necessary.</p>
"The cursor information box can be resized."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerHelpContent.tsx
> +            The image dropdown menu defaults to &quot;Active&quot; image which means the current image in the image viewer if it is the single-panel mode. If it is the multi-panel mode, the active im
"in single-panel mode"

"in multi-panel mode"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerHelpContent.tsx
> +            polarization angle etc.. The dropdown menu defaults to &quot;Current&quot;, meaning the selected polarization component via the animator.
"angle, etc.."

"the polarization component selected via the animator"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerHelpContent.tsx
> +        <p>and the intensity unit such as &quot;Jy/beam&quot; &lt;-&gt; &quot;K&quot;, depending on the integrity image header.</p>
The integrity of the image header? The contents of the image header? Not sure about this.

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerHelpContent.tsx
> +            The displayed profile can be smoothed via the <code>Smoothing</code> tab of the spectral profiler settings dialog (the <code>cog</code> button). A shortcut button of the <code>Smoothing</
A shortcut button to or for?

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerSettingsConversionHelpContent.tsx
> +        Intensity unit conversion currently works only with a <em>single</em> spectral profile. The support for the multi-profile mode will be implemented in a future release.
"The support" --> "Support"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerSettingsFittingHelpContent.tsx
> +            You may use the GUI to define an initial solution <em>manually</em> by entering the values with the text fields, or by using the mouse to draw a <em>box</em> on the plot. The height, widt
"in the text fields"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerSettingsFittingHelpContent.tsx
> +            solution of a continuum manually by entering the values with the text fields, or by using the mouse to draw a <em>line</em> on the plot (recommended).
"in the text fields"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerSettingsFittingHelpContent.tsx
> +            Once you have set up a good set of initial solutions, you can trigger the fitting process by clicking the <code>Fit</code> button. If you would like to trigger the fitter right after a se
"a set... is found"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerSettingsMomentsHelpContent.tsx
> +                <b>Image</b>: the image file for moment calculations. &quot;Active&quot; refers to the image displayed in the image viewer if it is single panel mode. If it is multi-panel mode, the a
"in single-panel mode"

"in multi-panel mode"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerSettingsMomentsHelpContent.tsx
> +                &quot;Exclude&quot;, the pixel value range defined in the text input fields is included or excluded, respectively. Alternatively, the pixel value range can be defined via the cursor b
"you can define the pixel value range with the cursor by..."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/SpectralProfilerSettingsMomentsHelpContent.tsx
> +            When all the parameters are defined, by clicking the <code>Generate</code> button moment calculations will begin. Depending on the file size, moment calculations may take a while. If that
"click the <code>Generate</code> button to start the moment calculation"

"may wish to cancel"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/StatsHelpContent.tsx
> +            The <code>Image</code> dropdown menu defaults to &quot;Active&quot; image which means the current image in the image viewer if it is single-panel mode. If it is multi-panel mode, the acti
in single-panel / multi-panel mode

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/StatsHelpContent.tsx
> +            The <code>Region</code> dropdown menu defaults to &quot;Active&quot; region which means a selected region in the image viewer. You can select a region by clicking one on the image viewer,
"the region selected in the image viewer"

"clicking on one in the image viewer"

"clicking on a region entry in the region list widget"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/StatsHelpContent.tsx
> +            The <code>Polarization</code> dropdown menu defaults to &quot;Current&quot; which means a selected polarization component in the animator widget.
"the polarization component selected in the animator widget"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/StokesAnalysisHelpContent.tsx
> +            The <code>Image</code> dropdown defaults to &quot;Active&quot; image which means the current image in the image viewer if it is single panel mode. If it is multi-panel mode, the active im
in single-panel / multi-panel mode

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/StokesAnalysisHelpContent.tsx
> +            The <code>Region</code> dropdown defaults to &quot;Active&quot; region which means a selected region in the image viewer. You can select a region by clicking one on the image viewer, or b
"the region selected in the image viewer"

"clicking on one in the image viewer"

"on a region entry in the..."

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/StokesAnalysisHelpContent.tsx
> +            The displayed profiles and the scatter plot can be smoothed via the <code>Smoothing</code> tab of the Stokes analysis settings dialog (the <code>cog</code> button). A shortcut button of t
shortcut button to (multiple places)

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/StokesAnalysisHelpContent.tsx
> +            When region Stokes profiles are requested, depending on the performance of the server, you may see profiles are updated piece by piece in regular intervals. This feature provides a visual
"you may see that profiles..."

"at regular intervals"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/VectorOverlayHelpContent.tsx
> +                    For visualization of linear polarization from a pre-computed position angle image in degree: set the <code>Angular Source</code> to &quot;Current image&quot; and set the <code>Int
"in degrees"?

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/VectorOverlayHelpContent.tsx
> +            Usually block smoothing is applied to the image to enhance signal-to-noise ratio before computing vector elements. You can enable the <code>Pixel Averaging</code> toggle (default enabled)
"enabled by default"

2022-07-25 12:37 UTC, confluence commented on src/components/HelpDrawer/HelpContent/VectorOverlayHelpContent.tsx
> +            similar to the raster rendering with image tiles. Click the <code>Clear</code> button to remove the vector overlay.
"similarly to"

2022-07-26 03:00 UTC, kswang1029 commented
@confluence thank you for scanning through the help contexts. All comments are included in the revision.

2022-07-26 07:11 UTC, confluence approved these changes

2022-08-01 08:03 UTC, YuHsuan-Hwang reviewed
The updates are nice; I just have some minor comments.

2022-08-01 08:03 UTC, YuHsuan-Hwang commented on src/components/HelpDrawer/HelpContent/FileBrowserHelpContent.tsx
> +                <a href="https://casadocs.readthedocs.io/en/stable/notebooks/image_analysis.html?highlight=LEL#Lattice-Expression-Language" target="_blank" rel="noreferrer">
Shall we remove the LEL highlight in the url?

2022-08-01 08:03 UTC, YuHsuan-Hwang commented on src/components/HelpDrawer/HelpContent/ImageFittingHelpContent.tsx
> +        </p>
I would prefer we add a note here describing the definition of major/minor axis of FWHM. (and perhaps also a note in the region dialog help describing the definition of major/minor axis)

2022-08-01 08:03 UTC, YuHsuan-Hwang commented on src/components/HelpDrawer/HelpContent/ImageViewHelpContent.tsx
> +            <li>Line</li>
Lines are also rotatable.

2022-08-01 08:03 UTC, YuHsuan-Hwang commented on src/components/HelpDrawer/HelpContent/ImageViewHelpContent.tsx
>          <h3 id="image-information-and-header">Image information and header</h3>
We can move this to the back because it's not related to the toolbar.

2022-08-01 08:03 UTC, YuHsuan-Hwang commented on src/components/HelpDrawer/HelpContent/RenderConfigHelpContent.tsx
>          <p>The x and y ranges of the histogram plot can be modified by</p>
Are we also changing the items below to `drag-and-drop`?

2022-08-01 09:43 UTC, kswang1029 commented
@YuHsuan-Hwang thanks for the comments. Please refer to [e923fed](https://github.com/CARTAvis/carta-frontend/pull/1924/commits/e923fed19635768d8b2487e06360165ffbb0482a) for the revised context.

2022-08-02 03:59 UTC, YuHsuan-Hwang approved these changes

2022-08-06 12:12 UTC, merged