Icchen/1826 condition of enabling catalog selection button
CARTAvis/carta-frontend pull request #1939
Opened 2022-08-02 10:05 UTC by I-Chenn

**Description**
Fix issue #1826. Now the condition of enabling "Catalog selection" button is:
1. **Catalog overlay is activated**
or
2. **There is at least one source is plotted on the viewer**

Result:
1. When "Catalog overlay" is activated, the "Catalog selection" button is still forbidden to click (note the mouse cursor):
![buttonNotEnabled](https://user-images.githubusercontent.com/106953609/182344207-04fe53ee-603c-4aed-a3e2-e5598287671d.jpg)
(sorry for taking the picture with cellphone camera since print screen may let mouse cursor disappear)

2. When sources are plotted on the viewer, the  "Catalog selection" button is enabled
![buttonEnabledWhenSourceIsPlotted](https://user-images.githubusercontent.com/106953609/182346773-26d00a2f-efb7-44c7-aff5-f97ceff71fe5.jpg)

3. Nevertheless, this modification still doesn't fix the "**the first source in the catalog table is highlighted in red when click elsewhere on the image**" problem (even when the "Catalog selection" button is not enabled yet...):
<img width="577" alt="image" src="https://user-images.githubusercontent.com/106953609/182348729-a71af327-7089-4947-9ae0-8f3332444595.png">

**Checklist**
- [x] changelog updated / ~~no changelog update needed~~
- [ ] e2e test passing / added corresponding fix
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed

2022-08-03 03:10 UTC, kswang1029 commented
ok for a formal PR

2022-08-03 03:22 UTC, kswang1029 approved these changes

2022-08-03 03:37 UTC, YuHsuan-Hwang requested changes

2022-08-03 03:37 UTC, YuHsuan-Hwang commented on src/components/ImageView/Toolbar/ToolbarComponent.tsx
> +        const baseFrame = this.props.frame;
We may need to consider spatially matched frames: `this.props.frame.spatialReference ?? this.props.frame`

2022-08-03 03:37 UTC, YuHsuan-Hwang commented on src/components/ImageView/Toolbar/ToolbarComponent.tsx
> +        let numSourcesArray = [];
Perhaps we don't need to calculate the exact sum of source number. We can apply `Array.prototype.every()` to check if each element is zero.

2022-08-05 05:14 UTC, YuHsuan-Hwang requested changes

2022-08-05 05:14 UTC, YuHsuan-Hwang commented on src/components/ImageView/Toolbar/ToolbarComponent.tsx
> +        appStore.catalogStore.visibleCatalogFiles.get(baseFrame).forEach(fileId => {
can be simplified by using `map` instead of `forEach`

2022-08-05 09:11 UTC, I-Chenn commented
@YuHsuan-Hwang I have modified the source code following your suggestion and squeeze the original source code into one line. Please let me know if you're not satisfied with that.

2022-08-09 01:37 UTC, YuHsuan-Hwang approved these changes

2022-08-09 02:56 UTC, YuHsuan-Hwang commented
> Nevertheless, this modification still doesn't fix the "the first source in the catalog table is highlighted in red when click elsewhere on the image" problem (even when the "Catalog selection" button is not enabled yet...)

Filed a new issue for this problem.

2022-08-19 07:39 UTC, merged