Implemented show/hide region functionality
CARTAvis/carta-frontend pull request #1940
Opened 2022-08-03 00:33 UTC by crocka

**Description**
linked issues and companion PRs (if there are), what is implemented or fixed, how to test it, …

**Checklist**
- [ ] changelog updated / no changelog update needed
- [ ] e2e test passing / added corresponding fix
- [ ] protobuf updated to the latest dev commit / no protobuf update needed

2022-08-03 03:34 UTC, kswang1029 commented
issues and suggestions:
1) when we lock all regions, we cannot unlock all region by clicking again
2) my initial guess for the 10% opacity seems not ideal. need a better one like 20% or 30%.
3) please adopt the same style for the import and export buttons at the bottom-right corner as the ones for the spatial profiler for example. 
4) please set the opacity loop as 100%->20%->0%->100%->...
5) when it is 0% we should disable region selection via mouse clicking
6) I suggest we use unlocked icon as the default when all regions are not locked. (ie sychronize the locked/unlocked state)

2022-08-05 01:05 UTC, kswang1029 commented
the state of the "(un)lock all" is affected by individual lock button.

https://user-images.githubusercontent.com/20819712/182980142-8ea51abf-5c98-41fa-afcb-566f413731f4.mov

2022-08-05 01:13 UTC, kswang1029 commented
I also found a bug (not due to your new changes): when a point region is selected, we see the white box (as control point) around the point. When we lock it, we still see it. Like other regions, we should hide the white box (control point). Would you be able to fix it in this branch too?

2022-08-05 03:07 UTC, crocka commented
> the state of the "(un)lock all" is affected by individual lock button.
> 
>  Screen.Recording.2022-08-05.at.09.04.28.mov

Oh, this is intentional. When all the region are set to locked/unlocked, the lock/unlock all will be automatically set to locked/unlocked state, but I see there is some problem when you unlock all the regions the second time. It is supposed to stay unlocked. I will fix it soon.

2022-08-31 06:52 UTC, kswang1029 commented
@crocka this looks good. feel free to turn this as a formal PR when you think proper. Performance-wise I confirm locking or changing opacity is almost instant for 20000 regions in my test cases.

2022-09-05 06:33 UTC, kswang1029 commented
@crocka this "new" PR appears problematic in the logics of the lock button and the view button.

https://user-images.githubusercontent.com/20819712/188378457-b51dc74a-611f-4675-9ff7-44f2fe778465.mov

2022-09-06 00:53 UTC, kswang1029 commented
@crocka yes, now the button logic appears fine. 👍 

One issue: if all region is locked and we select a region from the region list widget, the control points of that region should not be rendered in the image viewer as users may think the region can be modified via the control points.
![Screen Shot 2022-09-06 at 08 50 57](https://user-images.githubusercontent.com/20819712/188525236-e591feb6-dde8-4975-b184-231c289f4358.png)

2022-09-07 01:21 UTC, kswang1029 approved these changes
no regression is observed via the current e2e tests. Manual tests are looking good. This should improve UX significantly for users working with lots of regions. 👍

2022-09-07 03:45 UTC, YuHsuan-Hwang approved these changes
good work 👍

2022-09-13 06:45 UTC, veggiesaurus requested changes

2022-09-13 06:45 UTC, veggiesaurus commented on src/stores/Frame/RegionSetStore.ts
> +    Transparent = 0.5,
I think it would make sense to call this `SemiTransparent`. Transparent implies fully transparent.

2022-09-13 06:45 UTC, veggiesaurus commented on src/stores/Frame/RegionSetStore.ts
> +        if (this.locked) this.selectRegionByIndex(0);
single-line branches also require braces according to our code style

2022-09-27 08:26 UTC, veggiesaurus requested changes

2022-09-27 08:26 UTC, veggiesaurus commented on src/components/ImageView/RegionView/LineSegmentRegionComponent.tsx
> +            if (this.props.selected && this.props.listening && !region.locked && !AppStore.Instance.activeFrame?.regionSet.locked) {
makes sense to create a variable `const frame = AppStore.Instance.activeFrame` above, if you're going to reuse it a few times in the function

2022-09-27 08:26 UTC, veggiesaurus commented on src/components/ImageView/RegionView/LineSegmentRegionComponent.tsx
> +            if (this.props.selected && this.props.listening && !region.locked && !AppStore.Instance.activeFrame?.regionSet.locked) {
(or `regionSet`

2022-09-27 08:27 UTC, veggiesaurus commented on src/components/ImageView/RegionView/LineSegmentRegionComponent.tsx
> +            if (this.props.selected && this.props.listening && !region.locked && !AppStore.Instance.activeFrame?.regionSet.locked) {
actually, don't worry. Not worth delaying this PR for such a minor thing 😄

2022-09-27 08:27 UTC, veggiesaurus approved these changes

2022-09-27 08:32 UTC, YuHsuan-Hwang commented
@crocka Please merge dev and update changelog, thanks.

2022-09-28 03:39 UTC, merged