initial blueprint4 upgrade
CARTAvis/carta-frontend pull request #1975
Opened 2022-08-15 10:02 UTC by veggiesaurus

**Description**
Closes #1395. It may also close a number of table-related issues. 
Draft PR, requires a fair amount of testing, and will likely break e2e tests. 

**Checklist**
- [ ] changelog updated / ~~no changelog update needed~~
- [ ] e2e test passing / added corresponding fix
- [x] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed

2022-08-15 10:04 UTC, veggiesaurus commented
Assigning this to @kswang1029, as it is primarily a user-facing thing. Most of the upgrades were fairly straightforward. I've removed deprecated code where possible.

2022-08-22 07:14 UTC, YuHsuan-Hwang approved these changes

2022-09-01 06:43 UTC, kswang1029 commented
@veggiesaurus not sure why but I am seeing e2e test failures due to changes of xpath (eg. the file filter text field). I will need more time to investigate this. And you are right about the color theme: the contrast is increased and the color theme appears less warm.

2022-09-01 12:58 UTC, kswang1029 commented
One issue: the initial file browser highlight box is squeezed. 
with this PR
![Screen Shot 2022-09-01 at 20 56 31](https://user-images.githubusercontent.com/20819712/187919116-c260b690-4c4d-4a2e-b54b-b863575a1423.png)
current dev
![Screen Shot 2022-09-01 at 20 56 54](https://user-images.githubusercontent.com/20819712/187919120-cd396efb-b1c6-4d04-a743-ca514c301e58.png)

2022-09-01 13:00 UTC, kswang1029 commented
in the file browser, the sorting function in the the Filename, Type, Size, and Date columns does not work anymore.

2022-09-02 03:29 UTC, kswang1029 commented
@veggiesaurus @YuHsuan-Hwang there are a number of issues due to this library upgrade. I will summarize them in a google doc, just for better readability than posting here as a comment thread.

2022-09-05 03:28 UTC, kswang1029 commented
@veggiesaurus please refer to https://docs.google.com/document/d/1UgbYN7CzW2ziPeYo7bn_vDxHrSgs1ri6QDjXS86ylYk/edit?usp=sharing for a list of issues I observed with this blueprintjsV4 upgrade. Basically there are major issues with 
- spinbox
- html table
- blueprint table 🤦🏻‍♂️

2023-03-29 04:32 UTC, kswang1029 commented
@TienHao most of the issues in https://docs.google.com/document/d/1UgbYN7CzW2ziPeYo7bn_vDxHrSgs1ri6QDjXS86ylYk/edit are addressed. 👍 
there are some new others. Please refer to the above doc.

2023-11-23 07:54 UTC, YuHsuan-Hwang commented
Upgrade to blueprint v5 in the next release (v5-beta).

2024-02-16 04:12 UTC, YuHsuan-Hwang requested changes
The changes look nice. Thanks for all the hard work!

One minor issue: the fitting dialog right-bottom toolbar position needs adjustment.
<img src="https://github.com/CARTAvis/carta-frontend/assets/43841102/df3c404a-9564-45af-9b58-a4454e5e23ef" width="400" />

2024-02-16 04:12 UTC, YuHsuan-Hwang commented on src/App.scss
> +// override menu item style with BlueprintJS v3 style
Remove comments.

2024-02-19 08:44 UTC, TienHao commented on src/App.scss
> +// override menu item style with BlueprintJS v3 style
removed!

2024-02-21 04:28 UTC, YuHsuan-Hwang approved these changes

2024-05-15 05:22 UTC, kswang1029 approved these changes
Well done @TienHao 👍

2024-05-16 07:36 UTC, YuHsuan-Hwang approved these changes
New changes look good.

2024-05-17 06:32 UTC, kswang1029 approved these changes

2024-05-17 06:32 UTC, merged