Icchen/1797 scroll selected region into region list view
CARTAvis/carta-frontend pull request #2008
Opened 2022-09-08 08:51 UTC by I-Chenn

**Description**
This PR is to solve #1797.
A method called "scrollToSelected" is added in RegionListComponent.tsx to let the selected region auto-scroll into the view of region list. The result is shown below:
[Screencast from 09-08-2022 04:40:06 PM.webm](https://user-images.githubusercontent.com/106953609/189078748-7ecfe8e5-1165-4d9e-9fb3-bb1d229ff35f.webm)

**Checklist**
- [x] changelog updated / ~no changelog update needed~
- [ ] e2e test passing / added corresponding fix
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed

2022-09-14 00:39 UTC, kswang1029 approved these changes
this looks fine. no regression is observed from e2e tests.

2022-09-14 03:06 UTC, YuHsuan-Hwang requested changes
Found an issue when there are multiple images, for example: create 10 regions (id 1-10) on the first image and then create 10 regions (id 11-20) on the second image. If we select region id 11 on the second image, we always jump to the end of the list because we only display 10 regions (id 11-20).

2022-09-15 11:39 UTC, I-Chenn commented
@YuHsuan-Hwang 
New modification has been committed. Should have solved the issue when multiple images opened.
A rough test is shown below:
[multipleFrame.webm](https://user-images.githubusercontent.com/106953609/190393641-f5d77d55-49fa-4560-af56-151f1a0cf5b3.webm)
p.s. For some unknown reason, the screen recording didn't record the process when I change to the second image, but the result of the second image is successfully recorded.

2022-09-16 01:53 UTC, YuHsuan-Hwang requested changes
The new calculation looks good. Just some minor comments:

2022-09-16 01:53 UTC, YuHsuan-Hwang commented on src/components/RegionList/RegionListComponent.tsx
> +                    const validRegionId = [];
can be simplified by `Array.map`

2022-09-16 01:53 UTC, YuHsuan-Hwang commented on src/components/RegionList/RegionListComponent.tsx
> +                } else return;
`else return` can be removed

2022-09-16 03:54 UTC, I-Chenn commented on src/components/RegionList/RegionListComponent.tsx
> +                    const validRegionId = [];
The code is simplified in 7c3abcd.

2022-09-16 03:54 UTC, I-Chenn commented on src/components/RegionList/RegionListComponent.tsx
> +                } else return;
Removed in 7c3abcd

2022-09-16 05:50 UTC, YuHsuan-Hwang approved these changes

2022-09-16 06:28 UTC, kswang1029 approved these changes
tested with a few thousands regions on matched and unmatched images. All appear fine. no regression is observed from e2e tests.

2022-09-16 06:50 UTC, merged