OIDC serverside
CARTAvis/carta-frontend pull request #2016
Opened 2022-09-19 17:52 UTC by daikema

**Description**

Supersedes / replaces #1861, with the OIDC login moved to the serverside to eliminate a dependence on public clients which aren't accepted by all identity providers.  Note that the scope of changes required in the frontend has been significantly reduced due to the resulting similarity with the local authentication providers supported by the server such that the changes herein are expected to be minimal.  (The bulk of the changes to support OIDC login can be found in [this pull request in the carta-controller repo](https://github.com/CARTAvis/carta-controller/pull/129))

**Checklist**
- [?] changelog updated / no changelog update needed

Given the short nature of the change here I'm not sure that a changelog update is needed beyond what might be needed for the carta-controller.  (That said, I don't see a corresponding changelog in the carta-controller repo).

- [?] e2e test passing / added corresponding fix

Not sure how to run these tests but I suspect that the changes here are small enough in scope that it's unlikely to trigger new test failures.

- [X] protobuf updated to the latest dev commit / no protobuf update needed

2022-09-27 11:01 UTC, veggiesaurus requested changes

2022-09-27 11:01 UTC, veggiesaurus commented on src/services/ApiService.ts
> +                if (err.response.status == 404) {
replace with `===`

2022-09-27 18:46 UTC, daikema commented on src/services/ApiService.ts
> +                if (err.response.status == 404) {
Done

2022-10-05 08:12 UTC, veggiesaurus approved these changes

2022-10-05 08:12 UTC, merged