adjust PR template
CARTAvis/carta-frontend pull request #2024
Opened 2022-09-30 06:40 UTC by YuHsuan-Hwang

**Description**

I added some items in the PR template checklist that may be useful for final checks before we merge and close issues. Please check if the items are clear and necessary.

**Checklist**
- [X] ~changelog updated / no changelog update needed~
- [X] ~e2e test passing / added corresponding fix~
- [X] ~protobuf updated to the latest dev commit / no protobuf update needed~

2022-09-30 07:26 UTC, acdo2002 requested changes
Could the frontend PR template adds additional checking item? 
- [ ] src/services/BackendService.ts updated / no BackendService.ts update needed

It would be useful for the future carta-ICD-rxjs because it will use BackendService.ts as the base to run the tests.

2022-09-30 08:01 UTC, YuHsuan-Hwang commented
> Could the frontend PR template adds additional checking item?
> 
> * [ ]  src/services/BackendService.ts updated / no BackendService.ts update needed
> 
> It would be useful for the future carta-ICD-rxjs because it will use BackendService.ts as the base to run the tests.

@acdo2002 How about we add:

- [ ] BackendService.ts unchanged / BackendService.ts changed and corresponding ICD test fix added

2022-09-30 08:18 UTC, acdo2002 commented
@YuHsuan-Hwang Excellent, it looks great to me.

2022-09-30 08:47 UTC, acdo2002 approved these changes

2022-09-30 10:50 UTC, veggiesaurus commented
one very minor change, I'd suggest we just use `BackendService` (as in making use of the markdown) instead of BackendService.ts

2022-10-03 03:41 UTC, YuHsuan-Hwang commented
> one very minor change, I'd suggest we just use `BackendService` (as in making use of the markdown) instead of BackendService.ts

@veggiesaurus adjusted:
![image](https://user-images.githubusercontent.com/43841102/193497617-ecb37a65-26c8-42fb-8fa8-f0b5bbfe97ff.png)

2022-10-04 07:48 UTC, kswang1029 approved these changes

2022-10-04 07:48 UTC, kswang1029 commented on .github/pull_request_template.md
> +- [ ] protobuf updated to the latest dev commit / no protobuf update needed
for a feature development, protobuf messages may be updated so that frontend and backend can communicate properly. Would this be better as

- [ ] protobuf updated to the latest dev commit / protobuf updated for new features / no protobuf update needed

?

2022-10-04 07:48 UTC, kswang1029 commented on .github/pull_request_template.md
> +- [ ] protobuf updated to the latest dev commit / no protobuf update needed
never mind. misunderstood

2022-10-05 08:15 UTC, veggiesaurus approved these changes

2022-10-07 09:24 UTC, TienHao approved these changes

2022-10-07 13:53 UTC, crocka approved these changes

2022-10-11 01:39 UTC, I-Chenn approved these changes

2022-10-11 05:02 UTC, merged