Thchang/ issue_1319
CARTAvis/carta-frontend pull request #2032
Opened 2022-10-13 05:33 UTC by TienHao

**Description**
fixed #1319 by adding needed digits after decimal point(depending on cursor info precision and wcs value) in the upper wcs axis in spatial profilers.

**Checklist**
For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [x] changelog updated
- [x] no protobuf update needed
- [x] `BackendService` unchanged

2022-10-17 07:47 UTC, kswang1029 reviewed
Overall this works nicely. 👍 No regression is observed from e2e tests. 

Few minor issues to consider but not all of them need to be addressed:
1. [required] when the 2nd tick values are in channel, please use plain value format (ie remove ,)
![Screen Shot 2022-10-17 at 15 14 07](https://user-images.githubusercontent.com/20819712/196118066-e372da04-b14b-4256-86e9-66434da5d72e.png)

2. [best effort] in some cases, the tick values are too crowded. If possible, in this case we need to skip some.
![Screen Shot 2022-10-17 at 15 30 42](https://user-images.githubusercontent.com/20819712/196118528-da85a41f-a26e-443e-8547-1dff518a6696.png)

3. [can ignore] at extreme zoom levels, we start to see tick values are repeating.
![Screen Shot 2022-10-17 at 15 39 51](https://user-images.githubusercontent.com/20819712/196118801-05a9503d-7e44-4b72-a15c-26d41ff38b17.png)

Code review may start.

2022-10-20 03:04 UTC, YuHsuan-Hwang approved these changes

2022-10-26 11:16 UTC, TienHao commented
> 1. [required] when the 2nd tick values are in channel, please use plain value format (ie remove ,). Note this exists in dev so it is not due to this PR.
> 2. [best effort] in some cases, the tick values are too crowded. If possible, in this case we need to skip some.
> 3. [can ignore] at extreme zoom levels, we start to see tick values are repeating.

@kswang1029 : 
I have fixed the minor issues 1 & 2 first and kept the third one remained.

2022-10-28 03:03 UTC, kswang1029 requested changes
@TienHao thanks for addressing the value format and value overlapping issues. 👍 
Some e2e tests failed due to the top axis. Please hide the top axis for the spatial profiler widget if the region type is line or polyline. Please also hide the top axis for the spectral profiler.
![Screen Shot 2022-10-28 at 11 00 45](https://user-images.githubusercontent.com/20819712/198487663-b3b55223-75aa-4f70-b028-80634d390b99.png)
![Screen Shot 2022-10-28 at 11 00 31](https://user-images.githubusercontent.com/20819712/198487962-8647bff5-198a-4679-ad79-5ce1f2b6dc55.png)

2022-12-01 03:35 UTC, kswang1029 approved these changes
this works well now. no regression is observed from e2e tests. 👍

2022-12-01 08:16 UTC, YuHsuan-Hwang approved these changes

2022-12-01 22:13 UTC, crocka commented on src/components/SpatialProfiler/SpatialProfilerComponent.tsx
> +                    const wcsLabel = this.pointInfo?.infoWCS && !this.lineAxis ? `WCS: ${isXCoordinate ? this.pointInfo.infoWCS.x : this.pointInfo.infoWCS.y}, ` : "";
Can we replace isXCoordinate with this.widgetStore.isXProfile?

2022-12-01 22:18 UTC, crocka approved these changes

2022-12-05 11:28 UTC, veggiesaurus approved these changes

2023-01-03 02:03 UTC, merged