Carli/2054 support keeping moment image
CARTAvis/carta-frontend pull request #2059
Opened 2022-11-26 03:02 UTC by crocka

**Description**

Resolves #2054. Added option to keep previously generated moment images.

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [ ] changelog updated / no changelog update needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

2022-11-28 03:49 UTC, kswang1029 commented
@pford @crocka The keep function for moment images appears fine. I noticed that the keep function for pv images seems broken. Could you have a look?

2022-11-28 04:49 UTC, kswang1029 commented
with the new toggle for keep, we need a taller default dialog height so the generate button is visual and there will be no scroll bar present.

2022-11-29 05:11 UTC, kswang1029 commented
ready for a PR. 

tested manually and automatically with e2e tests. All looking good, except UI changes which break moment generator tests. A branch has been created to address the changes.

2022-12-01 03:19 UTC, YuHsuan-Hwang requested changes
The changes look good. How about we also fix #2061 in this PR? Shall be a one-line change.

2022-12-01 03:19 UTC, YuHsuan-Hwang commented on src/components/SpectralProfiler/MomentGeneratorComponent/MomentGeneratorComponent.tsx
> +                            this.props.widgetStore.setKeep(e.checked);
`this.props.widgetStore` can be simplified to `widgetStore`

2022-12-02 03:13 UTC, YuHsuan-Hwang approved these changes

2022-12-02 03:15 UTC, YuHsuan-Hwang commented
I think we will need to update the change log for issue 2054.

2022-12-02 04:17 UTC, YuHsuan-Hwang approved these changes

2022-12-02 06:51 UTC, kswang1029 approved these changes
all looking good. no regression is seen from e2e tests. A fix to moment generator test is applied due to UI changes.

2022-12-02 06:56 UTC, kswang1029 commented
also confirmed that #2061 is fixed in this PR. 👍

2022-12-03 02:30 UTC, merged