Icchen/1930 persistent connectivity popup
CARTAvis/carta-frontend pull request #2070
Opened 2022-12-21 10:46 UTC by I-Chenn

**Description**
This draft-PR is to resolve #1930. The modification includes:
1. Change the `connectivityTooltip` from `Tooltip2` to `Popover2` to make it persistent.
2. Add a button to copy the session ID to clipboard for later use.

The result is shown below:
https://user-images.githubusercontent.com/106953609/208884219-5bb6ce50-c7a7-4be1-a153-338ebd7cc545.mov

World like to discuss with @kswang1029  and @YuHsuan-Hwang:
Is it OK to change the `connectivityTooltip` from `Tooltip2` to `Popover2`?

And would like to ask @confluence:
Is this is the effect you want?

**Checklist**

For linked issues (if there are):
- [X] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [X] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [ ] changelog updated / no changelog update needed
- [X] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [X] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

2022-12-21 23:51 UTC, kswang1029 commented
@I-Chenn this look good. Just few suggestions:
1) we need to beautify it with css
2) we also need another button as Copy session URL (handy for the python scripting interface setup)
3) after clicking the copy button, we can use "toast" (please refer to blueprintjs) to show a confirmation such as "Session ID copied to clipboard".

2022-12-22 03:54 UTC, YuHsuan-Hwang commented
> Is it OK to change the connectivityTooltip from Tooltip2 to Popover2?

`isOpen` prop in `Tooltip2` could be another solution, but I'm ok with both `Tooltip2` and `Popover2`

2022-12-22 04:22 UTC, kswang1029 commented
> > Is it OK to change the connectivityTooltip from Tooltip2 to Popover2?
> 
> `isOpen` prop in `Tooltip2` could be another solution, but I'm ok with both `Tooltip2` and `Popover2`

It would be “better” to have less clicks. So if the small box can be launched by just hovering and can be closed by clicking elsewhere (except those copy buttons) it feels better in my point of view.

2022-12-22 04:45 UTC, I-Chenn commented
OK, I will:
1. Try `isOpen` prop of `ToolTip2` and see if I can maintain the original `Tooltip2` version.
2. Beautify the button & add a feedback like "Session ID copied!" to it.
3. Another button for session URL.
in my next commit.

Nevertheless, as for the "Session URL button", is that related to Adriana's reply in #1930? I did some search for "Session URL" in the front-end code, but still have no idea what that is. May I have some indication of what "Session URL" is?

2022-12-22 05:58 UTC, kswang1029 commented
> OK, I will:
> 
> 1. Try `isOpen` prop of `ToolTip2` and see if I can maintain the original `Tooltip2` (hover, not click) version.
> 2. Beautify the button & add a feedback like "Session ID copied!" to it.
> 3. Another button for session URL.
> 
> in my next commit.
> 
> Nevertheless, as for the "Session URL button", is that related to Adriana's reply in #1930? I did some search for "Session URL" in the front-end code, but still have no idea what that is. May I have some indication of what "Session URL" is?

It is the browser url which we used to launch the gui

2023-01-04 15:40 UTC, I-Chenn commented
@kswang1029 @YuHsuan-Hwang

I still find it hard to get a method of "maintaining" Tooltip2 until we can click on the button within it. The major problem is that I am not able to set up a proper scenario (until the next click?) to set `isOpen` prop to false. Please enlighten me if you have any good idea.

An alternative way is adopted temporarily in 219ae51, that is to set `hoverCloseDelay` prop to 3 seconds, which I think should be long enough for user to click on the button. It's not perfect, but it resolve the problem to some extent.

By the way, I still don't quite understand what Session URL is. It's definitely not `http://localhost:3000/` and probably not:
<img width="968" alt="截圖 2023-01-04 下午11 35 10" src="https://user-images.githubusercontent.com/106953609/210591407-7de796c0-32d5-4856-b5c6-a137d5a1661d.png">
Can you show me how to get Session URL?

2023-01-05 02:05 UTC, YuHsuan-Hwang commented
> @kswang1029 @YuHsuan-Hwang
> 
> I still find it hard to get a method of "maintaining" Tooltip2 until we can click on the button within it. The major problem is that I am not able to set up a proper scenario (until the next click?) to set `isOpen` prop to false. Please enlighten me if you have any good idea.
> 
> An alternative way is adopted temporarily in [219ae51](https://github.com/CARTAvis/carta-frontend/commit/219ae5109fb1b1422bf368d41f39b52c406fa4d2), that is to set `hoverCloseDelay` prop to **3 seconds**, which I think should be long enough for user to click on the button. I know it's not perfect, but it resolve the problem to some extent.
> 
> To be honest, I personally don't think it's a good idea to add an interactive element within tooltip, since tooltip is supposed to display additional information. A popup is instead more reasonable to put in interactive elements by comparison.

I see, `Tooltip2` does not support clicks well. We can use `Popover2` instead.
`hoverCloseDelay` design also looks good to me because users don't need any extra clicks in this way, but I don't have a strong preference.

2023-01-05 02:27 UTC, kswang1029 commented
we should use https://blueprintjs.com/docs/#core/components/toast to notify a user that a session id is copied.

2023-01-09 02:51 UTC, kswang1029 commented
@I-Chenn @YuHsuan-Hwang I have one simple idea on adding the copy session id/URL. We can simply add two more options as "Copy session ID" and "Copy session URL" to the server sub-menu.
![Screen Shot 2023-01-09 at 10 48 40](https://user-images.githubusercontent.com/20819712/211233850-965eb166-67f1-4537-aea6-ed96a7a91010.png)

That "restart service" option should be displayed only when CARTA is deployed with the CARTA controller.

2023-01-09 04:27 UTC, I-Chenn commented
@kswang1029 
OK, roger that.

Nevertheless, I would like to know how to reveal that "Service" sub-menu? I tried to look for the source code:
![image](https://user-images.githubusercontent.com/106953609/211239926-ba9a0e6b-24d1-4dc1-9bb2-1fbaf3e5ca52.png)
![image](https://user-images.githubusercontent.com/106953609/211240007-2152d916-3322-46dd-b1b9-8a73d19cdda1.png)
![image](https://user-images.githubusercontent.com/106953609/211240082-8a97824b-c4f3-4fb2-ae3d-990ac39d3f8e.png)
and it seems that I need to be "authenticated" and with an "access token"? I would like to know how to get the "access token" and be "authenticated"? Does that relate to "Carta Controller" you mentioned? 

> That "restart service" option should be displayed only when CARTA is deployed with the CARTA controller.

2023-01-09 04:51 UTC, kswang1029 commented
> @kswang1029 OK, roger that.
> 
> Nevertheless, I would like to know how to reveal that "Service" sub-menu? I did some survey through the source code: ![image](https://user-images.githubusercontent.com/106953609/211239926-ba9a0e6b-24d1-4dc1-9bb2-1fbaf3e5ca52.png) ![image](https://user-images.githubusercontent.com/106953609/211240007-2152d916-3322-46dd-b1b9-8a73d19cdda1.png) ![image](https://user-images.githubusercontent.com/106953609/211240082-8a97824b-c4f3-4fb2-ae3d-990ac39d3f8e.png) and it seems that I need to be "authenticated" and with an "access token"? I would like to know how to get the "access token" and be "authenticated"? Does that relate to "Carta Controller" you mentioned?

No, even without the CARTA controller, when we start a carta_backend process, be default it will generate a token as part of the URL for users to connect to.

2023-01-09 06:16 UTC, veggiesaurus commented
> @I-Chenn @YuHsuan-Hwang I have one simple idea on adding the copy session id/URL feature. We can simply add two more options as "Copy session ID" and "Copy session URL" to the server sub-menu.

How do we adapt this to the electron app? Hide the session URL entry?

2023-01-09 06:19 UTC, kswang1029 commented
> > @I-Chenn @YuHsuan-Hwang I have one simple idea on adding the copy session id/URL feature. We can simply add two more options as "Copy session ID" and "Copy session URL" to the server sub-menu.
> 
> How do we adapt this to the electron app? Hide the session URL entry?

Can we keep it? Then users can still use it if they want to have a new session in a browser or use the URL in a python script to control the GUI programmatically?

2023-01-09 10:43 UTC, I-Chenn commented
Blueprintjs' toaster is not yet applied to the commit of 9cb4069. Will do it tomorrow.

2023-01-10 04:54 UTC, I-Chenn commented
@kswang1029 @YuHsuan-Hwang 
An "InfoToast" function is added to toast.ts and is then used to present "XXX is copied!" information after clicking the menus mentioned above. The result is shown below:
[Screencast from 01-10-2023 12:19:29 PM.webm](https://user-images.githubusercontent.com/106953609/211463090-198577f1-4da1-4746-ad32-e70a6e8a2eb1.webm)

Another concern is that: most of the content in the **Server** sub-menu don't usually show up. They need some condition to show up. Take "**Restart Service**" for example, it needs authentication to show up (and that's why that when I tried to run CARTA with `--debug_no_auth` flag when developing, the whole **Server** sub-menu doesn't show up at all). I haven't set any condition for the two new sub sub-menus in 07035f4, do I need to add any condition for them to show up?

2023-01-10 05:02 UTC, kswang1029 commented
> @kswang1029 @YuHsuan-Hwang An "InfoToast" function is added to toast.ts and is then used to present "XXX is copied!" information after clicking the menus mentioned above. The result is shown below: [Screencast from 01-10-2023 12:19:29 PM.webm](https://user-images.githubusercontent.com/106953609/211463090-198577f1-4da1-4746-ad32-e70a6e8a2eb1.webm)
> 
> Another concern is that: most of the content in the **Server** sub-menu don't usually show up. They need some condition to show up. Take "**Restart Service**" for example, it needs authentication to show up (and that's why that when I tried to run CARTA with `--debug_no_auth` flag when developing, the whole **Server** sub-menu doesn't show up at all). I haven't set any condition for the two new sub sub-menus in [07035f4](https://github.com/CARTAvis/carta-frontend/commit/07035f4deafc906454174689fb92059ade0069ff), do I need to add any condition for them to show up?

Regarding the "Server" menu and it context, we need to refine the current logic. 
1. We should always show the Server menu from now.
2. We always show the two copy functions
3. For "Restart Service", "Dashboard", and "Logout", we only need to show them when a carta controller is used for deployment.
![Screen Shot 2023-01-10 at 13 01 19](https://user-images.githubusercontent.com/20819712/211466025-e128f26d-1fcb-4fd2-8055-df69c55c697c.png)

2023-01-11 10:02 UTC, I-Chenn commented
@kswang1029 @YuHsuan-Hwang 
Sorry for making a further commit again.
Though we decided to open a new issue for the "appearance of the **Restart Service**" issue during our discussion yesterday, I asked @veggiesaurus about this issue and it seems that we only need a minor modification to fix it, I thus made the fix in this PR and the result is shown below (Note: in the image, CARTA is run with production build to be authenticated):
![image](https://user-images.githubusercontent.com/106953609/211775547-44184807-86ad-4aaa-8b9e-6067efef9046.png)
The modification does fix the issue.

2023-01-11 10:03 UTC, kswang1029 commented
@ajm-asiaa is there a way to test this with the carta controller?

2023-01-11 10:38 UTC, ajm-asiaa commented
@kswang1029 I have put the 321ad049 frontend commit on our cartaviewer server, used the `"frontendPath"` configuration option in `/etc/carta/config.json` to point towards it, and restarted the carta-controller service. You can try it out on https://cartaviewer.asiaa.sinica.edu.tw/ (only if inside the IAA network).

The menu options show up correctly:
![Screenshot 2023-01-11 at 6 29 53 PM](https://user-images.githubusercontent.com/20802551/211783297-3eada775-6d93-4ade-9105-8fe8782a08a1.png)

I notice there is no token in the copied URL, so I guess for the carta-controller version only the first part of the URL and session ID are needed for carta-python to connect to it?

2023-01-11 10:41 UTC, kswang1029 commented
> @kswang1029 I have put the [321ad04](https://github.com/CARTAvis/carta-frontend/commit/321ad049336d4bfcccf3f1b821aaa6fb4834e2c9) frontend commit on our cartaviewer server, used the `"frontendPath"` configuration option in `/etc/carta/config.json` to point towards it, and restarted the carta-controller service. You can try it out on https://cartaviewer.asiaa.sinica.edu.tw/ (only if inside the IAA network).
> 
> The menu options show up correctly: ![Screenshot 2023-01-11 at 6 29 53 PM](https://user-images.githubusercontent.com/20802551/211783297-3eada775-6d93-4ade-9105-8fe8782a08a1.png)
> 
> I notice there is no token in the copied URL, so I guess for the carta-controller version only the first part of the URL and session ID are needed for carta-python to connect to it?

@ajm-asiaa thanks. This looks great (@I-Chenn). As for using carta-python via the controller, I do not have answer for now. @confluence @veggiesaurus help...

2023-01-11 11:32 UTC, confluence commented
@ajm-asiaa yes, there's no token in the URL if you use Python scripting with the controller. The token is only used when you connect directly to a backend.

2023-01-11 13:38 UTC, confluence approved these changes
I have tested this with a local backend, and it looks like it's doing the correct thing.

2023-01-12 01:51 UTC, kswang1029 requested changes
It appears that if we just launch CARTA and try to copy session ID/URL, there is no toast info showing up. 

https://user-images.githubusercontent.com/20819712/211956880-bbe4bfeb-8ca1-4895-8620-8d3e636f4cca.mov

2023-01-12 02:49 UTC, I-Chenn commented
@kswang1029: 
That's weird, since I am able to show the toast right after launch Carta on my desktop (Ubuntu 22.04):
[Screencast from 01-12-2023 10:44:26 AM.webm](https://user-images.githubusercontent.com/106953609/211963956-0f10ab53-6546-4881-8c3e-6bb6fd8b0e8e.webm)
I will try it on my MacBook later.

2023-01-12 03:05 UTC, YuHsuan-Hwang requested changes

2023-01-12 03:05 UTC, YuHsuan-Hwang commented on src/components/Menu/RootMenuComponent.tsx
> +                    navigator.clipboard.writeText(window.location.href).then(() => {
We can use `async/await` syntax, as in `PreferenceDialogComponent.handleUserIdCopied`

2023-01-12 03:05 UTC, YuHsuan-Hwang commented on src/components/Menu/RootMenuComponent.tsx
> +                        AppToaster.show(InfoToast("Session URL copied!"));
How about we just reuse `SuccessToast("clipboard", ...`?

2023-01-12 03:42 UTC, I-Chenn commented on src/components/Menu/RootMenuComponent.tsx
> +                        AppToaster.show(InfoToast("Session URL copied!"));
@YuHsuan-Hwang 
![image](https://user-images.githubusercontent.com/106953609/211969258-3106b066-afd7-4be8-b0b6-e62fec19f105.png)
OK, I did mean to use `SuccessToast` at first, but I didn't see the similar clipboard example in `PreferenceDialogComponent.handleUserIdCopied` thus I don't know what icon should I apply for the situation. I will take your comment.
By the way, is `async/await` syntax method used to solve @kswang1029's issue mentioned in:
https://github.com/CARTAvis/carta-frontend/pull/2070#pullrequestreview-1244855995
? I still can't reproduce Kuo-Song's situation yet......

2023-01-12 04:03 UTC, YuHsuan-Hwang commented on src/components/Menu/RootMenuComponent.tsx
> +                        AppToaster.show(InfoToast("Session URL copied!"));
>By the way, is async/await syntax method used to solve @kswang1029's issue mentioned in:
https://github.com/CARTAvis/carta-frontend/pull/2070#pullrequestreview-1244855995
? I still can't reproduce Kuo-Song's situation yet......

No, I think they're not related

2023-01-12 05:47 UTC, kswang1029 commented
if we "click" the Server menu first, there is a chance that the toast will not be displayed. This might be something else in general so please do not spend time on this now.

2023-01-12 05:48 UTC, kswang1029 commented
Uh, in fact, if we don't see the toast, copy is not successful.

2023-01-12 05:50 UTC, kswang1029 commented
> Uh, in fact, if we don't see the toast, copy is not successful.

This weird issue happens to other menus. So please ignore it for now.

2023-01-12 07:23 UTC, I-Chenn commented
@YuHsuan-Hwang 
`SuccessToast` and `async/await ` syntax is adopted in 13c76fb.
The `InfoToaster` is thus removed from `toaster.ts` in the same commit.

2023-01-13 05:43 UTC, YuHsuan-Hwang approved these changes
The new changes look good.

2023-01-30 04:23 UTC, kswang1029 approved these changes
this looks good. 👍 no regression is seen from e2e tests.

2023-01-31 08:36 UTC, merged