Angus/1272 save state
CARTAvis/carta-frontend pull request #2084
Opened 2023-01-11 14:33 UTC by veggiesaurus

**Description**
Unfinished work on save/load workspace feature. Just to start the conversation for now...

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [ ] changelog updated / no changelog update needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

2023-01-24 14:15 UTC, veggiesaurus commented on package.json
> +            "object-curly-spacing": "off",
@YuHsuan-Hwang this solves the problem of eslint reformatting things when it rearranges imports

2023-01-24 14:16 UTC, veggiesaurus commented on src/test/required_tiles.test.ts
> -const TallTile: Point2D = {x: 512, y: 1024};
lint fix

2023-01-24 14:16 UTC, veggiesaurus commented on src/registerServiceWorker.ts
> +                    console.log("This web app is being served cache-first by a service worker. To learn more, visit https://goo.gl/SC7cgQ");
lint fix

2023-01-25 15:33 UTC, veggiesaurus commented
Regions and render configs now working, albeit limited capability:

https://user-images.githubusercontent.com/592504/214605619-a77aee07-93da-4e7f-a19c-4946522a0d40.mp4

2023-03-03 08:32 UTC, YuHsuan-Hwang requested changes
Some initial comments:
1. The dialog is too large and can not be resized

2. When there are no workspace, two non ideal states are overlapped
<img width="400" alt="image" src="https://user-images.githubusercontent.com/43841102/222655946-c917d852-8016-47cc-a05c-81bcaa232837.png">

3. I think it would be convenient to be able to delete workspace. Currently we have `clearWorkspace` but not used by components.

4. I'm not sure if "close workspace" is useful if it's the same as "close all images".

5. The screenshot is small with devicePixelRatio = 2
<img width="400" alt="image" src="https://user-images.githubusercontent.com/43841102/222663789-de9a602f-dd14-4b3f-a20e-05776af76ebf.png">

2023-03-03 08:32 UTC, YuHsuan-Hwang commented on src/components/App/UIControllerComponent.tsx
> +import {WorkspaceDialogComponent} from "../Dialogs/WorkspaceDialog/WorkspaceDialogComponent";
can be combined with "components/Dialogs"

2023-03-03 08:32 UTC, YuHsuan-Hwang commented on src/components/Dialogs/WorkspaceDialog/WorkspaceInfoComponent.tsx
> +                    fetchFileInfo(res);
Do we need `await` here?

2023-03-03 08:32 UTC, YuHsuan-Hwang commented on src/stores/HelpStore/HelpStore.ts
> +    SAVE_WORKSPACE = "Save Layout",
typo: "Save Workspace"

2023-03-10 19:22 UTC, Jordatious commented
This is cool! I've also found the same issues mentioned above. 

When I try to save a workspace under the same name, it apparently saves, but duplicates the same name on a separate line in the workspace list, but is never accessible over the 1st occurrence. Obviously some features are missing, like mentioned above. Furthermore, locked regions become unlocked, and the frozen cursor position is lost.

2023-04-10 14:20 UTC, veggiesaurus commented
@YuHsuan-Hwang 

> Some initial comments:
> 
> 1. The dialog is too large and can not be resized
> 2. When there are no workspace, two non ideal states are overlapped

fixed

 
> 3. I think it would be convenient to be able to delete workspace. Currently we have `clearWorkspace` but not used by components.

I agree. I've added it as an action button next to open/save. Does this look ok? 
![image](https://user-images.githubusercontent.com/592504/230918537-dfe78ff7-92df-44d8-989c-dd1fa55e2107.png)
![image](https://user-images.githubusercontent.com/592504/230918598-46adb8ec-b53b-40a7-b6cc-42ec53755229.png)


> 4. I'm not sure if "close workspace" is useful if it's the same as "close all images".

We can remove that. @kswang1029 @Jordatious what do you think?

> 5. The screenshot is small with devicePixelRatio = 2

fixed

> 
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/43841102/222663789-de9a602f-dd14-4b3f-a20e-05776af76ebf.png">


@Jordatious 

> When I try to save a workspace under the same name, it apparently saves, but duplicates the same name on a separate line in the workspace list, but is never accessible over the 1st occurrence.

I have a fairly good idea why this happens on the controller side. Shouldn't happen in the normal build though :innocent: 

> Furthermore, locked regions become unlocked, and the frozen cursor position is lost.

Locked regions added. I'm not entirely sure how to solve the frozen cursor position :thinking:  this might have to be a known issue for beta1

2023-04-10 14:21 UTC, veggiesaurus commented
@kswang1029 please re-test, I have addressed the comments above

2023-04-11 06:04 UTC, kswang1029 commented
@veggiesaurus overall this looks good!

- if we delete a workspace, the screenshot and its description at the right panel of the workspace dialog remain. This should become the state when no workspace file is selected.

- in the workspace dialog, we do not need the "close" button. We can just use the X button at the top-right corner of the dialog. This would also prevent confusion about what "close" means.

- File menu issues:
We better group the context as

```
-------------------
Open Image
Append Image
Save Image
Close Image
-------------------
Import Regions
Export Regions
Import Catalog
Export Image      >
-------------------
Open Workspace
Save Workspace
-------------------
Preferences
Server            >
-------------------
```

The "Close Workspace" option is not needed I think.

- Widgets menu issues
We are adopting title-cased style in the menu. Eg "Statistics Widget"

- If we load a workspace with images matched spatially and spectrally then if we load a workspace with images matched only spatially (single channel images), there will be a set of warning toasts (orange color) showing up saying for example

"Could not enable spectral matching (velocity system) of cosmos_spitzer24micron.fits to reference image member.uid___A001_X1284_X6c1._G31.41p0.31__sci.spw25.cube.I.pbcor_subimage.fits. No valid transform was found"

- do you think we can use the blueprintjs icon "control" or "applications" as the icon at the top-left corner of the workspace dialog? 

- it may be good to add some text info in the dialog if the selected workspace file has invalid images.

- it appears that the image viewer grid layout is not part of the workspace file. If we have a 3x3 grid with 9 images loaded as a workspace, when it is loaded back with a grid config as 2x2, the 9 images are loaded in 2x2 layout.

2023-04-11 07:45 UTC, YuHsuan-Hwang commented
@veggiesaurus The new changes are nice. Some other comments:

* Looks like the "Last modified" time changes randomly when I reopen the dialog

* I suggest we set the order of action buttons to be `Delete` `Open/Save`

* I would prefer the input column without the left and right margin
  <img src="https://user-images.githubusercontent.com/43841102/231089026-b9e69bcf-2692-4e2a-b953-487220eecfbe.png" width="400" />

* (good to have) It would be convenient if we can scroll the workspace info panel in x direction

2023-04-11 14:56 UTC, Jordatious commented
I'm happy to test this once those changes are made. Is this / will this be deployed to the IDIA carta-testing server?

2023-04-17 13:40 UTC, veggiesaurus commented
> 

I'll deploy it once things are merged into dev :+1:

2023-04-29 20:07 UTC, veggiesaurus commented
@YuHsuan-Hwang @kswang1029 can you re-reivew please?

I've fixed the above issues, apart from:
- input group CSS (I can fix in a separate branch if needed, or do a quick update to this branch on Monday)
- Workspace info panel scroll and invalid information text (I think we need to think about how to communicate this to the user and how to still allow them to load files that _are_ valid).
- Image view layout (e.g. grid) needs more thought and discussion

I think the above can easily be fixed for 4.0 stable, as well as expanded support for workspaces.

2023-05-01 06:19 UTC, kswang1029 commented
@veggiesaurus I spotted a regression (not in dev) with e2e tests. 
To reproduce:
1. load an image
2. enable region list widget in the view
3. load a region file with multiple regions (eg 4 regions), we will see in the region list widget there are four regions with default names as Region 1, Region 2, etc.
4. click the image view and we will see those region names are updated to Region 5, Region 6, etc. In the console, we also see logs about updating region id. 


https://user-images.githubusercontent.com/20819712/235415884-98ce4220-10f4-4806-af20-63830e2b6113.mov

2023-05-01 07:05 UTC, kswang1029 commented
FYI. This branch introduced an xpath index shift. I have created a fix branch for e2e tests. Once the region id regression is fixed, I will try to ensure e2e tests work as usual. This is required for v4-beta package e2e testing.

2023-05-01 17:29 UTC, veggiesaurus commented
> @veggiesaurus I spotted a regression (not in dev) with e2e tests. To reproduce:
> 
> 1. load an image
> 2. enable region list widget in the view
> 3. load a region file with multiple regions (eg 4 regions), we will see in the region list widget there are four regions with default names as Region 1, Region 2, etc.
> 4. click the image view and we will see those region names are updated to Region 5, Region 6, etc. In the console, we also see logs about updating region id.

@kswang1029 fixed :innocent:

2023-05-02 01:26 UTC, kswang1029 commented
@veggiesaurus some issues:
1. if we want to save a workspace with a name colliding with existing workspaces, the existing one will be overwritten without any warning or confirmation. 
2. if the filename is short, the screenshot is displayed nicely. But if the filename is long, the screenshot seems to align with the width of the long filename, leading to a partial display of the screenshot. We need to manually enlarge the window for a better view (and UX). Wonder if it is possible to decouple the alignment (screenshot and text) here?
![Screen Shot 2023-05-02 at 09 09 43](https://user-images.githubusercontent.com/20819712/235558558-b4e655aa-46e8-4be0-87c2-6b54ae58bca9.png)
![Screen Shot 2023-05-02 at 09 10 05](https://user-images.githubusercontent.com/20819712/235558574-d38b20cc-dbdb-455e-9111-bd9b65810ef2.png)
3. In the above screenshot, we see the filename input field is not aligned with the upper two panels (it is narrower)
4. to be consistent, the delete button should be in red with a trash can icon (cf the region dialog).
![Screen Shot 2023-05-02 at 09 16 04](https://user-images.githubusercontent.com/20819712/235558960-cf6d98e0-ec00-4a8d-b17e-b70290e2fcfd.png)
5. It is possible to save a workspace with "whitespace" as a name. However, if we try to open it, when we select it in the workspace file browser, the frontend will crash.
![Screen Shot 2023-05-02 at 09 19 09](https://user-images.githubusercontent.com/20819712/235559282-682d3481-dbdf-4655-88a6-cb15eb586ced.png)
6. please disable spelling check in the filename input field.

2023-05-02 05:59 UTC, YuHsuan-Hwang requested changes
Just one change request. I think most of the remaining issues are related to CSS or design.

2023-05-02 05:59 UTC, YuHsuan-Hwang commented on src/stores/AppStore/AppStore.ts
> +            if (frame.frameInfo.fileId < 0) {
This needs to be consistent with `inMemoryImages` in `resumeSession`.

2023-05-02 11:03 UTC, veggiesaurus commented
@YuHsuan-Hwang fixed

@kswang1029 fixed the following:
- whitespace characters in name (requires latest commit of workspaces backend)
- delete button intent and icon
- spellcheck disabled

The rest are CSS and minor, and can be done for stable

2023-05-02 12:15 UTC, kswang1029 approved these changes

2023-05-03 02:29 UTC, YuHsuan-Hwang approved these changes

2023-05-03 02:35 UTC, YuHsuan-Hwang commented
This PR is ready for merge once the changelog is updated.

2023-05-03 13:24 UTC, YuHsuan-Hwang approved these changes

2023-05-03 14:32 UTC, merged