Carli/1561_support_pv_preview
CARTAvis/carta-frontend pull request #2100
Opened 2023-02-14 20:28 UTC by crocka

**Description**

linked issues and companion PRs (if there are), what is implemented or fixed, how to test it, …

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [ ] changelog updated / no changelog update needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

2023-04-20 10:28 UTC, YuHsuan-Hwang requested changes
Most of the implementation is good 👍 Here are my initial comments:

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/stores/PreferenceStore/PreferenceStore.ts
> +                PreferenceKeys.PERFORMANCE_PV_PREVIEW_CUBE_SIZE_LIMIT_UNIT
We don't need to change `upgradePreferences` because it's for old keys.

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx
> +                <FormGroup inline={true} label="PV Preview Cube Size Limit">
The label and placeholder need to be in sentence case.

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx
> +                            onValueChange={value => PreferenceStore.Instance.setPreference(PreferenceKeys.PERFORMANCE_PV_PREVIEW_CUBE_SIZE_LIMIT, value)}
can be simplified to `preference.setPreference`.

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx
> +    @observable pvPreviewCubeSizeLimitUnit: string;
This needs to be initialized otherwise `pvPreviewCubeSizeMaxValue` will be `PV_PREVIEW_CUBE_SIZE_LIMIT` before `handlePvPreviewCubeSizeUnitChange` is triggered.
How about we directly use`preferenceStore.pvPreivewCubeSizeLimitUnit`?

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/stores/PreferenceStore/PreferenceStore.ts
> +        pvPreviewCubeSizeLimitUnit: "GB"
Perhaps we could create a enum `MemoryUnit` to specify the type.

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/stores/OverlayStore/OverlayStore.ts
> +    @action height(frame?: FrameStore): number {
Looks like the colorbar tick positions are not responsive to the height, both in the main viewer and the preview viewer:
![image](https://user-images.githubusercontent.com/43841102/233290225-789dbb41-a795-4429-a46b-f3b2c7259407.png)
Maybe we need to change `height` to a `@computed` variable returning a function (`(frame?: FrameStore) => number`) so that `colorbarStore.positions` responses with `height`.
Another way would be moving `height` under `colorbarStore`, which is frame dependent.

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/stores/OverlayStore/OverlayStore.ts
> +        const tickNum = Math.round((this.height() / 100.0) * this.tickDensity);
I think the tick number is also dependent to the preview frame height.

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/stores/OverlayStore/OverlayStore.ts
> +    @action previewRenderWidth(viewWidth: number) {
Looks like the preview image panel is not responsive to the new paddings when we change the colorbar position from right to bottom/top:
![image](https://user-images.githubusercontent.com/43841102/233295930-6fd25d8a-5385-4898-a10f-b0d952bfdaa9.png)
Maybe we need to change preview render width/height to a `@computed` variable returning a function so that the image panel responses with paddings.

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/components/ImageView/ImageViewComponent.tsx
> +        const viewHeight = frame.previewViewHeight || appStore.overlayStore.viewHeight;
It's for exporting png files, and we may remove changes if we don't support it. Shall we also disable Export image in the File menu?

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/stores/Frame/FrameStore.ts
> +    @observable rasterData: Float32Array;
I suggest we rename it to `previewPVRasterData` to show that it's not used for all images.

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/stores/Frame/Region/RegionStore.ts
> +    private updateRegion = async (isRequestingPreview?: boolean) => {
We can assign a default value `false` to `isRequestingPreview`.

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/components/PvGenerator/PvGeneratorComponent.tsx
> +                    <div className="generate-button">
I prefer we move the buttons to a new line.

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/components/PvGenerator/PvGeneratorComponent.scss
> +                margin: 1em;
I prefer we just add left margin.

2023-04-20 10:28 UTC, YuHsuan-Hwang commented on src/components/PvGenerator/PvGeneratorComponent.tsx
> +                <div className="pv-generator-panel">{pvImagePanel}</div>
It would be useful if we can scroll in y direction when the widget is small.

2023-04-21 03:15 UTC, crocka commented on src/stores/OverlayStore/OverlayStore.ts
> +    @action previewRenderWidth(viewWidth: number) {
I added dummy variables: paddingLeft/top/right/bottom in frame.renderWidth and frame.renderHeight. It works. What do you think of this solution?

2023-04-21 04:19 UTC, YuHsuan-Hwang commented on src/stores/OverlayStore/OverlayStore.ts
> +    @action previewRenderWidth(viewWidth: number) {
I would prefer we change `previewRenderWidth/Height` so that we won't have the same problem when reusing it in other places.

2023-04-28 04:30 UTC, YuHsuan-Hwang requested changes

2023-04-28 04:30 UTC, YuHsuan-Hwang commented on src/stores/Frame/FrameStore.ts
> +        yield TileService.Instance.decompressPreviewRasterData(compressedView, eventArgs, previewData, nanEncodings32);
I suggest we adjust the function to `decompressPreviewRasterData(fileId: number, previewData: CARTA.PvPreviewData)` and move lines 2860-2878 into `TileService`.

2023-04-28 04:30 UTC, YuHsuan-Hwang commented on src/stores/Frame/FrameStore.ts
> +        !skipUpdatePreviewData && this.updatePreviewDataGenerator.next();
I think an if-statement is clearer: `if (!skipUpdatePreviewData) {...}`

2023-04-28 04:30 UTC, YuHsuan-Hwang commented on src/services/PreviewWebGLService.ts
> +export class PreviewWebGLService {
Is it possible to inherit `TileWebGLService` and override `Instance()`?

2023-05-02 06:05 UTC, YuHsuan-Hwang approved these changes
New changes are looking good.

2023-05-02 07:34 UTC, kswang1029 approved these changes

2023-05-03 02:37 UTC, YuHsuan-Hwang commented
This PR is ready for merge once the protobuf merge conflict is resolved and changelog is updated.

2023-05-03 02:49 UTC, markccchiang approved these changes

2023-05-03 11:34 UTC, merged