Yuhsuan/2114 splatalogue backend query
CARTAvis/carta-frontend pull request #2126
Opened 2023-03-23 04:59 UTC by YuHsuan-Hwang

**Description**

1. Closes #2114

- Implemented Splatalogue advanced backend query based on the [document](https://docs.google.com/document/d/1xEZ4_IcyJUo5CermETjOtO96jp4oYC7fJhy7iJlB25I/edit#)
  - See "Implementation -> mode 1 and 2" in the document for the details of the query parameters
  - See "Implementation -> Headers" in the document for the details of the received data format and the corresponding headers from the current approach. I preserved the displayed columns in the table, with some minor changes:
    1. "CDMS/JPL Intensity": `0.00000` becomes empty
    ![image](https://user-images.githubusercontent.com/43841102/227103532-29a892ff-e757-418b-a3ed-6d01cdd4764c.png) --> ![image](https://user-images.githubusercontent.com/43841102/227103499-e9c4987e-a029-4f19-a027-dc9b791c528e.png)

    2. "Resolved QNs": additional spaces
    ![image](https://user-images.githubusercontent.com/43841102/227104133-7f97e2bc-cb3a-4699-85fe-d4bc46c2dfbc.png) --> ![image](https://user-images.githubusercontent.com/43841102/227103914-de570e27-3ded-476d-aa39-69a2cc1f93db.png)

    3. almost all columns: trailing zeros are removed
    ![image](https://user-images.githubusercontent.com/43841102/227104670-ca690146-6aab-44c7-84e0-7e19b4cfc766.png) --> ![image](https://user-images.githubusercontent.com/43841102/227104421-73787615-1b60-4ae0-8a58-400d8357fff4.png)

- Removed the connection check when opening the widget since it does not guarantee the connection is available when the users click `Query`
- Added simple unit tests, focusing on query parameters and parsing strings

2. Fixes #2119 by changing the Error object to string

ToDo:
- [ ] update the final url

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [ ] changelog updated / no changelog update needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

2023-03-24 03:56 UTC, YuHsuan-Hwang commented
New changes:
* filter received data instead of removing the last data (which could be storing only the query string)
* improve parsing string

2023-03-28 03:59 UTC, kswang1029 requested changes
@YuHsuan-Hwang in general this looks good based on some manual tests and e2e tests. A few issues spotted:
1. In the resolved QN column, there are some html tags such as <sup></sup> or <sub></sub> left, as well as others (eg <font ...>)
![Screen Shot 2023-03-28 at 11 36 17](https://user-images.githubusercontent.com/20819712/228124453-d4ce3686-06e8-4e5f-be38-b3261f1988e5.png)
![Screen Shot 2023-03-28 at 11 34 58](https://user-images.githubusercontent.com/20819712/228124467-763db7cd-6803-4800-893f-2c3a86aef7d2.png)

2. If we switch to "Center" mode to define a center and a range in mm or cm, the query process seems taking forever. This is picked up by the e2e tests.

2023-03-28 05:47 UTC, YuHsuan-Hwang commented
> @YuHsuan-Hwang in general this looks good based on some manual tests and e2e tests. A few issues spotted:
> 
> 1. In the resolved QN column, there are some html tags such as  or  left, as well as others (eg <font ...>)

@kswang1029 Do you mean  only the resolved QN column or also other columns?

2023-03-28 05:48 UTC, kswang1029 commented
> > @YuHsuan-Hwang in general this looks good based on some manual tests and e2e tests. A few issues spotted:
> > 
> > 1. In the resolved QN column, there are some html tags such as  or  left, as well as others (eg <font ...>)
> 
> @kswang1029 Do you mean only the resolved QN column or also other columns?

so far I only spotted the issue in the resolved QN column.

2023-03-28 06:56 UTC, YuHsuan-Hwang commented
> so far I only spotted the issue in the resolved QN column.

ok

2023-04-05 00:01 UTC, crocka commented on src/services/SplatalogueService.ts
> +        data = data.filter(line => line?.["species_id"] !== null || line?.["name"]);
If line is undefined, then undefined !== null would equal true. Is that what you want? Also, should the || be && instead according to your comment on line 84?

2023-04-11 06:10 UTC, YuHsuan-Hwang commented on src/services/SplatalogueService.ts
> +        data = data.filter(line => line?.["species_id"] !== null || line?.["name"]);
> If line is undefined, then undefined !== null would equal true. Is that what you want?

You're right. I adjusted to first check if `line` is valid.

> Also, should the || be && instead according to your comment on line 84?

I would like to exclude lines with both species id and species name invalid, so I think `||` works fine.

2023-04-11 06:24 UTC, YuHsuan-Hwang commented
@kswang1029 
> 1. In the resolved QN column, there are some html tags such as  or  left, as well as others (eg <font ...>)

fixed. I found html tags in chemical name column (and they exist in dev branch), so I also removed them.

![image](https://user-images.githubusercontent.com/43841102/231072419-1c32267d-599c-4c1a-967d-34de21da51b7.png) --> ![image](https://user-images.githubusercontent.com/43841102/231072281-106a81c4-8561-47ce-ba86-e3b8299136f1.png)

Another detail is that there are also additional spaces in species column, but I think this is very minor. These are updated in the description.

> 2. If we switch to "Center" mode to define a center and a range in mm or cm, the query process seems taking forever. This is picked up by the e2e tests.

fixed

2023-04-11 09:38 UTC, kswang1029 commented
@YuHsuan-Hwang the regression spotted by the e2e test is fixed. 👍 Please convert this to formal PR and please proceed _code review_ to save time. I will perform extra manual test to know more about this new query backend meanwhile.

2023-04-14 05:55 UTC, kswang1029 commented
Spotted some minor parsing issues:
1. in the Species column, `&#150;` appears. It should be "-" so in the following example, the species is C6H-.
![Screen Shot 2023-04-14 at 13 32 38](https://user-images.githubusercontent.com/20819712/231950192-69ae7242-8bc1-4ea6-9d93-174b02ed45da.png)
There is also `&le;` as "<=".

2. in the Species column, Resolved QNs column, and Unresolved QNs column, possibly there are greek letters, such as `&alpha;`, `&gamma;`, `&epsilon;` (recombination lines), `&Omega;` (as state in QN). I suggest we show them as `alpha`, `epsilon`, `Omega`, etc.. so that users can still easily use the filter.
![Screen Shot 2023-04-14 at 13 42 18](https://user-images.githubusercontent.com/20819712/231951881-2c46471c-2594-49aa-9455-0549d897c418.png)

2023-04-17 14:06 UTC, veggiesaurus approved these changes
Code looks fine to me :+1:

2023-04-17 18:32 UTC, crocka approved these changes

2023-04-21 07:16 UTC, YuHsuan-Hwang commented
@kswang1029 I think it's not safe to convert `&xxx;` to `xxx` because there might be strings similar to `&le;`, unless we list all the possibilities.
Alternatively, I converted the symbols with `DOMParser`. Please check if this works fine, thanks.
Actually this exists in the dev branch, so I have noted it in the description.

2023-04-21 07:35 UTC, kswang1029 commented
> @kswang1029 I think it's not safe to convert `&xxx;` to `xxx` because there might be strings similar to `&le;`, unless we list all the possibilities.
> Alternatively, I converted the symbols with `DOMParser`. Please check if this works fine, thanks.
> Actually this exists in the dev branch, so I have noted it in the description.

yes, certainly this is a much better solution. Then shall we enable "select" in the table, so users can do copy-and-paster for filtering purposes?

2023-04-21 07:45 UTC, kswang1029 commented
this might work https://github.com/palantir/blueprint/blob/b0f1aff2b5a70433778e3b6661db90bdf755bfa2/packages/docs-app/src/examples/table-examples/tableSortableExample.tsx#L206
(this table behaves not the way I imagined 🤦🏻‍♂️)

2023-04-21 09:48 UTC, kswang1029 commented
> this might work https://github.com/palantir/blueprint/blob/b0f1aff2b5a70433778e3b6661db90bdf755bfa2/packages/docs-app/src/examples/table-examples/tableSortableExample.tsx#L206
> 
> or demo https://blueprintjs.com/docs/versions/3/#table/features.sorting
> 
> (this table behaves not the way I imagined 🤦🏻‍♂️)
> 
> I think we need selection and keyboard copy. The right-click context menu is not needed.

Postponing this as a future work due to its complexities released to a shared component.

2023-04-21 09:52 UTC, kswang1029 approved these changes
e2e tests are revised accordingly. No regression is observed from other e2e tests. Manual tests are fine as far as I can tell.

There is a potential performance issue: it seems with this new advanced backend query, performance degradation is observed comparing to the v3-stable spatalogue-frontend query.  This requires future investigation but it is not a showstopper of merging.

2023-04-24 08:01 UTC, merged