Mark/1488 customize histogram calculations
CARTAvis/carta-frontend pull request #2141
Opened 2023-04-14 06:35 UTC by markccchiang

**Description**

This customized the histogram calculations as described in #1488. The companion [backend PR](https://github.com/CARTAvis/carta-backend/pull/1254) and [protobuf PR](https://github.com/CARTAvis/carta-protobuf/pull/83) are shown on the hyperlinks.

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [x] changelog updated ~/ no changelog update needed~
- [x] protobuf updated to the latest dev commit ~/ no protobuf update needed~
- [ ] ~`BackendService` unchanged /~ `BackendService` changed and corresponding ICD test fix added

2023-04-19 03:08 UTC, kswang1029 commented
this looks good. please proceed code review.

2023-04-20 05:08 UTC, kswang1029 approved these changes
this looks fine. no regression is seen from e2e tests.

2023-04-20 09:13 UTC, acdo2002 commented
@markccchiang 
Because the `src/services/BackendService` is the same to the current dev one, I think the final checking item can change to "BackendService unchanged", then tick the checkbox. 

The setHistogramRequirements request in the backendService is direct adopt the protobuf defined format (i.e. CARTA.ISetHistogramRequirements), so it does not require additional modification in the BackendService.ts in the frontend code.

2023-04-24 14:40 UTC, markccchiang commented
I am fixing a bug found by @YuHsuan-Hwang. And also changing the codes according to suggestions. Will push new commits when they are done.

2023-04-27 05:03 UTC, YuHsuan-Hwang requested changes
The changes are looking good! I have some feedback for the details:

2023-04-27 05:03 UTC, YuHsuan-Hwang commented on src/components/Histogram/HistogramComponent.tsx
> +    private curLinePlotProps: LinePlotComponentProps;
I prefer we rename it to `currentLinePlotProps` for clarity.

2023-04-27 05:03 UTC, YuHsuan-Hwang commented on src/components/Histogram/HistogramComponent.tsx
> +        // Check whether the hostogram data matchs the wieget's configuration
typo: widget

2023-04-27 05:03 UTC, YuHsuan-Hwang commented on src/components/Histogram/HistogramSettingsPanelComponent/HistogramConfigPanelComponent.tsx
> +    private currentMaxNumBins: number;
I suggest we remove `currentMaxNumBins` and `maxNumBins` in the component and just use the variable `widgetStore.maxNumBins` from the store for the max bin num input. `this.currentMaxNumBins > HistogramConfigPanelComponent.BINS_LOWER_BOUND` check can be moved to `onMaxNumBinsChanged`.

2023-04-27 05:03 UTC, YuHsuan-Hwang commented on src/components/Histogram/HistogramSettingsPanelComponent/HistogramConfigPanelComponent.tsx
> +        const newMaxNumBins = this.widgetStore.currentNumBins * 2;
Shall we reset this to the default bin number * 2? If `currentNumBins` was changed to a small value, we might reset it to a value smaller than the default bin number.

2023-04-28 03:34 UTC, YuHsuan-Hwang commented on src/components/Histogram/HistogramComponent.tsx
> +        // Check whether the hostogram data matchs the wieget's configuration
@markccchiang wideget -> widget
The rest of changes all look good to me 👍

2023-04-28 06:34 UTC, markccchiang commented on src/components/Histogram/HistogramComponent.tsx
> +        // Check whether the hostogram data matchs the wieget's configuration
Oops, sorry for missing it!

2023-04-28 06:49 UTC, YuHsuan-Hwang approved these changes

2023-04-28 07:02 UTC, kswang1029 approved these changes
looking good and no regression from e2e tests. 👍

2023-05-02 08:59 UTC, YuHsuan-Hwang commented
Added fix for #2150.

2023-05-02 14:38 UTC, merged