Carli/2162 fix text annotation box size
CARTAvis/carta-frontend pull request #2170
Opened 2023-05-17 17:47 UTC by crocka

**Description**
The factor ``frame.zoomLevel / AppStore.Instance.imageRatio`` is added to the text annotation textbox so that the size of the textbox won't change with zoom.

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [ ] ~~changelog updated~~ / no changelog update needed
- [ ] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed
- [ ] `BackendService` unchanged / ~~`BackendService` changed and corresponding ICD test fix added~~

2023-05-26 04:10 UTC, kswang1029 approved these changes
this is looking good now. no regression from e2e. 👍

2023-05-29 04:09 UTC, YuHsuan-Hwang requested changes
The changes look good. I only have very minor comments.

2023-05-29 04:09 UTC, YuHsuan-Hwang commented on src/components/Dialogs/RegionDialog/CompassRulerRegionForm/CompassRulerRegionForm.tsx
> +export class CompassRulerRegionForm extends React.Component<{region: RegionStore; frame: FrameStore; wcsInfo: AST.FrameSet}> {
Remove `props.frame` if it's not used.

2023-05-29 04:09 UTC, YuHsuan-Hwang commented on src/components/Dialogs/RegionDialog/RectangularRegionForm/RectangularRegionForm.tsx
> +        const constant = fixedScreenSize ? AppStore.Instance.imageRatio / this.props.frame.zoomLevel : 1;
Perhaps rename to `scale` is more informative? Same for other functions.

2023-05-29 04:09 UTC, YuHsuan-Hwang commented on src/components/Dialogs/RegionDialog/RectangularRegionForm/RectangularRegionForm.tsx
> +        const bottomLeftInputX = (isTextAnnotation: boolean = false) => (
We could directly use `isTextAnnotation` without adding an input parameter. Same for other functions.

2023-05-30 02:51 UTC, YuHsuan-Hwang commented on src/components/Dialogs/RegionDialog/RectangularRegionForm/RectangularRegionForm.tsx
> +        const bottomLeftInputX = (isTextAnnotation: boolean = false) => (
@crocka Could we also change functions `{sizeWidthInput()}` back to elements `{sizeWidthInput}`?
Other than this, it's ready for merge. Please also update the change log, thanks.

2023-05-31 02:56 UTC, YuHsuan-Hwang approved these changes

2023-05-31 02:57 UTC, merged