KSW/add annotation shortcut
CARTAvis/carta-frontend pull request #2174
Opened 2023-05-22 13:18 UTC by kswang1029

**Description**
This is to address #2167 

A new AnnotationMenuComponent is created and reused in the ToolbarComponent.
Then a new annotation shortcut button is added to the ToolbarMenuComponent and reuse the AnnotationMenuComponent to display all annotation types for selection and draw.

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [ ] changelog updated / no changelog update needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

2023-05-25 04:49 UTC, YuHsuan-Hwang requested changes
Tested that the shortcut works good 👍  I have some suggestions:

2023-05-25 04:49 UTC, YuHsuan-Hwang commented on src/components/Menu/ToolbarMenu/ToolbarMenuComponent.tsx
> +            <Menu style={{padding: 0}}>
I think the dropdown looks better without removing the padding.

2023-05-25 04:49 UTC, YuHsuan-Hwang commented on src/components/Menu/ToolbarMenu/ToolbarMenuComponent.tsx
> +                    <Popover2 popoverClassName="annotation-menu" content={annotationMenu} position={Position.BOTTOM} minimal={true} disabled={regionButtonsDisabled}>
`popoverClassName` can be removed if it's not used. I would prefer we set `Position.BOTTOM_LEFT` to be consistent with the menu.

2023-05-25 04:49 UTC, YuHsuan-Hwang commented on src/components/Menu/ToolbarMenu/ToolbarMenuComponent.tsx
> +                                onClick={() => {
Maybe we don't need to enable annotation creation mode by clicking the button. The user could be just checking what types of annotations are available.

2023-05-25 04:49 UTC, YuHsuan-Hwang commented on src/components/Shared/AnnotationMenu/AnnotationMenuComponent.tsx
> +    handleRegionTypeClicked = (type: CARTA.RegionType) => {
Perhaps we can set `handleRegionTypeClicked` as a prop and reuse `handleRegionTypeClicked` in `ToolbarComponent` and `ToolbarMenuComponent`. These two functions are actually slightly different. I think we can try to use functional components to make the code simpler.

2023-05-25 05:26 UTC, kswang1029 commented on src/components/Menu/ToolbarMenu/ToolbarMenuComponent.tsx
> +                                onClick={() => {
the idea behind this is to sync the active state of this shortcut button with the region button in the toolbar. will think about how to simplify this.

2023-05-25 10:20 UTC, kswang1029 commented
@YuHsuan-Hwang I have tried to refactor/fix the parts that you commented. Could you have another look to make sure the direction is right?

2023-05-26 03:09 UTC, YuHsuan-Hwang commented
@kswang1029 The direction is right 👍

2023-05-29 04:39 UTC, YuHsuan-Hwang requested changes
The new changes are good. I have some final comments.

2023-05-29 04:39 UTC, YuHsuan-Hwang commented on src/components/ImageView/Toolbar/ToolbarComponent.tsx
> +                <AnnotationMenuComponent handleRegionTypeClicked={type => this.handleRegionTypeClicked(type)} />
Can be simplified to `{this.handleRegionTypeClicked}`.

2023-05-29 04:39 UTC, YuHsuan-Hwang commented on src/components/Menu/ToolbarMenu/ToolbarMenuComponent.tsx
> +                <AnnotationMenuComponent handleRegionTypeClicked={type => this.handleRegionTypeClicked(type)} />
Can be simplified to `{this.handleRegionTypeClicked}`.

2023-05-29 04:39 UTC, YuHsuan-Hwang commented on src/components/Shared/AnnotationMenu/AnnotationMenuComponent.tsx
> +export const AnnotationMenuComponent: React.FC<AnnotationMenuComponentProps> = ({handleRegionTypeClicked}) => {
`React.FC` could be problematic when upgrading to React 18. Change it to:
`export const AnnotationMenuComponent = ({handleRegionTypeClicked}: AnnotationMenuComponentProps) => {`.

2023-05-29 04:39 UTC, YuHsuan-Hwang commented on src/components/Shared/AnnotationMenu/AnnotationMenuComponent.tsx
> +        <React.Fragment>
We could simplify it to `<> ... </>`.

2023-05-29 05:40 UTC, kswang1029 commented
@YuHsuan-Hwang comments are addressed. thanks.
 No regression from e2e test apparently.

2023-05-29 05:43 UTC, YuHsuan-Hwang approved these changes

2023-05-29 17:27 UTC, crocka approved these changes

2023-05-29 17:27 UTC, crocka commented on src/components/Shared/AnnotationMenu/AnnotationMenuComponent.tsx
> +    handleRegionTypeClicked = (type: CARTA.RegionType) => {
Maybe we can pass this function in as a prop?

2023-05-31 09:54 UTC, acdo2002 approved these changes
Checking the ICD working flow, the shortcut performance is what I have expected.

2023-06-01 06:37 UTC, merged