Corrected type
CARTAvis/carta-frontend pull request #2175
Opened 2023-05-22 19:56 UTC by crocka

**Description**
The ``exportTsvFile`` function in ``export.ts`` is where the exported tsv files are named. ``imageName`` and ``plotName`` are parameters of the function that go into the names of the exported tsv files. This PR resolves #1987.

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [ ] changelog updated / ~~no changelog update needed~~
- [ ] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed
- [ ] `BackendService` unchanged / ~~`BackendService` changed and corresponding ICD test fix added~~

2023-05-23 06:56 UTC, kswang1029 commented
@crocka I tested with an image file named like "spire500 ext.fits" (there is a space in the filename) then the exported tsv filename would have the space too. I suggest we replace space with _ (underscore).

Attached is the example file exported with v4-beta. It appears that there is a blank line in the end.
[spire500 ext.fits.HDU_1_image-X-profile-2023-05-23-14-52-49.tsv.zip](https://github.com/CARTAvis/carta-frontend/files/11540481/spire500.ext.fits.HDU_1_image-X-profile-2023-05-23-14-52-49.tsv.zip)

2023-05-26 02:30 UTC, kswang1029 commented
tsv and txt files are now with "space" in filename replaced by "__". 👍 The \n issue is also fixed.
One last question, do we want to apply the space -> __ treatment to png filename too for consistency?

2023-05-29 05:36 UTC, YuHsuan-Hwang requested changes
Text filename in `ProfileFittingComponent` need to be changed to `Profile_Fitting_Result_Log`. The space is modified to double underscore.

2023-05-29 05:36 UTC, YuHsuan-Hwang commented on src/utilities/export/export.ts
> +    a.download = `${imageName.replace(" ", "__")}-${plotName.replace(" ", "-")}-${getTimestamp()}.tsv`;
This will only replace the first space. Perhaps use `replaceAll`. Same for the other function.

2023-05-30 03:33 UTC, YuHsuan-Hwang approved these changes

2023-05-31 01:59 UTC, kswang1029 approved these changes

2023-05-31 02:59 UTC, YuHsuan-Hwang commented
This is ready for merge. @crocka Please update the change log, thanks.

2023-06-02 03:49 UTC, merged