Thchang/2138 disable spell check
CARTAvis/carta-frontend pull request #2186
Opened 2023-06-09 07:04 UTC by TienHao

**Description**

Closed #2138 by adding `spellcheck="false"` in text input and textarea.

* Adding spellcheck in text input without `spellcheck="false"`.
* In case any developer forget to disable spell check, added an event listener to add `spellcheck="false"` to the text input once an input event is triggered.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [x] changelog updated / ~no changelog update needed~
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

2023-06-12 01:19 UTC, kswang1029 requested changes
@TienHao this mostly looks good. Please enable spell check for the text annotation.
A question: for existing input, we manually disable spell check. If we add a new input in the future do you mean we don't have to disable it manually based on the new event listener in AppStore?

2023-06-12 10:49 UTC, TienHao commented
I have enabled spell check for the text annotation. (no more spellcheck changes for textarea elements in the new event listener)

>  A question: for existing input, we manually disable spell check. If we add a new input in the future do you mean we don't have to disable it manually based on the new event listener in AppStore?

Yes, we don't need to disable it manually. I made a few change in the event listener. The default value of spellcheck is false now, and if some text input still need a spell check just adding `spellCheck={true}` in them.

2023-06-13 01:58 UTC, kswang1029 approved these changes

2023-06-14 05:41 UTC, YuHsuan-Hwang approved these changes

2023-06-14 05:41 UTC, YuHsuan-Hwang commented on CHANGELOG.md
> +* Disabled spell check in text input and textarea ([#2138](https://github.com/CARTAvis/carta-frontend/issues/2138)).
Remove "textarea."

2023-06-14 10:33 UTC, TienHao commented on CHANGELOG.md
> +* Disabled spell check in text input and textarea ([#2138](https://github.com/CARTAvis/carta-frontend/issues/2138)).
thanks, just fixed!

2023-06-15 01:44 UTC, crocka approved these changes

2023-06-26 01:26 UTC, merged