Thchang/2155 fixed the UI alignment in workspace dialog
CARTAvis/carta-frontend pull request #2187
Opened 2023-06-09 07:13 UTC by TienHao

**Description**
closes #2155. Fixed overflowed long image name and text input alignment in workspace dialog by modified css file.

![ezgif com-video-to-gif (1)](https://github.com/CARTAvis/carta-frontend/assets/20379662/9429ed4b-77e5-4b60-bf50-ecbfd9f7f1cb)

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [x] changelog updated / ~no changelog update needed~
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

2023-06-12 03:12 UTC, kswang1029 requested changes
mostly good. 👍 no regression from e2e tests.

we need to make the input field a bit narrower in order to show the highlight properly.
![Screenshot 2023-06-12 at 11 08 20](https://github.com/CARTAvis/carta-frontend/assets/20819712/e4205ccc-a191-4d0c-a969-2ae201e4e1d5)

2023-06-13 01:32 UTC, kswang1029 approved these changes

2023-06-14 05:49 UTC, YuHsuan-Hwang approved these changes

2023-06-15 01:55 UTC, crocka approved these changes

2023-06-26 01:27 UTC, merged