Thchang/2098 spectral matching type selectors improvement
CARTAvis/carta-frontend pull request #2197
Opened 2023-06-28 03:38 UTC by TienHao

**Description**

Closes #2098: Not to sync the selector of spectral matching type in **Image List Settings** with the one in the global preferences. Modified by adding `spectralMatchingType` in AppStore.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [x] changelog updated / ~no changelog update needed~
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

2023-07-03 03:42 UTC, kswang1029 approved these changes
This works nicely. No regression from e2e tests. 👍

2023-07-03 04:01 UTC, YuHsuan-Hwang requested changes
The feature is working nice. I have some minor suggestions.

2023-07-03 04:01 UTC, YuHsuan-Hwang commented on src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx
> +                                Please change in the <b>Image List Settings</b>.
I prefer we change it to "Please modify the settings in the Image List Settings."

2023-07-03 04:01 UTC, YuHsuan-Hwang commented on src/stores/AppStore/AppStore.ts
> +                this.setSpectralMatchingType(this.preferenceStore.spectralMatchingType);
I suggest we move this line before `checkNewRelease()` because fetching data could take time.

2023-07-03 04:01 UTC, YuHsuan-Hwang commented on src/stores/AppStore/AppStore.ts
> +    @observable spectralMatchingType: SpectralType;
Perhaps move this line to the upper part of this file for consistency?

2023-07-05 10:37 UTC, TienHao commented on src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx
> +                                Please change in the <b>Image List Settings</b>.
Sure, no problem.

2023-07-05 10:37 UTC, TienHao commented on src/stores/AppStore/AppStore.ts
> +                this.setSpectralMatchingType(this.preferenceStore.spectralMatchingType);
Thanks for noting that.

2023-07-05 10:37 UTC, TienHao commented on src/stores/AppStore/AppStore.ts
> +    @observable spectralMatchingType: SpectralType;
OK

2023-07-06 02:42 UTC, YuHsuan-Hwang commented on src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx
> +                                Please change in the <b>Image List Settings</b>.
@TienHao Sorry, I meant changing the second sentence. How about we have just one sentence: "For instant changes, please modify the settings in the Image List Settings."?

2023-07-06 03:00 UTC, kswang1029 commented on src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx
> +                                Please change in the <b>Image List Settings</b>.
I suggest we don't need that tooltip.

2023-07-06 03:08 UTC, TienHao commented on src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx
> +                                Please change in the <b>Image List Settings</b>.
That's OK, the new one is pretty good. Thanks!

2023-07-06 03:55 UTC, TienHao commented on src/components/Dialogs/PreferenceDialog/PreferenceDialogComponent.tsx
> +                                Please change in the <b>Image List Settings</b>.
Sorry, I missed @kswang1029 's comment, just removed it.

2023-07-06 05:08 UTC, YuHsuan-Hwang approved these changes

2023-07-06 05:09 UTC, merged