Thchang/ hide the blinking toolbar when animating images
CARTAvis/carta-frontend pull request #2209
Opened 2023-07-21 08:56 UTC by TienHao

**Description**

closes #2163. The toolbar blinked during animating images.

The blinking was caused by property `imageToolbarVisible`, which controlled the visibility of the toolbar in ImagePanelComponent, being reset to `false` when the next image is displayed during animating images. After we have grid view function, the ImageViewComponent computes list of new ImagePanelComponent when displayed images change. 

This part could be fixed by passing properties from ImageViewComponent. But another problem raised, that the toolbar might still be remained after the cursor leaving the image view, since the `onMouseLeave` won't be triggered when the node of images gets detached. (refer the [issue](https://github.com/facebook/react/issues/6807) from React)

As a result, hiding the toolbar when animating images to fix this issue.

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [x] changelog updated / ~no changelog update needed~
- [x] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [x] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

2023-07-24 08:40 UTC, YuHsuan-Hwang requested changes
Currently we can click the invisible buttons during animation. We might need to avoid rendering the toolbar.

2023-07-26 08:11 UTC, YuHsuan-Hwang approved these changes

2023-07-26 09:19 UTC, kswang1029 approved these changes

2023-07-31 05:08 UTC, crocka approved these changes

2023-07-31 05:37 UTC, merged