Carli/1223 zfp compression artifacts
CARTAvis/carta-frontend pull request #2218
Opened 2023-07-31 04:51 UTC by crocka

**Description**

linked issues and companion PRs (if there are), what is implemented or fixed, how to test it, …

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [ ] changelog updated / no changelog update needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

2023-08-02 02:03 UTC, kswang1029 approved these changes
looks good. Tested with other moment1 (velocity field) or moment2 (velocity dispersion) images and all are looking fine. no regression from e2e tests.

2023-08-10 04:08 UTC, YuHsuan-Hwang requested changes
The changes look good. 👍 Some minor comments:

2023-08-10 04:08 UTC, YuHsuan-Hwang commented on src/stores/AppStore/AppStore.ts
> +    headerUnit?: string;
Shall this be required instead of optional?

2023-08-10 04:08 UTC, YuHsuan-Hwang commented on src/stores/AppStore/AppStore.ts
> +                let compressionQuality = this.preferenceStore.imageCompressionQuality;
Perhaps simplify to one line as in `updateView`.

2023-08-10 04:08 UTC, YuHsuan-Hwang commented on src/stores/AppStore/AppStore.ts
> +        // If BUNIT = km/s, adopted compressionQuality is set to 32 regardless the preferences setup
Can be moved to `else` section.

2023-08-11 02:40 UTC, YuHsuan-Hwang approved these changes

2023-08-11 02:41 UTC, YuHsuan-Hwang commented
@crocka Please update the change log, thanks.

2023-08-15 01:44 UTC, merged