Fix the stuck of stokes animation at low frame rates (1 or 2)
CARTAvis/carta-frontend pull request #2228
Opened 2023-08-13 17:32 UTC by markccchiang

**Description**

linked issues and companion PRs (if there are), what is implemented or fixed, how to test it, …
This is to fix the [backend issue 1293](https://github.com/CARTAvis/carta-backend/issues/1293). But it may be straightforward to fix in the frontend.

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added
- [ ] changelog updated ~/ no changelog update needed~
- [x] ~protobuf updated to the latest dev commit /~ no protobuf update needed
- [x] `BackendService` unchanged ~/ `BackendService` changed and corresponding ICD test fix added~

2023-08-15 06:03 UTC, kswang1029 approved these changes
confirmed the fix. no regression from e2e tests. please turn this into a formal PR and please proceed code review.

2023-08-21 08:22 UTC, YuHsuan-Hwang requested changes
Some naming suggestions:
1. Rename `stokes_index` to `stokesIndex`.
2. How about we swap the naming of `stokes_index` and `stokes`? Looks like `stokes` is the Stokes index of the image, so maybe it's more like "stokes index".

2023-08-22 09:15 UTC, kswang1029 approved these changes
retested and all good. no regression from e2e

2023-08-22 09:21 UTC, YuHsuan-Hwang approved these changes

2023-08-22 10:41 UTC, merged