Angus/sharing workspaces
CARTAvis/carta-frontend pull request #2234
Opened 2023-08-21 14:10 UTC by veggiesaurus

**Description**
#sharing
Companion PR of https://github.com/CARTAvis/carta-controller/pull/155 and https://github.com/CARTAvis/carta-backend/pull/1299

- Workspaces can be shared once they are saved, using the "share" button in the top-right corner of the interface
- Workspaces can optionally be saved before sharing
- Refactored clipboard sharing slightly with `copyToClipboard` function

![image](https://github.com/CARTAvis/carta-frontend/assets/592504/2bd9ce99-8384-4ceb-bb48-9c68f797a308)
![image](https://github.com/CARTAvis/carta-frontend/assets/592504/235b89af-4cb5-4799-ba3c-fa18f0a1999f)
![image](https://github.com/CARTAvis/carta-frontend/assets/592504/08717940-da01-43f9-a032-2ae25fd86b0c)

**Checklist**

For linked issues (if there are):
- [x] assignee and label added
- [x] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [x] reviewers and assignee added
- [x] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing
- [x] changelog updated
- [x] no protobuf update needed
- [ ] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

2023-08-24 05:04 UTC, crocka commented on src/stores/AppStore/AppStore.ts
> +        const hasWorkspaceParam = workspaceKeyParam || workspaceNameParam;
Should we use ``??`` here like in line 241 to avoid the case when workspaceKeyParam = 0?

2023-08-25 03:39 UTC, YuHsuan-Hwang requested changes
Overall the changes look good. 👍

2023-08-25 03:39 UTC, YuHsuan-Hwang commented on src/components/Dialogs/ShareWorkspaceDialog/ShareWorkspaceDialogComponent.tsx
> +    const [saveBeforeShare, setSaveBeforeShare] = React.useState<boolean>(false);
Do we update these status when the active workspace is changed?

2023-08-25 03:39 UTC, YuHsuan-Hwang commented on src/components/Dialogs/ShareWorkspaceDialog/ShareWorkspaceDialogComponent.tsx
> +            <Tooltip2>
Remove empty tooltip.

2023-08-25 03:39 UTC, YuHsuan-Hwang commented on src/components/Dialogs/ShareWorkspaceDialog/ShareWorkspaceDialogComponent.tsx
> +            <>
This can be removed.

2023-08-25 03:54 UTC, crocka commented on src/components/Dialogs/ShareWorkspaceDialog/ShareWorkspaceDialogComponent.tsx
> +    const [saveBeforeShare, setSaveBeforeShare] = React.useState<boolean>(false);
From the video in the description, I think the background is disabled, so I think there's no way to change the active workspace. And when this dialog component is closed, the states are lost and not preserved. These states are initialized again when the dialog is opened.

2023-08-25 04:51 UTC, arusstaylor commented
This is exciting!

2023-08-30 03:21 UTC, YuHsuan-Hwang commented on src/components/Dialogs/ShareWorkspaceDialog/ShareWorkspaceDialogComponent.tsx
> +    const [saveBeforeShare, setSaveBeforeShare] = React.useState<boolean>(false);
Yes, we can not change the active workspace when the dialog is shown, but I think the status are preserved.

2023-08-30 10:05 UTC, veggiesaurus commented on src/stores/AppStore/AppStore.ts
> +        const hasWorkspaceParam = workspaceKeyParam || workspaceNameParam;
`workspaceKeyParam` has to be a ID format (base64 encoding of a mongodb ID for example), so `0` is not a valid workspace key

2023-08-30 16:47 UTC, veggiesaurus commented on src/components/Dialogs/ShareWorkspaceDialog/ShareWorkspaceDialogComponent.tsx
> +    const [saveBeforeShare, setSaveBeforeShare] = React.useState<boolean>(false);
added a `useEffect` to handle this

2023-08-30 16:48 UTC, veggiesaurus commented
@YuHsuan-Hwang changes implemented, please re-review. 

@ajm-asiaa and @kswang1029 please test with the latest controller commits as well :innocent:  I think they address all your concerns raised.

2023-08-31 07:40 UTC, kswang1029 approved these changes

2023-08-31 09:32 UTC, YuHsuan-Hwang approved these changes

2023-09-01 05:55 UTC, merged