Carli/2242 ruler image matching bug
CARTAvis/carta-frontend pull request #2258
Opened 2023-09-20 23:21 UTC by crocka

**Description**

This PR fixes #2242. This bug is introduced by PR #2190, where the ``spatialTransformAst`` frameSet object in ``FrameStore`` was replace by a cmpMap. The fix is simply to introduce the original transform frameSet back and name it ``spatialTransformFrameSet``.

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added / new e2e test created
- [ ] changelog updated / ~~no changelog update needed~~
- [ ] ~~protobuf updated to the latest dev commit~~ / no protobuf update needed
- [ ] `BackendService` unchanged / ~~`BackendService` changed and corresponding ICD test fix added~~

2023-09-22 04:07 UTC, kswang1029 commented
please proceed code review. A set of e2e tests will be added to address spatial matching of annotations.

2023-10-13 02:06 UTC, loveluthien approved these changes
The bug is fixed.

2023-10-16 03:07 UTC, YuHsuan-Hwang requested changes
The new fix looks good! I have some minor suggestions. Please also update the change log, thanks.

2023-10-16 03:07 UTC, YuHsuan-Hwang commented on src/stores/Frame/AnnotationStore.ts
> +    public getCompassApproximation(astTransform: AST.FrameSet, spatiallyMatched?: boolean, spatialTransform?: AST.Mapping): {northApproximatePoints: number[]; eastApproximatePoints: number[]} {
I suggest we rename `astTransform` to `wcsInfo`.

2023-10-16 03:07 UTC, YuHsuan-Hwang commented on src/stores/Frame/AnnotationStore.ts
> +    public getCurveApproximation(astTransform: AST.FrameSet, mapping?: AST.Mapping): {xApproximatePoints: number[]; yApproximatePoints: number[]; hypotenuseApproximatePoints: number[]} {
I suggest we rename `astTransform` to `wcsInfo`.

2023-10-16 03:07 UTC, YuHsuan-Hwang commented on wasm_src/ast_wrapper/ast_wrapper.cc
> +    double dist = astDistance(frame, start, finish);
Could we directly use `wcsinfo`? (same for `astOffset` below)

2023-10-16 03:07 UTC, YuHsuan-Hwang commented on wasm_src/ast_wrapper/post.ts
> +
Remove empty line.

2023-10-16 05:29 UTC, YuHsuan-Hwang commented on CHANGELOG.md
> +* Fixed ruler annotation matching bug ([#2242](https://github.com/CARTAvis/carta-frontend/issues/2242)).
@crocka Please update to the latest dev and move it to [Unreleased].

2023-10-16 06:28 UTC, YuHsuan-Hwang approved these changes

2023-10-17 01:34 UTC, kswang1029 approved these changes

2023-10-17 01:36 UTC, kswang1029 commented
@loveluthien please have a final test (due to new code changes).

2023-10-17 04:34 UTC, loveluthien approved these changes
Tested.

2023-10-19 02:55 UTC, merged

2023-10-27 03:01 UTC, crocka commented on src/stores/Frame/Region/RegionStore.ts
> +        if (this.regionType === CARTA.RegionType.LINE || this.regionType === CARTA.RegionType.ANNLINE || this.regionType === CARTA.RegionType.ANNVECTOR || this.regionType === CARTA.RegionType.ANNRULE
@confluence Hi Adriana, could you please confirm if this PR fixed issue #2246?