Used react-virtualized to make a virtualized set
CARTAvis/carta-frontend pull request #2269
Opened 2023-10-14 09:08 UTC by crocka

**Description**

linked issues and companion PRs (if there are), what is implemented or fixed, how to test it, …

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added / new e2e test created
- [ ] changelog updated / no changelog update needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] protobuf version bumped / protobuf version not bumped
- [ ] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

2023-10-17 00:57 UTC, kswang1029 approved these changes
Looks good. No regression from e2e tests. Please proceed code review.

2023-10-25 02:38 UTC, kswang1029 approved these changes
retested. The browser is responsive when there are 4000 regions in my test case. Selecting a region can also trigger a region highlight in the region list of the file browser. No regression from e2e tests.

2023-10-30 07:25 UTC, YuHsuan-Hwang requested changes
The feature looks good. 👍 I have some minor comments.

2023-10-30 07:25 UTC, YuHsuan-Hwang commented on package.json
> +}
Remove changes in `package.json` and `package-lock.json`.

2023-10-30 07:25 UTC, YuHsuan-Hwang commented on src/components/Dialogs/FileBrowser/RegionSelect/RegionSelectComponent.tsx
> +    private reference: HTMLDivElement;
Is this unused?

2023-10-30 07:25 UTC, YuHsuan-Hwang commented on src/stores/FileBrowserStore/FileBrowserStore.ts
> +            this.exportRegionIndexes = [...this.exportRegionIndexes].sort();
1. I think we only need to copy the array once within the action function.
2. Should `sort()` be changed to `sort((a, b) => a - b)`?

2023-11-01 07:58 UTC, loveluthien commented
The export part is good, but the import part has a similar issue. The window of the import region becomes less responsive when we click a file with lots of regions. Do we want to deal with the import part in this PR?

2023-11-23 07:51 UTC, YuHsuan-Hwang commented
> The export part is good, but the import part has a similar issue. The window of the import region becomes less responsive when we click a file with lots of regions. Do we want to deal with the import part in this PR?

Let's work on it with a separate PR.
@loveluthien Could you help file a new issue for this?

2023-11-23 08:25 UTC, loveluthien approved these changes
It looks good. I will file issue about the import part.

2023-12-04 08:42 UTC, YuHsuan-Hwang approved these changes

2023-12-04 08:45 UTC, merged