Added annruler to setRotation, line region setting
CARTAvis/carta-frontend pull request #2280
Opened 2023-10-27 23:22 UTC by crocka

**Description**

linked issues and companion PRs (if there are), what is implemented or fixed, how to test it, …

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added / new e2e test created
- [ ] changelog updated / no changelog update needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] protobuf version bumped / protobuf version not bumped
- [ ] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

2023-10-30 07:48 UTC, YuHsuan-Hwang approved these changes
The changes looks good. 👍

2023-10-30 10:17 UTC, confluence commented
Are we making a decision for the 2D size of line-shaped regions to have positive components regardless of the direction of the line? This will lead to some unexpected behaviour if the user interacts with region sizes using scripting:

* If the user sets a size with one or more negative components, the size returned with `size` will not be the same as the size set with `setSize`.
* Passing the size returned by `size` back into `setSize` (or another size with positive components) may transform the shape of the region, depending on what the original signs are:
  * If both raw values calculated from the endpoints have been negated, the endpoints will be switched. (Are there any calculations based on line regions where the direction of the endpoints is significant?)
  * If only one of the values has been negated, the region will be rotated by 90°!
* It is no longer possible to specify an orientation for the line by setting the size.

My suggestion would be to keep (half of) the current behaviour, where the 2D size of a line can have negative components, but to flip the endpoints in the calculation -- that is, to subtract endpoint 0 from endpoint 1, so that a component pointing in a positive direction will be positive. Then the orientation of the line will determine the signs of the components, an unambiguous orientation can be selected when the size is set, and the value returned by `size` will preserve the value that was set with `setSize`.

2023-11-01 10:15 UTC, confluence commented
Revised idea (as discussed in today's dev meeting): only allow positive sizes, but take the current rotation into account when setting the size, so that the current orientation of the line is preserved.

2023-12-05 06:18 UTC, YuHsuan-Hwang requested changes
The changes are good.

When the rotation is 0, we fail to set x size. To reproduce with JS snippet:
```js
const file = await app.openFile([path], [any file]);
const region = await file.regionSet.addRegionAsync(1, [{x: 1.5, y: 2}, {x: 1.5, y: 1}]);
//region.setSize({x: 2, y: 3}); // incorrect
//region.setSize({x: 0, y: 3}); // correct
//region.setSize({x: 2, y: 0}); // incorrect
```

2023-12-05 06:18 UTC, YuHsuan-Hwang commented on src/stores/Frame/Region/RegionStore.ts
> +            const _x = x * Math.sign(Math.sin(rotation));
Perhaps rename `_x` to `newX`.

2023-12-05 06:18 UTC, YuHsuan-Hwang commented on src/stores/Frame/Region/RegionStore.ts
>      @action setSize = (p: Point2D, skipUpdate = false) => {
It would be nice if we can add TSDoc to `setSize()` and `size`.

2023-12-07 08:49 UTC, YuHsuan-Hwang requested changes
The new changes looks good to me. I have some comments for the documentation.

Currently, `setSize` updates start/end while keeping the rotation within the same quadrant (with a rotation change <= 90 degrees). @confluence Could you check if this works for scripting?

2023-12-07 08:49 UTC, YuHsuan-Hwang commented on src/stores/Frame/Region/RegionStore.ts
> +     * Getter for the sizes of regions and annotations
I suggest we revise it to "Returns the sizes of regions and annotations. For line regions and annotations, vector annotations, and ruler annotations, returns x and y absolute displacements."

2023-12-07 08:49 UTC, YuHsuan-Hwang commented on src/stores/Frame/Region/RegionStore.ts
> +     * @returns A Point2D object with x and y size components.
I suggest we revise it to "The x and y size components." (We don't need to include types.)

2023-12-07 08:49 UTC, YuHsuan-Hwang commented on src/stores/Frame/Region/RegionStore.ts
> +     *            For line region and annotation, vector annotation, and ruler annotation, the function sets the individual new x and y components of the linear segment.
Perhaps revise it to "For line regions and annotations, vector annotations, and ruler annotations, the function sets the new start and end positions while keeping the rotation within the same quadrant."

2023-12-07 08:56 UTC, confluence commented
> @confluence Could you check if this works for scripting?

I will check it now, and make the current region PR behave consistently (and adjust the scripting code in dev after the merge / branch).

2023-12-07 09:54 UTC, confluence approved these changes
I'm happy with the current behaviour -- I tested with 4 x 4 regions (one per line-like type x one per quadrant), and confirmed that all the types behave consistently and that orientation is preserved (unless one of the dimensions is set to zero, in which case the orientation is reset to consistent defaults).

I will update the patched functionality in the region PR to match this.

2023-12-11 03:07 UTC, YuHsuan-Hwang approved these changes

2023-12-11 03:08 UTC, YuHsuan-Hwang commented
Requires final checks for e2e tests.

2023-12-11 04:58 UTC, kswang1029 approved these changes
tested. a few ruler-related e2e tests have been fixed in a branch.

2023-12-11 09:03 UTC, merged