Remove distanceMeasuring from preview frames
CARTAvis/carta-frontend pull request #2281
Opened 2023-10-28 23:10 UTC by crocka

**Description**

linked issues and companion PRs (if there are), what is implemented or fixed, how to test it, …

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added / new e2e test created
- [ ] changelog updated / no changelog update needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] protobuf version bumped / protobuf version not bumped
- [ ] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

2023-10-30 08:15 UTC, YuHsuan-Hwang requested changes

2023-10-30 08:15 UTC, YuHsuan-Hwang commented on src/components/ImageView/RegionView/RegionViewComponent.tsx
> +        if ((regionSet.mode === RegionMode.CREATING || AppStore.Instance?.activeLayer === ImageViewLayer.DistanceMeasuring) && !frame.isPreview) {
Currently we can draw regions with the menu. I think we either disable drawing regions or keep the crosshair cursor style for the `CREATING` region mode.

2023-10-30 08:15 UTC, YuHsuan-Hwang commented on src/stores/Frame/FrameStore.ts
> +        this.distanceMeasuring = null;
Do we need to check if `isPreview` is true? If `setIsPreview(false)` is called, do we enable distance tool?

2023-11-02 06:06 UTC, YuHsuan-Hwang requested changes

2023-11-02 06:06 UTC, YuHsuan-Hwang commented on src/stores/Frame/FrameStore.ts
> +        this.distanceMeasuring = !frameInfo.preview && new DistanceMeasuringStore();
Please initialize it to null instead of false.

2023-11-02 06:06 UTC, YuHsuan-Hwang commented on src/stores/Frame/FrameStore.ts
> +        this.isPreview = frameInfo.preview;
If preview is included in `this.frameInfo`, how about we change `this.isPreview` to a `@computed getter`?

2023-11-17 01:10 UTC, YuHsuan-Hwang approved these changes

2023-11-23 08:56 UTC, loveluthien approved these changes
It works well.

2023-11-23 09:24 UTC, YuHsuan-Hwang commented
Require final check for e2e tests.

2023-11-23 12:36 UTC, kswang1029 approved these changes
looks good. no regression from e2e tests.

2023-11-24 02:48 UTC, merged