Fixed sorting condition
CARTAvis/carta-frontend pull request #2282
Opened 2023-10-30 00:50 UTC by crocka

**Description**

Closes #2251. The levels array is sorted incorrectly. For instance, [10, 20, 40, 3] will be sorted as [10, 20, 3, 40], causing the deletion of incorrect indexed level.

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / corresponding fix added / new e2e test created
- [ ] changelog updated / no changelog update needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] protobuf version bumped / protobuf version not bumped
- [ ] `BackendService` unchanged / `BackendService` changed and corresponding ICD test fix added

2023-10-30 08:23 UTC, YuHsuan-Hwang requested changes
Good fix. I think we also need to fix this line:
https://github.com/CARTAvis/carta-frontend/blob/dev/src/components/Dialogs/ContourDialog/ContourDialogComponent.tsx#L226

2023-11-01 06:44 UTC, kswang1029 approved these changes
looks good, no regression from e2e

2023-11-01 08:36 UTC, loveluthien approved these changes
It works correctly now.

2023-11-02 06:07 UTC, YuHsuan-Hwang approved these changes
@crocka Please update the change log, thanks.

2023-11-17 01:26 UTC, merged