Kuanchou/2044 dropdown menu style
CARTAvis/carta-frontend pull request #2301
Opened 2023-11-28 16:26 UTC by loveluthien

**Description**

Closes #2044. Make all dropdown menu styles consistent including the menu in the contour, vector, fitting dialogs, PV generator,  catalog setting, and fitting panel in spectral profile setting. Some minor UI adjustments. 

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] e2e test passing / ~corresponding fix added / new e2e test created~
- [ ] changelog updated / ~no changelog update needed~
- [ ] ~protobuf updated to the latest dev commit~ / no protobuf update needed
- [ ] ~protobuf version bumped~ / protobuf version not bumped
- [ ] `BackendService` unchanged / ~`BackendService` changed and corresponding ICD test fix added~

2023-12-04 08:38 UTC, YuHsuan-Hwang requested changes
The changes are good. 👍 
Shall we file a new issue for unifying the styles of the dropdown content?

2023-12-04 08:38 UTC, YuHsuan-Hwang commented on src/components/CatalogOverlay/CatalogOverlayPlotSettingsPanelComponent/CatalogOverlayPlotSettingsPanelComponent.scss
> +                width: calc(100% - 5em);
Perhaps add a comment for `5em`.

2023-12-04 08:38 UTC, YuHsuan-Hwang commented on src/components/CatalogOverlay/CatalogOverlayPlotSettingsPanelComponent/CatalogOverlayPlotSettingsPanelComponent.scss
> +    .file-menu .bp3-button {
Can be moved to line 4.

2023-12-04 08:48 UTC, loveluthien commented on src/components/CatalogOverlay/CatalogOverlayPlotSettingsPanelComponent/CatalogOverlayPlotSettingsPanelComponent.scss
> +                width: calc(100% - 5em);
The comment is added.

2023-12-04 08:52 UTC, loveluthien commented on src/components/CatalogOverlay/CatalogOverlayPlotSettingsPanelComponent/CatalogOverlayPlotSettingsPanelComponent.scss
> +    .file-menu .bp3-button {
Thanks.

2023-12-04 09:01 UTC, loveluthien commented
@YuHsuan-Hwang comments are addressed. I agree to file another issue about the dropdown content and data source infomation (like the figure). 
<img width="637" alt="截圖 2023-12-04 下午4 59 40" src="https://github.com/CARTAvis/carta-frontend/assets/6416595/09fc44f8-8baf-4c4d-a910-98d984a4914f">

2023-12-05 03:42 UTC, YuHsuan-Hwang approved these changes

2023-12-11 05:43 UTC, kswang1029 requested changes
There are two issues in the contour rendering dialog:
1) the layout of "parameters" should be a two-column layout so that users can see all control UI elements without scrolling down.
![Screenshot 2023-12-11 at 13 42 04](https://github.com/CARTAvis/carta-frontend/assets/20819712/983feb10-5f9a-4e9d-9fd6-cf11c1f869dd)

2) with a mouse is used (not touch pad), the horizontal scroll bar shows up unnecessarily. It appears there is a small gap somewhere forcing the rendering of the horizontal scroll bar.

https://github.com/CARTAvis/carta-frontend/assets/20819712/f258586d-19ae-48b8-b17d-9accdb7191bc

2023-12-11 07:53 UTC, loveluthien commented
@kswang1029 I don't have the second issue in my mac and ubutu. I will relax the width a bit to avoid the horizontal scroll bar.

2023-12-11 15:41 UTC, loveluthien commented
@kswang1029 please check the changes.

2023-12-12 04:18 UTC, kswang1029 approved these changes
looks good~

2023-12-13 03:07 UTC, merged