Update Google auth approach to use new libraries
CARTAvis/carta-frontend pull request #2345
Opened 2024-02-05 13:17 UTC by daikema

**NOTE: This is a breaking change for those using Google auth and will require updates to the controller config and Google auth registration as well as a controller install with the code from the [corresponding controller pull request](https://github.com/CARTAvis/carta-controller/pull/166) to work.**

**Description**

The vast majority of this work was on the controller side, and described in the other related pull request.

As far as the new approach goes, following initial login with Google credentials sessions are persisted using access tokens + refresh tokens generated like those for the other auth methods.  As a result, this is mostly removing existing Google code and libraries no longer needed in the frontend.

2024-02-12 12:35 UTC, veggiesaurus requested changes

2024-02-12 12:35 UTC, veggiesaurus commented on src/services/ApiService.ts
> +    logoutUsingGet?: boolean;
shouldn't this rather be `logoutUsingRedirect`? since we're redirecting the current page to that URL.

2024-02-13 08:21 UTC, daikema commented on src/services/ApiService.ts
> +    logoutUsingGet?: boolean;
As per Slack discussion now updated code to always use the redirect approach to perform a logout.

2024-02-19 06:54 UTC, YuHsuan-Hwang approved these changes
Looks good.

2024-03-14 02:57 UTC, kswang1029 commented
@daikema Can this PR be paired with the dev branch of the backend without involving the controller part? Based on what I see here is a no. Therefore, no e2e tests can pass...

2024-03-14 18:45 UTC, daikema commented
@kswang1029 when you say: 

> with http://localhost:3002/ I see something like "cannot authenticate with server".

Am I correct that this is a controller-deploy without reverse proxy in front?  Is what precisely is showing this error?  Is this the browser displaying a page?  In the debug console?  The backend trying to access controller settings?

2024-03-14 21:05 UTC, kswang1029 commented
> @kswang1029 when you say: 
> 
> 
> 
> > with http://localhost:3002/ I see something like "cannot authenticate with server".
> 
> 
> 
> Am I correct that this is a controller-deploy without reverse proxy in front?  Is what precisely is showing this error?  Is this the browser displaying a page?  In the debug console?  The backend trying to access controller settings?

No it is just the frontend + backend.

2024-03-15 13:56 UTC, daikema commented
@kswang1029 can you let me know if the latest changes fix the issues you were seeing?  I think the issue was related to your use of `--debug_no_auth` which these latest changes adjust to handle.

2024-03-15 14:12 UTC, kswang1029 commented
> @kswang1029 can you let me know if the latest changes fix the issues you were seeing? I think the issue was related to your use of `--debug_no_auth` which these latest changes adjust to handle.

Yes, now it works. I have run e2e tests and do not see regressions. 👍 

@acdo2002 could you please set up a controller instance at ASIAA for testing purpose?

2024-03-15 15:09 UTC, acdo2002 commented
@kswang1029 Yes, I am trying to do it. but this is my first to work with controller I need time to testing it then apply to the asiaa server, I will let you know when I start to set up a testing instance on the ASIAA server.

2024-03-20 11:56 UTC, kswang1029 approved these changes

2024-03-21 02:54 UTC, acdo2002 approved these changes
ASIAA set up this new carta-frontend PR (+ carta-controller PR) and it works fine.

2024-03-26 10:26 UTC, veggiesaurus approved these changes

2024-03-26 10:30 UTC, merged