Carli/1203 channel map
CARTAvis/carta-frontend pull request #2348
Opened 2024-02-18 12:33 UTC by crocka

**Description**

This resolves #1203, the channel map feature.

Todo:

Fix multi tile images rendering regression. Tiles are cleared when panning.
Tiling when stokes is changed.
Add coutour layer to channel map.
Resolve Overlay performance issue. Tried with canvas reference and canvas drawImage but didn't get a result.
SpatialProfiler should show the values for the particular channel.
GUI stuffs like page changer. Currently, the temporary channel changer is added to the image viewer setting.
Colormap position and size issue. 
Colormap and Render Config issue.
Add beam layer to channel map.
OverlayStore arragement improvement.
Display channel in the cursor info component.
Red highlight of the active channel.
Selection of which image is used for channel map.
Channel label at the top left corner of each channel dispaly.
Add page slider to animator widget

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] ZenHub issue connection, board status, and estimate updated

For the pull request:
- [ ] reviewers and assignee added
- [ ] ZenHub estimate, milestone, and release (if needed) added
- [ ] changelog updated / no changelog update needed
- [ ] unit test added (for functions with no dependenies)
- [ ] API documentation added (for public variables and methods in stores)

For dependencies:
- [ ] e2e test passing / corresponding fix added / new e2e test created
- [ ] protobuf version bumped / no protobuf version bumped needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] corresponding ICD test fix added (`BackendService` changed) / no ICD test fix needed (`BackendService` unchanged)
- [ ] user manual prepared (for large new features)

2025-01-24 09:21 UTC, YuHsuan-Hwang requested changes
Thanks for all the hard work! 👍 

Some comments:

- I would prefer we do not disable some settings in the animator widget, e.g. the image slider can change the current image, the channel slider can be modified to “Start channel”, the Stokes slider can also be functional, etc, but perhaps we can consider this in a separate PR in the next dev cycle.

- Would be nice if we can modify the channel map control widget to a consistent design with the PV Generator widget and all other widgets. Expected designs are:
  - The position of each line does not change when we resize the widget.
  - The labels of each column is aligned to the right.
  - The width of the labels does not change when we resize the widget.
  - The width of the inputs does not change when we resize the widget.
  - When overflow in y direction, show scroll shadows.
  - The slider row does not have a larger margin comparing to other rows.

- The image view in channel map mode should show NonIdealState after all images are closed.

- Please add `ChannelMapStore.ts` to `tsc-silent.config.js` to enable strict null checks (might need to fix additional errors; please check by re-running `npm start`).

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ChannelMapControl/ChannelMapControlComponent.tsx
> +        const onChannelChanged = (val: number) => {
I prefer we change this function to a method of the class or move the logic to `ChannelMapStore`.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ChannelMapControl/ChannelMapControlComponent.tsx
> +                    val += frame.frameInfo.fileInfoExtended.depth;
Perhaps we can simply clamp the value here. Adding a depth does not guarantee that the value becomes > 0, and setting the value to 0 for values that are too large might be a bit unnatural.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ChannelMapControl/ChannelMapControlComponent.tsx
> +                            <Button icon={"chevron-backward"} onClick={() => appStore.channelMapStore.setPrevPage()} data-testid="">
Please remove empty `data-testid` (same comment for all other elements in this file).

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ChannelMapControl/ChannelMapControlComponent.tsx
> +                    <label className="channel-map-control-label bp5-label">Start Channel</label>
Please use blueprint component directly instead of adding the classname `bp5-label`. Please change to lowercase “Start channel” for consistency.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ChannelMapControl/ChannelMapControlComponent.tsx
> +                    {!appStore.channelMapStore.channelMapEnabled && <NonIdealState icon={"folder-open"} title={"Channel map not enabled"} description={"Enable channel map using the menu"} />}
Instead of showing a non ideal state, I suggest we add a toggle “Enable channel map mode” at the top and collapse the settings when it is disabled.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/ImagePanel/ImagePanelComponent.tsx
> +                    <BeamProfileOverlayComponent frame={frame} top={overlayStore.padding.top} left={overlayStore.padding.left} docked={this.props.docked} padding={10} />
Duplicated with the next line.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/CursorOverlay/CursorOverlayComponent.tsx
> +    @observable divElement: HTMLDivElement;
Looks like `divElement` is not used.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
> +    frame: FrameStore;
Looks like `props.frame` is not used.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
> +    renderHeight: number;
Perhaps we don’t need to set `channelMapStore`, `renderWidth`, and `renderHeight` as props since we always use `AppStore.Instance.channelMapStore` and `AppStore.Instance.overlayStore`.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
> +    const cursorOverlayRef = React.useRef<CursorOverlayComponent>();
Looks like this is not used.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
> +        let thisIs: "corner" | "left" | "bottom" | "inner";
Perhaps rename to overlayType.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
> +        let thisIs: "corner" | "left" | "bottom" | "inner";
Perhaps rename to overlayType.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
> +                        width={overlayStore.channelMapInnerWidth(width, thisIs)}
I wonder if we can directly use `imageRenderWidth` here. Looks like `imageRenderWidth` is the width for each channel. Same comment for height.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
> +                        width={overlayStore.channelMapInnerWidth(width, thisIs)}
Same comment.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
> +            throttledDraw();
I think we can avoid using `overlayComponentRef`+throttling+`useEffect`(with a long list of dependencies) by setting the draw function as a props of `OverlayStore` and call it directly after the drawing of the corner overlay, but perhaps we can consider refactoring this in a separate PR in the next cycle since this requires some changes.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/Overlay/OverlayComponent.tsx
> +    thisIs?: "left" | "bottom" | "corner" | "inner";
I think we can remove this because it is always “corner” for type “channel-map-inner”.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/Overlay/OverlayComponent.tsx
> +    refCanvas?: any;
Looks like props `refCanvas` and related code can be removed.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/Overlay/OverlayComponent.tsx
> +            <>
This can be removed since we only have one component `canvas`.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/components/ImageView/RasterView/RasterViewComponent.tsx
> +const Float32Max = 3.402823466e38;
Please remove this line or `RasterViewComponent.Float32Max`.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/services/TileService.ts
> +export const SINGLE_TILE_DECOMPRESION_SYNC_ID = -1;
Looks like we don't need to export `SINGLE_TILE_DECOMPRESION_SYNC_ID`.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/services/TileService.ts
> +    protected static staticInstance: TileService;
We can set `staticInstance` back to private.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/services/TileService.ts
> +    protected constructor() {
We can set `constructor` back to private.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/services/TileService.ts
> +    findRanges(arr: number[]): {min: number; max: number}[] {
Looks like this function is not used.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/services/TileService.ts
> +        const channelToTilesMap = new Map<number, TileCoordinate[]>();
Perhaps we can use an array instead of a map to preserve the channel order.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/services/TileService.ts
> +            if (tileString === previousTileString && currentRange) {
We also need to check if `channel === currentRange.max + 1`.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/services/TileService.ts
> +        // Loop through all the grouped tiles array, divide the channels into ranges, and request the required channel.
The comment is outdated.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/services/TileWebGLService.ts
> +export interface ShaderUniforms {
Looks like we don't need to export it.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/stores/ChannelMapStore/ChannelMapStore.ts
> +        this.overlayStores = {corner: undefined, outer: undefined};
Looks like this is not used.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/stores/ChannelMapStore/ChannelMapStore.ts
> +    @computed get channelRange(): number {
I suggest we rename it to `endChannel`.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/stores/ChannelMapStore/ChannelMapStore.ts
> +    @action updateOverlayStoreSize(width: number, height: number) {
Looks like this is not used.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/stores/OverlayStore/OverlayStore.ts
> +    public constructor(fullViewWidth?: number, fullViewHeight?: number, base: number = 1, defaultGap: number = 2) {
The constructor can be set back to private and the input parameters are not used.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/stores/OverlayStore/OverlayStore.ts
> +        this.fullViewHeight = fullViewHeight;
Might be safer to set to 1 instead of undefined.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/stores/OverlayStore/OverlayStore.ts
> -    @computed get base() {
I prefer we set `OverlayStore.base` back to 5 instead of 1 to preserve the current paddings of the image view.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/stores/OverlayStore/OverlayStore.ts
> -    @computed get defaultGap() {
I prefer we set `OverlayStore.defaultGap` back to 5 instead of 2 to preserve the current paddings of the image view.

2025-01-24 09:21 UTC, YuHsuan-Hwang commented on src/stores/Widgets/WidgetsStore.ts
> +        channelMapStore.setChannelMapEnabled(true);
I suggest we disable the channel map mode when we click the button again.

2025-02-03 06:49 UTC, YuHsuan-Hwang requested changes
Most of the issues are fixed. The new design of the channel map control widget looks nice. 👍 
I have some new comments, but most of them should be minor:

* It would be nice if we can show "No file loaded" for the channel map view and the channel map control widget when we close all the images:
    <img src="https://github.com/user-attachments/assets/e92ac35b-2ab0-4345-af48-6b029803628f" width="400" />

2025-02-03 06:49 UTC, YuHsuan-Hwang commented on src/components/ChannelMapControl/ChannelMapControlComponent.tsx
> +            channelMapSettings.setStartChannel(clamp(val, 0, frame.frameInfo.fileInfoExtended.depth));
Should we clamp to `depth - 1`?

2025-02-03 06:49 UTC, YuHsuan-Hwang commented on src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
> +            imageViewWidth += overlayStore.paddingLeft;
Looks like `imageViewWidth/Height` are not used after this line, so we don't need to change their value according to type.

2025-02-03 06:49 UTC, YuHsuan-Hwang commented on src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
> +                        height={imageRenderHeight - 2}
I wonder what the 2's are for. Perhaps we can add some comments here to clarify their usage.

2025-02-03 06:49 UTC, YuHsuan-Hwang commented on src/components/ImageView/Overlay/OverlayComponent.tsx
> +    overlayType?: "left" | "bottom" | "corner" | "inner";
I think we can remove this because it is always “corner” for type “channel-map-inner”.

2025-02-03 06:49 UTC, YuHsuan-Hwang commented on src/components/ImageView/Overlay/OverlayComponent.tsx
> -            this.throttledRenderCanvas();
I think we should remain the throttling feature. There is a preference settings toggle for this.

2025-02-03 06:49 UTC, YuHsuan-Hwang commented on src/stores/ChannelMapStore/ChannelMapStore.ts
> +        if (startChannel < 0 || startChannel > this.masterFrame.frameInfo.fileInfoExtended.depth) {
Should we check `> depth - 1`?

2025-02-03 06:49 UTC, YuHsuan-Hwang commented on src/stores/ChannelMapStore/ChannelMapStore.ts
> +    @observable overlayStores: {corner: OverlayStore; outer: OverlayStore};
Looks like this is not used.

2025-02-03 06:49 UTC, YuHsuan-Hwang commented on src/stores/OverlayStore/OverlayStore.ts
> +            return 2;
I think this variable is used for the padding of the entire widget, i.e. the gap between the widget border and the (outer) overlay elements. I suggest we apply the same width 5 for channel map mode to have a consistent design. If we need 2 for the gaps between the inner overlay borders, we can create a new variable for it.

2025-02-03 06:49 UTC, YuHsuan-Hwang commented on src/stores/Widgets/WidgetsStore.ts
> +            imagePanelButton.attr("style", channelMapStore.channelMapEnabled ? "opacity: 0.2" : "");
I suggest keeping the image panel button and the channel map button responsive (showing a darker color when hovered) when they are clickable.

2025-02-03 06:49 UTC, YuHsuan-Hwang commented on src/stores/Widgets/WidgetsStore.ts
> +            const channelMapButton = this.getControlButton("lm-channel-map-panel", "switch to channel map", "heat-grid").on("click", this.onChannelMapButtonClick);
Perhaps change the tooltip text to "enable/disable channel map".

2025-02-03 06:49 UTC, YuHsuan-Hwang commented on src/stores/OverlayStore/OverlayStore.ts
> +    @computed get channelMapInnerWidth() {
Looks like `channelMapInnerWidth/Height` are not used.

2025-02-03 06:49 UTC, YuHsuan-Hwang commented on src/services/TileService.ts
> +                    pendingRequests.delete(key);
I wonder if we should instead check the set of tiles of a pending request (i.e. `value`) and remove a tile when it is not in `currentTileRange`. If we remove the entire pending request, might the backend cancel only some of the tiles of the request but we send duplicated requests to the backend?

2025-02-10 06:37 UTC, YuHsuan-Hwang requested changes

2025-02-10 06:37 UTC, YuHsuan-Hwang commented on src/components/ImageView/RegionView/RegionViewComponent.tsx
> +                    style={{left: this.props.left, top: this.props.top, cursor, border: `${this.props.highlighted ? "1px solid red" : "1px solid transparent"}`}}
I wonder if this is causing additional displacement to the region canvas in non-channel-map mode:
<img width="581" alt="image" src="https://github.com/user-attachments/assets/c888233c-8c9e-46f7-ab9a-554ee4ace881" />

cf. dev
<img width="582" alt="image" src="https://github.com/user-attachments/assets/c30f2d60-d91b-49e3-ac14-4aa6c567e55f" />

2025-02-10 06:37 UTC, YuHsuan-Hwang commented on src/stores/ChannelMapStore/ChannelMapStore.ts
> +        this.masterFrame = masterFrame as FrameStore;
If we allow `this.masterFrame` to be undefined, please change the type of `this.masterFrame` instead:
```js
@observable masterFrame: FrameStore | undefined;

 @action setMasterFrame(masterFrame?: FrameStore) {
        this.masterFrame = masterFrame;
        ...
```

2025-02-10 06:37 UTC, YuHsuan-Hwang commented on src/stores/OverlayStore/OverlayStore.ts
>      @action minSize(frame?: FrameStore) {
Let's remove the optional `?` because `frame` is always provided and is required in the calculation.

2025-02-12 06:22 UTC, YuHsuan-Hwang requested changes
Some comments to the new changes, but all of them are minor:

2025-02-12 06:22 UTC, YuHsuan-Hwang commented on src/components/ImageView/ChannelMapView/ChannelMapViewComponent.tsx
> +                        left={imageLeft - (channel === channelMapStore.masterFrame.requiredChannel ? 1 : 0)}
I think it might be clearer if we move highlight border related calculation into `RegionViewComponent`, but this is very minor.
For example, in this file:
```js
top={imageTop}
left={imageLeft}
```
and in `RegionViewComponent`:
```js
<Stage
    ...
    style={{left: this.props.left - this.props.highlighted ? highlightBorderWidth : 0, top: this.props.top - this.props.highlighted ? highlightBorderWidth : 0, cursor, border: `${this.props.highlighted ? `${highlightBorderWidth}px solid red` : "none"}`}}
```

2025-02-12 06:22 UTC, YuHsuan-Hwang commented on src/stores/Widgets/WidgetsStore.ts
> +            imagePanelButton.attr("style", channelMapStore.channelMapEnabled ? "opacity: 0.2" : "");
I suggest keeping the image panel button responsive (showing a darker color when hovered).

2025-02-12 06:22 UTC, YuHsuan-Hwang commented on src/stores/ChannelMapStore/ChannelMapStore.ts
> +    }
I prefer we remove optional `?` and avoid type assertion `as`:
```js
@action setMasterFrame(masterFrame: FrameStore) {
    this.masterFrame = masterFrame;
}
```

2025-02-14 06:01 UTC, YuHsuan-Hwang approved these changes

2025-02-14 06:27 UTC, kswang1029 approved these changes
This is considered as another milestone in CARTA history. Excellent work @crocka @YuHsuan-Hwang 👍

2025-02-14 07:11 UTC, loveluthien approved these changes
🏆

2025-02-14 08:20 UTC, merged