Kuahchou/2396 new restfrq for moment
CARTAvis/carta-frontend pull request #2404
Opened 2024-08-14 03:56 UTC by loveluthien

**Description**

This closed #2396 together with backend [PR](https://github.com/CARTAvis/carta-backend/pull/1387) and companian protobuf. 

**Checklist**

For linked issues (if there are):
- [ ] assignee and label added
- [ ] GitHub Project estimate added

For the pull request:
- [ ] reviewers and assignee added
- [ ] GitHub Project estimate added
- [ ] changelog updated / no changelog update needed
- [ ] unit test added (for functions with no dependenies)
- [ ] API documentation added (for public variables and methods in stores)

For dependencies:
- [ ] e2e test passing / corresponding fix added / new e2e test created
- [ ] protobuf version bumped / ~no protobuf version bumped needed~
- [ ] protobuf updated to the latest dev commit / ~no protobuf update needed~
- [ ] corresponding ICD test fix added (`BackendService` changed) / no ICD test fix needed (`BackendService` unchanged)
- [ ] user manual prepared (for large new features)

2024-08-16 05:57 UTC, kswang1029 requested changes
Regarding changing the unit of rest frequency definition, there are possible use cases:
1. user manually types in the value: in this case, user needs to configure the right unit first before typing. Or user needs to convert the value in mind if the selected unit is different from the one in user's mind (mostly the value is read from a catalog)
2. user copies and pasts a value from a catalog: in this case, users need to configure the right unit first before pasting. If pasting happens first and changing the unit later, the value will be changed too.

In both cases. the new feature (synchronize the value and unit) does not help the UX and sometimes hurts. I suggest we keep the original way (desynchronize the value and unit)

2024-08-16 06:44 UTC, loveluthien commented
> Regarding changing the unit of rest frequency definition, there are possible use cases:
> 
> 1. user manually types in the value: in this case, user needs to configure the right unit first before typing. Or user needs to convert the value in mind if the selected unit is different from the one in user's mind (mostly the value is read from a catalog)
> 2. user copies and pasts a value from a catalog: in this case, users need to configure the right unit first before pasting. If pasting happens first and changing the unit later, the value will be changed too.
> 
> In both cases. the new feature (synchronize the value and unit) does not help the UX and sometimes hurts. I suggest we keep the original way (desynchronize the value and unit)

Okay.

2024-08-19 01:13 UTC, kswang1029 requested changes
When there is no image loaded, if we enable the spectral profiler widget and then enable its settings dialog, the frontend will crash.

![Screenshot 2024-08-19 at 09 12 21](https://github.com/user-attachments/assets/aca204de-b6c6-48d0-98c8-365c8be9a3cb)

2024-08-21 09:17 UTC, loveluthien commented
update:
- Fix the frontend crash when no image loaded.
- disable the rest freq. function in the moment generator following SpectralSettingsComponent.

2024-08-21 12:30 UTC, kswang1029 approved these changes
looks nice. 👍 added new e2e tests

2024-08-22 07:52 UTC, YuHsuan-Hwang requested changes
The implemented UI looks good. Just some minor comments:

2024-08-22 07:52 UTC, YuHsuan-Hwang commented on src/components/SpectralProfiler/MomentGeneratorComponent/MomentGeneratorComponent.tsx
> +    private renderRestFreqInput = frame => {
Please add type for the input parameter `frame`.

2024-08-22 07:52 UTC, YuHsuan-Hwang commented on src/components/SpectralProfiler/MomentGeneratorComponent/MomentGeneratorComponent.tsx
> +        const restFreqStore = widgetStore.effectiveFrame?.restFreqStore;
Could be simplified to `frame?.restFreqStore`.

2024-08-22 07:52 UTC, YuHsuan-Hwang commented on src/components/SpectralProfiler/MomentGeneratorComponent/MomentGeneratorComponent.tsx
> +                    onValueChanged={val => {
Could be simplified to `onValueChanged={restFreqStore?.setCustomVal}`.

2024-08-22 07:52 UTC, YuHsuan-Hwang commented on src/stores/Widgets/SpectralProfileWidget/SpectralProfileWidgetStore.ts
>      @override setRegionId = (fileId: number, regionId: number) => {
Perhaps this function is for the spectral profiler rather than moment maps. The description is the same as `selectMomentRegion`.

2024-08-22 07:52 UTC, YuHsuan-Hwang commented on src/stores/Widgets/SpectralProfileWidget/SpectralProfileWidgetStore.ts
>      @action setSpectralCoordinate = (coordStr: string) => {
I think the moment map coordinate setting is synchronized to the profiler, so this function is mainly for the profiler.

2024-08-27 04:27 UTC, YuHsuan-Hwang approved these changes

2024-09-02 03:15 UTC, YuHsuan-Hwang commented
Pending for https://github.com/CARTAvis/carta-backend/pull/1387 code review.

2024-09-09 12:20 UTC, merged