Kuanchou/752 smart layout
CARTAvis/carta-frontend pull request #2431
Opened 2024-11-12 07:34 UTC by loveluthien

**Description**

Close #752. 

**Checklist**

- Layout is associated with loading file
- Layout will wait for the file opening
- Create LayoutMap.json in ~/..carta/config/layouts. The file LayoutMap.json will be generated if not exist
- Smart layout UI in the menu "View" -> "Layouts" -> "Smart Layout"
- Using the bottom Smart Layout in "Save layout" to save a new layout and associate it to a file type 
- Smart layout is blocked when no file is open

For linked issues (if there are):
- [ ] assignee and label added
- [ ] GitHub Project estimate added

For the pull request:
- [ ] reviewers and assignee added
- [ ] GitHub Project estimate added
- [ ] changelog updated / no changelog update needed
- [ ] unit test added (for functions with no dependenies)
- [ ] API documentation added (for public variables and methods in stores)

For dependencies:
- [ ] e2e test passing / corresponding fix added / new e2e test created
- [ ] protobuf version bumped / no protobuf version bumped needed
- [ ] protobuf updated to the latest dev commit / no protobuf update needed
- [ ] corresponding ICD test fix added (`BackendService` changed) / no ICD test fix needed (`BackendService` unchanged)
- [ ] user manual prepared (for large new features)

2025-02-04 06:33 UTC, kswang1029 requested changes
@loveluthien I made a custom layout for Stokes analysis and enabled the dynamic layout feature. When I set the layout to my custom Stokes analysis layout, the layout is applied to the current session but the dropdown menu switches back to the default layout. Then if we have a new session and load a Stokes cube, the default layout is adopted instead of my custom Stokes layout. 

https://github.com/user-attachments/assets/892f6cfd-a105-4ca3-b7f7-75d5ce19a4eb

2025-02-06 04:50 UTC, YuHsuan-Hwang requested changes
Some suggestions:
* When renaming layout, we exit rename mode when trying to click inside the input or select text.
* Layout dialog toggle tooltip: I suggest we add spaces between ctypes to have a consistent design.
  ![image](https://github.com/user-attachments/assets/a3011e82-d904-4289-b806-bbec3168658a)
* (regression) Not a common use case, but the frontend crashes when we open images with one pixel (size 1 pixel x 1 pixel).
* Not sure if this is reproducible, but I see some warnings when launching carta and when opening the layout dialog.
  When launching carta:
  ![image](https://github.com/user-attachments/assets/3478bae7-e0a6-4f47-b71c-a6d27eb94a5a)
  When opening the layout dialog:
  ![image](https://github.com/user-attachments/assets/8bcbe4cf-8fed-4444-90dd-8cb2439898a8)
  ![image](https://github.com/user-attachments/assets/0bc6ffc1-8f06-4fec-94d8-24ff8adcd3d2)

2025-02-06 04:50 UTC, YuHsuan-Hwang commented on src/stores/PreferenceStore/PreferenceStore.ts
> +        existLayoutMapping: [],
I think this needs to be initialized to `{}`.

2025-02-06 04:50 UTC, YuHsuan-Hwang commented on src/components/Dialogs/LayoutDialog/LayoutDialogComponent.tsx
> +    private handleInput = (ev: React.FormEvent<HTMLInputElement>) => {
Please add `@action` decorators when modifying observables. Same comments for the other methods in this class.

2025-02-06 04:50 UTC, YuHsuan-Hwang commented on src/stores/FileBrowserStore/FileBrowserStore.ts
> +            if (this.selectedFiles) {
I think we need to check `this.selectedFiles.length` because empty arrays are converted to true.

2025-02-06 04:50 UTC, YuHsuan-Hwang commented on src/stores/PreferenceStore/PreferenceStore.ts
> +    @computed get existLayoutMapping(): Object {
Perhaps we can apply a more specific type: `: {[key: string]: string}`.

2025-02-06 04:50 UTC, YuHsuan-Hwang commented on src/stores/LayoutStore/LayoutStore.ts
> +    @action showLayoutDialog = (mode: LayoutDialogMode, oldLayoutName?: string) => {
Looks like `showLayoutDialog` and `setLayoutDialogMode` can be removed.

2025-02-06 04:50 UTC, YuHsuan-Hwang commented on src/stores/LayoutStore/LayoutStore.ts
> +    Layout
Looks like the first three modes are not used.

2025-02-06 04:50 UTC, YuHsuan-Hwang commented on src/stores/LayoutStore/LayoutStore.ts
> +        this.oldLayoutName = ""; // for rename
Looks like this is not used.

2025-02-06 04:50 UTC, YuHsuan-Hwang commented on src/stores/DialogStore/DialogStore.ts
> +    LayoutDialog = "layout-dialog",
I wonder what is the difference between `Layout` and `LayoutDialog`?

2025-02-06 04:50 UTC, YuHsuan-Hwang commented on src/components/Menu/RootMenuComponent.tsx
> +                <MenuItem text="Layout dialog" icon={"page-layout"} onClick={() => AppStore.Instance.dialogStore.showDialog(DialogId.LayoutDialog)} />
I suggest we show "Layouts" instead of "Layout dialog" to be consistent with other menu options.

2025-02-06 04:50 UTC, YuHsuan-Hwang commented on src/components/Dialogs/FileBrowser/FileBrowserDialogComponent.tsx
> +            layoutStore.applyLayout(dynamicLayoutStore.dynamicLayoutName);
I wonder if we should apply layout before loading the image so that zooming is fit to the size of the image view.

2025-02-06 04:50 UTC, YuHsuan-Hwang commented on src/components/Dialogs/LayoutDialog/LayoutDialogComponent.tsx
> +export const LayoutMappingComponent = React.memo((props: LayoutMappingComponentProps) => {
Looks like the props are not used.

2025-02-12 07:34 UTC, YuHsuan-Hwang requested changes
Some suggestions for the layout dialog:

1. I wonder if we should reset the layout rename text when existing rename mode without saving.

2. The apply button might be a bit confusing ("apply layout" or "apply new name") in rename mode. Perhaps we can hide it during rename mode.
    ![image](https://github.com/user-attachments/assets/6394dc6a-11bb-4288-bbd9-eb251e752578)

2025-02-12 07:34 UTC, YuHsuan-Hwang commented on src/components/Dialogs/LayoutDialog/LayoutDialogComponent.tsx
> +        this.saveDynamicLayoutEnable = false;
Please add Mobx decorators when modifying observables.

2025-02-12 07:34 UTC, YuHsuan-Hwang commented on src/stores/DialogStore/DialogStore.ts
> +    LayoutDialog = "layout-dialog",
I would prefer "Layout" for consistency with other DialogId.

2025-02-12 07:34 UTC, YuHsuan-Hwang commented on src/components/Dialogs/LayoutDialog/LayoutDialogComponent.tsx
> +    const appsStore = AppStore.Instance;
Typo: appStore.

2025-02-12 07:34 UTC, YuHsuan-Hwang commented on src/components/Dialogs/LayoutDialog/LayoutDialogComponent.tsx
> +    existLayoutMapping: Object;
This can also be defined as `: {[key: string]: string}`.

2025-02-12 07:34 UTC, YuHsuan-Hwang commented on src/components/Dialogs/StokesDialog/StokesDialogComponent.tsx
> +                    layoutStore.applyLayout(activeFrame.dynamicLayout.layoutName);
Perhaps we can also move this to before loading the image so that zooming is fit to the size of the image view.

2025-02-12 07:34 UTC, YuHsuan-Hwang commented on src/stores/PreferenceStore/PreferenceStore.ts
> +            PreferenceKeys.GLOBAL_DYNAMIC_LAYOUT,
This removes all layout connections when clicking restore default in the global tab. Perhaps we need a new function for the Layout tab.

2025-02-13 06:54 UTC, YuHsuan-Hwang requested changes
Minor comments for the new changes:

2025-02-13 06:54 UTC, YuHsuan-Hwang commented on src/models/Ctype/CtypeDefinition.ts
> +export function HyperCubeCtypeTransform(ctypes: any): {ctype: string; rank: number} {
Please avoid using `any` for the type. Should the return type be `{ctype: string[]; rank: number[]}` instead?

2025-02-13 06:54 UTC, YuHsuan-Hwang commented on src/stores/FileBrowserStore/FileBrowserStore.ts
> +    @observable selectedFilesCtypes: any | null;
Please avoid using `any` for the type.

2025-02-13 06:54 UTC, YuHsuan-Hwang commented on src/components/Dialogs/StokesDialog/StokesDialogComponent.tsx
> +        // const {activeFrame} = AppStore.Instance;
Please remove comments.

2025-02-13 06:54 UTC, YuHsuan-Hwang commented on src/components/Dialogs/StokesDialog/StokesDialogComponent.tsx
> +// import {POLARIZATION_LABELS} from "models";
Please remove comments.

2025-02-13 07:50 UTC, loveluthien commented on src/components/Dialogs/StokesDialog/StokesDialogComponent.tsx
> +// import {POLARIZATION_LABELS} from "models";
done

2025-02-13 07:54 UTC, YuHsuan-Hwang approved these changes
Nice work.

2025-02-13 08:16 UTC, merged