Add file list refresh button in File Browser #557
CARTAvis/carta-frontend pull request #659
Opened 2019-12-25 08:56 UTC by TienHao

close [#557](https://github.com/CARTAvis/carta-frontend/issues/557):reload button for refresh file list in file browser 

* add button on the left of breadcrumbs

* modify css

2019-12-25 09:36 UTC, duidae requested changes
works good. some suggestions:
1. I think it should be more intuitive to use "repeat" icon instead of "refresh" since chrome & firefox also use the same icon for refresh button
2. Capitalize the title "Refresh current directory"
3. use minimal prop of button so that the UI style is consistent with bread crumb

2019-12-26 01:51 UTC, duidae approved these changes

2019-12-26 01:53 UTC, kswang1029 commented
we will need a reload button for the region file browser as well. can be in a separate PR.

2019-12-26 08:45 UTC, veggiesaurus requested changes
For consistency, we should use the BlueprintJS [tooltip](https://blueprintjs.com/docs/#core/components/tooltip) rather than the HTML tooltip.

2020-01-06 10:11 UTC, veggiesaurus approved these changes

2020-01-06 10:12 UTC, merged