cleanup:removing redundant observable decorators
CARTAvis/carta-frontend pull request #675
Opened 2020-01-15 08:21 UTC by TienHao

#668 remove redundant observable decorators

2020-01-15 08:46 UTC, duidae requested changes
some of the observables cannot be removed, please check again

2020-01-15 10:01 UTC, veggiesaurus requested changes
As @duidae stated, some `@observable` decorators can't be removed. It gets more complicated when you have a map, because it it's not marked as `@observable`, then any changes to the map won't trigger a mobX recalculation. It's best to leave any map-based `@observables` as they are

2020-01-15 10:01 UTC, veggiesaurus commented on src/stores/WidgetsStore.ts
> +    readonly renderConfigWidgets: Map<string, RenderConfigWidgetStore>;
e.g. these should just stay observable

2020-01-31 12:38 UTC, veggiesaurus commented
@TienHao is there any progress on this PR?

2020-02-03 12:47 UTC, duidae requested changes

2020-02-03 12:47 UTC, duidae commented on src/stores/LayoutStore.ts
> +    @observable private readonly layouts: any;
there are some assignments of layouts, should not be readonly

2020-02-03 12:47 UTC, duidae commented on src/stores/PreferenceStore.ts
> +    readonly regionContainer: RegionStore;
this variable will be removed after server preference branch, can keep it unmodified to avoid conflict

2020-02-03 12:47 UTC, duidae commented on src/services/BackendService.ts
> +    readonly loggingEnabled: boolean;
ok

2020-02-03 12:47 UTC, duidae commented on src/stores/LogStore.ts
> +    readonly logLimit: number;
better to use a constant to replace variable logLimit

2020-02-03 12:47 UTC, duidae commented on src/stores/RegionStore.ts
> +    readonly fileId: number;
ok

2020-02-03 12:47 UTC, duidae commented on src/stores/SpatialProfileStore.ts
> +    readonly regionId: number;
ok

2020-02-03 12:47 UTC, duidae commented on src/stores/SpectralProfileStore.ts
> +    readonly regionId: number;
ok

2020-02-03 12:47 UTC, duidae commented on src/stores/AppStore.ts
> +    readonly animatorStore: AnimatorStore;
inside autorun()

2020-02-03 12:47 UTC, duidae commented on src/stores/AppStore.ts
> +    readonly preferenceStore: PreferenceStore;
inside autorun()

2020-02-03 12:47 UTC, duidae commented on src/stores/AppStore.ts
> +    readonly alertStore: AlertStore;
ok

2020-02-04 08:58 UTC, TienHao commented on src/stores/WidgetsStore.ts
> +    readonly renderConfigWidgets: Map<string, RenderConfigWidgetStore>;
change these back in the following commit

2020-02-06 08:15 UTC, duidae approved these changes

2020-02-06 13:54 UTC, veggiesaurus approved these changes

2020-02-06 13:54 UTC, merged