Jason/spectral conversion
CARTAvis/carta-frontend pull request #744
Opened 2020-02-17 13:15 UTC by duidae

closes #647

2020-02-17 14:16 UTC, veggiesaurus commented
This is looking really useful. Quick discussion point: This makes the spectral profiler _really_ cramped. @kswang1029 what do you think of moving this out of the dropdown, and to the widget settings (at the top, because they're probably the most important settings)? Once we add the "image" dropdown, it's simply going to be way too crowded.

![image](https://user-images.githubusercontent.com/592504/74661448-a8fd2100-51a0-11ea-849e-ca5f54b46585.png)

2020-02-17 14:21 UTC, veggiesaurus commented on src/stores/widgets/RegionWidgetStore.ts
> +    public readonly appStore: AppStore;
probably don't need explicit `public`

2020-02-17 14:24 UTC, veggiesaurus commented on wasm_src/ast_wrapper/ast_wrapper.cc
> +        (void) snprintf(buffer, sizeof(buffer), "Epoch=%s", epoch);
we don't need any of these explicit `(void) ` specifiers.

2020-02-17 14:25 UTC, veggiesaurus commented on wasm_src/ast_wrapper/ast_wrapper.cc
> +    fitschan = astFitsChan(NULL, NULL, "");
should use `nullptr` instead (please update my `NULL` values at the same time :)

2020-02-17 14:47 UTC, arusstaylor commented
I agree this could go in the widget settings.

2020-02-18 03:35 UTC, duidae commented
will do the corresponding modification, btw kswang is on his flight to Taiwan, will be back soon

2020-02-18 06:41 UTC, veggiesaurus requested changes
I think the changes work well. But we need the same spectral conversion options in the Stokes widget as well, please.

2020-02-18 06:43 UTC, kswang1029 commented
Yes, moving those to setting is good. We also need to add spectral reference frame label to x-label. eg “LSRK, radio velocity (km/s)”

2020-02-18 06:44 UTC, veggiesaurus commented
> Yes, moving those to setting is good. We also need to add spectral reference frame label to x-label. eg “LSRK, radio velocity (km/s)”

Couldn't we leave the "(km/s)" out, since it would be included in the _value_ quoted itself?

2020-02-18 15:42 UTC, arusstaylor commented
I have been trained to always include units in axis labels....

2020-02-18 16:07 UTC, veggiesaurus commented
Oh wait I'm misunderstanding what @kswang1029 was suggesting 🙈

2020-02-19 12:14 UTC, veggiesaurus commented
this is looking great now. I'm just wondering: Should we increase the default size of the Stokes and spectral config widgets so that the coordinate dropdown lines up nicely? 

![image](https://user-images.githubusercontent.com/592504/74833329-ee952780-5321-11ea-88b3-3cd6cc196a26.png)

(it does seem like there's some odd CSS in the widget though, but this can be fixed later)

2020-02-19 12:16 UTC, kswang1029 commented
how are the default spectral convention and reference frame determined now?
Can we have LSRK Radio velocity (km/s) as default?

2020-02-19 12:20 UTC, kswang1029 commented
@duidae please modify "wave length" to "wavelength"

2020-02-19 12:57 UTC, duidae commented
the initial default is set to the frame's spectral setting according to it's fits header, can be change to LSRK Radio velocity (km/s) as universal default

2020-02-19 13:06 UTC, veggiesaurus commented
> the initial default is set to the frame's spectral setting according to it's fits header, can be change to LSRK Radio velocity (km/s) as universal default

To me, it makes sense to use the fits header for the default, since we're then representing what's actually in the image headers, rather than forcing a specific convention?

2020-02-19 13:10 UTC, kswang1029 commented
I think at least, if it is velocity we should use km/s. And for frequency, we can use GHz. I agree we should use the reference frame as it is defined in the header. So the requested change is to set the units to the commonly used ones.

2020-02-20 13:11 UTC, duidae commented
@veggiesaurus  @kswang1029  changed accordingly, please take a look, thanks.

2020-02-20 13:47 UTC, kswang1029 commented
@duidae found an issue, if we switch to other spectral convention and try to freeze and unfreeze cursor, we will see the unit changes.

2020-02-20 14:05 UTC, duidae commented
@kswang1029  I cant reproduce that. What file/browser are u using?

2020-02-20 14:14 UTC, kswang1029 commented
@duidae I am using Chrome with "origin/jason/spectral_conversion 3f0c72e 2020-02-20 13:17:38 UTC".

To reproduce,
1) load set_HD163296/HD163296_CO_2_1.fits
2) we see LSRK, Frequency (GHz)
3) switch to Frequency (kHz)
4) try to freeze/unfreeze cursor repeatedly and observe the unit.

2020-02-21 07:11 UTC, veggiesaurus approved these changes

2020-02-21 07:18 UTC, merged