Thchang/improve help drawer
CARTAvis/carta-frontend pull request #825
Opened 2020-03-11 09:16 UTC by TienHao

#795 : changing help drawer pictures in different themes (dark theme picture not added yet)
#679 : automatically showing help drawers on left or right depends on widgets location

2020-03-12 08:16 UTC, veggiesaurus requested changes

2020-03-12 08:16 UTC, veggiesaurus commented on src/components/Dialogs/DraggableDialog/DraggableDialogComponent.tsx
> +            const helpButton = <Button icon="help" minimal={true} onClick={(ev: React.MouseEvent<HTMLButtonElement>) => this.onClickHelpButton(ev)}/>;
can't you just use `onClick={this.onClickHelpButton}` after turning `onClickHelpButton` into an arrow-function? Anonymous functions should be avoided if possible in react, as they always trigger re-rendering

2020-03-12 08:16 UTC, veggiesaurus commented on src/components/FloatingWidget/FloatingWidgetComponent.tsx
> +                    <div className={buttonClass} onClick={(ev) => this.onClickHelpButton(ev)}>
same suggestion here

2020-03-16 20:22 UTC, veggiesaurus commented
@kswang1029 did we resolve to automatically pop up the help drawer on the opposite side to the widget? or let the user decide?

2020-03-16 23:02 UTC, kswang1029 commented
I think we should try auto.

2020-03-17 03:28 UTC, TienHao commented
> @kswang1029 did we resolve to automatically pop up the help drawer on the opposite side to the widget? or let the user decide?

I have implemented automatically left/right popping up by the horizontal location of the help button in widgets and dialogues.

2020-03-17 14:29 UTC, veggiesaurus commented
@TienHao what is the logic behind which location it chooses? I'd have thought it would be related to whether the center of the widget is to the left or right of the midpoint, but that's not happening:

![image](https://user-images.githubusercontent.com/592504/76866082-4a44c900-686c-11ea-82d2-b9a0e1775931.png)

I see it depends on where you actually _click_ the button, rather than the position of the button itself. I don't think that makes sense. But it's also not switching at the midpoint, so I'm confused as to what the intended logic is.

2020-03-19 08:35 UTC, TienHao commented
> I see it depends on where you actually _click_ the button, rather than the position of the button itself. I don't think that makes sense. But it's also not switching at the midpoint, so I'm confused as to what the intended logic is.

@veggiesaurus My previous thought is to use the position of button to decide the help drawer location without blocking the help button.(that did make sense to me at that point. :grin: I think yours better. ) Since the width of drawer is 33%, if the position of help button is over 65% width of browser, the drawer will pop up on left, and less then 65% will pop up on right. 

I have changed the logic to the center of the widget now.

2020-03-19 08:37 UTC, veggiesaurus commented
I think we should also consider not applying the dimming overlay, so that you can still see the widget properly

2020-03-23 12:50 UTC, veggiesaurus approved these changes
this looks good. Can you also make a PR for `release/1.3`

2020-03-23 12:51 UTC, merged