update AST to 9.1.1 & simplify AST initialization for spectral conversion
CARTAvis/carta-frontend pull request #852
Opened 2020-03-30 02:33 UTC by duidae

this PR includes:
1. update AST to 9.1.1 
2. simplify AST initialization for spectral conversion

2020-03-30 11:36 UTC, veggiesaurus commented on wasm_src/ast_wrapper/ast_wrapper.cc
> +    AstSpecFrame *specframe = static_cast<AstSpecFrame*>astGetFrame(found, AST__CURRENT);
Why don't we rather load all the headers into a single frame set, and _then_ split it out into a spectral and spatial frame?

2020-03-30 11:37 UTC, veggiesaurus commented on wasm_src/ast_wrapper/ast_wrapper.cc
> +    AstSpecFrame *specframe = static_cast<AstSpecFrame*>astGetFrame(found, AST__CURRENT);
For example, `initFrame` could init the entire `AstFrameSet`, and then `getSpatialFrame` and `getSpectralFrame` could pull out the appropriate frames

2020-04-02 10:52 UTC, veggiesaurus requested changes
This looks much better than our previous approach, but there's a problem with loading images with no WCS info (e.g. `LMCq.fits`). Seems to cause AST to crash.

2020-04-02 11:09 UTC, duidae commented
kk, will look into it after vacation(next week)

2020-04-06 10:21 UTC, duidae commented
using dev branch, the error also show up in AST ver. 8.7.1:

astGrid(Plot): No numerical labels can be produced for axis 1 using the supplied Frame format string 'd.*'

probably some changes between 8.6.3/8.7.1 about args for astPlot() (Format(1)=d.*, Format(2)=d.*)

will try to fix it

2020-04-06 10:29 UTC, veggiesaurus commented
> using dev branch, the error also show up in AST ver. 8.7.1:
> 
> astGrid(Plot): No numerical labels can be produced for axis 1 using the supplied Frame format string 'd.*'
> 
> probably some changes between 8.6.3/8.7.1 about args for astPlot() Format(1)='d._', Format(2)='d._'
> 
> will try to fix it

One possible solution would be to not apply the `Format` arguments when the WCS is invalid

2020-04-07 08:36 UTC, duidae commented
There are 2 issues:
1.  in 8.6.3, AST initFrame() returns invalid after reading the headers of LMCq.fits, however, after ver. 8.7.1, it returns ok, so the dummy frame will not be created.

2. originally "Format(1)=d.*" is accepted in  8.6.3, but '*' seems no longer available after 8.7.1

so a simple fix would change (2) by removing '*', and the axis will be like:

![image](https://user-images.githubusercontent.com/25971696/78647136-b60ad680-78ec-11ea-84b9-dde590347916.png)

and I think for future refactoring, initWCS() & initFullWCS() could be integrated for simplicity.

@veggiesaurus do you think the solution above ok?

2020-04-09 07:44 UTC, veggiesaurus commented
> There are 2 issues:
> 
> 1. in 8.6.3, AST initFrame() returns invalid after reading the headers of LMCq.fits, however, after ver. 8.7.1, it returns ok, so the dummy frame will not be created.
> 2. originally 'Format(1)=d.*' is accepted in  8.6.3, but '*' seems no longer available after 8.7.1
> 
> so a simple fix would change (2) by removing '*', and the axis will be like:
> 
> ![image](https://user-images.githubusercontent.com/25971696/78647136-b60ad680-78ec-11ea-84b9-dde590347916.png)
> 
> and I think for future refactoring, initWCS() & initFullWCS() could be integrated for simplicity.
> 
> @veggiesaurus do you think the solution above ok?

That sounds sensible. For (1), can we just check whether there's a spatial frame using AST? And if not, update the "validWCS" flag in FrameStore?

2020-04-20 06:58 UTC, veggiesaurus commented
@duidae is this ready for a re-review yet?

2020-04-20 07:17 UTC, duidae commented
@veggiesaurus  still working on spatial part, will notify you when ready, thanks.

2020-04-20 07:23 UTC, veggiesaurus commented on src/components/StokesAnalysis/StokesAnalysisComponent.tsx
> +            let nearestIndex = undefined;
by default, variables are `undefined`

2020-05-06 12:27 UTC, duidae commented
just tried David's approach to extract skyframe and replace original wcsinfo with skyframe, however it breaks the AST ticks, not sure what is going on, so I think this PR can only handle the spectral part, spatial part refactoring needs more investigation. (so far the spatial functionality  still works using previous implementation).

original:
![image](https://user-images.githubusercontent.com/25971696/81175900-e4a4cb80-8fd6-11ea-975c-9fd6339156af.png)

simply replace wcsinfo with skyframe:
![image](https://user-images.githubusercontent.com/25971696/81175859-d35bbf00-8fd6-11ea-9faf-e29a524f0735.png)

2020-05-07 08:54 UTC, veggiesaurus commented on src/stores/FrameStore.ts
> +    public invertToNativeWCS = (value: number): number => {
should this be "convert"?

2020-05-07 12:03 UTC, duidae commented on src/stores/FrameStore.ts
> +    public invertToNativeWCS = (value: number): number => {
Fixed

2020-05-07 15:51 UTC, veggiesaurus requested changes
I must have skimmed over your message before, because I see now that the issues for LMCq aren't actually fixed, since it's now just assigning the letter "d" to the ticks, instead of just displaying the ticks as pixel values, which it used to do. For images with no WCS, it should revert to pixel coords, like it used to.

Part of the issue might be that now the WCS is constructed correctly, so no dummy frame is initialised. Technically, it does have a valid transform (from pixels to some unknown type), so perhaps we should use that? 

@kswang1029 the header itself doesn't have a CTYPE or CDELT but casacore seems to be inserting a CDELT of 1.0 by default. Not really sure how to handle situations like this...

2020-05-13 08:39 UTC, duidae commented
@veggiesaurus  tried a workaround in commit b5d6e37b0be7eabd56e54db6365817d95612c017, please have a look to see if it's ok, thanks.

2020-05-13 09:22 UTC, veggiesaurus requested changes
I think that check might be too specific. I think there's a simper approach: If the FrameSet that AST generates has a `Domain` attribute of `"SKY"`, then it can be displayed with degrees or HMS. If not, then the coordinates should _not_ be formatted as degrees etc.

LMCq for example, gives a domain of `"AXIS1-AXIS2"`

2020-05-14 03:01 UTC, duidae commented
changed to avoid non-sky frame

2020-05-19 17:20 UTC, veggiesaurus approved these changes

2020-05-19 17:20 UTC, merged