Thchang/profile smoothing
CARTAvis/carta-frontend pull request #986
Opened 2020-07-08 11:20 UTC by TienHao

close #651 

[GSL](https://www.gnu.org/software/gsl/) is used to apply profile smoothing. 
Requirement doc: https://docs.google.com/document/d/1-EnbWNeApaLB0HlJ3EUn-mGsLfKD2NeG9TKTWMzR5m4/edit#

demo:
![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/20379662/86912210-2b39b200-c14f-11ea-9401-8b5a2a9372ce.gif)

2020-07-08 18:55 UTC, veggiesaurus requested changes
- In order to build GSL, I had to add the argument ` --host=wasm32` to the configure step
- I get a divide by zero runtime error whenever I load a file which requires decimation of spatial profiles:

```
Uncaught RuntimeError: divide by zero
    at filterDecimation (http://localhost:3000/gsl_wrapper.wasm:wasm-function[12]:0x6e9)
    at Object../wasm_src/gsl_wrapper/build/index.js.Module._filterDecimation [as filterDecimation] (http://localhost:3000/static/js/bundle.js:512761:21873)
    at Object../wasm_src/gsl_wrapper/build/index.js.Module.decimation (http://localhost:3000/static/js/bundle.js:512761:27727)
    at ProfileSmoothingStore.getDecimatedValues (http://localhost:3000/static/js/bundle.js:505939:87)
    at SpatialProfilerComponent.get plotData (http://localhost:3000/static/js/bundle.js:490800:62)
```

2020-07-09 03:36 UTC, TienHao commented
> * In order to build GSL, I had to add the argument ` --host=wasm32` to the configure step

I removed the argument ` --host=wasm32` because there was a building trouble on RHEL7. (mentioned by @ajm-asiaa)
@veggiesaurus : what OS did you use to build?

2020-07-09 04:12 UTC, veggiesaurus commented
@TienHao one quick comment: if you know the length of a large array beforehand, it's much faster to allocate it first, rather than appending to it.

2020-07-09 04:13 UTC, veggiesaurus commented
> > * In order to build GSL, I had to add the argument ` --host=wasm32` to the configure step
> 
> I removed the argument ` --host=wasm32` because there was a building trouble on RHEL7. (mentioned by @ajm-asiaa)
> @veggiesaurus : what OS did you use to build?
> 
> 

Ubuntu 20.04. I'll double check what version of emcc I used.

2020-07-10 09:22 UTC, veggiesaurus commented on src/stores/widgets/SpectralProfileWidgetStore.ts
> +    @observable smoothingStore: ProfileSmoothingStore;
this can be a `readonly` variable without an observable decorator, can't it? since it's only assigned once

2020-07-10 09:25 UTC, veggiesaurus commented on wasm_src/gsl_wrapper/gsl_wrapper.cc
> +        size_t* minIndex = new size_t[1];
should just be `size_t minIndex;` and then pass it in as `&minIndex`, otherwise you're leaking memory.

2020-07-10 09:30 UTC, veggiesaurus requested changes
this now builds nicely.

- Can you change all the occurrences where you're pushing a known number of elements to an array to instead pre-allocating and assigning to that array. If we're looking at thousands of points, it might get a bit slow
- It looks to me like you're smoothing the _visible_  part of the profile. This makes it nice and efficient, which is great, but it does mean that you end up with missing data on the sides. I think you need to work out how much extra padding you need on either side and include that in the profile you're smoothing
- Couple of comments in the C++ code made separately

![image](https://user-images.githubusercontent.com/592504/87139699-ab236180-c2a0-11ea-9b74-42a2c502b004.png)

2020-07-15 07:55 UTC, TienHao commented
> * It looks to me like you're smoothing the _visible_  part of the profile. This makes it nice and efficient, which is great, but it does mean that you end up with missing data on the sides. I think you need to work out how much extra padding you need on either side and include that in the profile you're smoothing

I have added methods to get proper sub-array to perform local smoothing.

2020-07-15 07:56 UTC, TienHao commented
GSL has an argument to decide how to handle end points. 
https://www.gnu.org/software/gsl/doc/html/movstat.html#handling-endpoints

I added a dropdown `endType` in the setting panel to change the argument, which had been fixed to `GSL_MOVSTAT_END_PADVALUE`.

`endType` has three options:
1.`none`: set `NaN` to channels which have the window(kernel) needing extra padding for convolution.
2.`zero`: add zero into extra padding (`GSL_MOVSTAT_END_PADZERO`)
3.`value`: add first/last value into extra padding (`GSL_MOVSTAT_END_PADVALUE`)

2020-07-15 14:12 UTC, veggiesaurus commented
@kswang1029 which should we use as the default padding? `NaN`?

2020-07-15 14:34 UTC, kswang1029 commented
NaN sounds natural to adopt as we don’t have any info beyond the edges. In any case either with NaN, zero, or constant extrapolation, I personally won’t treats those smoothed edge channel seriously for analysis or interpretation.

2020-07-20 10:38 UTC, veggiesaurus commented
@TienHao is this ready for re-review?

2020-07-20 10:43 UTC, TienHao commented
@veggiesaurus : Yes, this is ready for re-review.
@kswang1029 : `NaN` is the default padding type now.

2020-07-20 10:59 UTC, veggiesaurus requested changes
couple of minor changes required to the code. In addition:
- Please make the settings widget slightly wider by default, so that the select dropdown doesn't get squashed.
- I think `EndType` is a very confusing setting. Just because that's how it's exposed in the library doesn't mean we should use that terminology. @kswang1029 how should we describe it?

2020-07-20 10:59 UTC, veggiesaurus commented on wasm_src/gsl_wrapper/gsl_wrapper.cc
> +            double *x = (double *) malloc(wsize * sizeof(double));
this should be initialised via `new` instead of `malloc`

2020-07-20 10:59 UTC, veggiesaurus commented on wasm_src/gsl_wrapper/gsl_wrapper.cc
> +            free(x);
`delete[]`

2020-07-21 09:36 UTC, kswang1029 commented
@veggiesaurus @TienHao We should just hide EndType from users and just use it internally in the codebase (ie users do not have a chance to configure it through the GUI).

2020-07-21 12:07 UTC, TienHao commented
@kswang1029 I have removed `EndType` from smoothing setting panel.

2020-07-21 18:11 UTC, veggiesaurus commented
@TienHao code now looks fine. However, I still can't build properly without `--host=wasm32` as an argument. I think we either need to find the root cause of this, or document it carefully and make it easy for users to run `build_libs` with some sort of command line option that adds that flag

2020-07-23 13:56 UTC, veggiesaurus commented
@TienHao let me know if the build script changes work ok for you. Works fine with `npm build-libs-docker` for me

2020-07-24 03:11 UTC, TienHao commented
@veggiesaurus : the build script works fine for me too!

2020-07-24 08:48 UTC, merged