Jason/line id overlay
CARTAvis/carta-frontend pull request #998
Opened 2020-07-15 12:40 UTC by duidae

closes #863

send PR first to see if there is anything needs to fix before hand,
working on filter.

2020-07-15 12:44 UTC, veggiesaurus commented on src/components/Shared/TableComponent/TableComponent.tsx
> +        return table.type === TableType.ColumnFilter ? (
I think the if/else approach looks a bit neater for such a long return value

2020-07-15 13:04 UTC, veggiesaurus requested changes
One minor change in the code. The only other thing I'd like changed is the dropdown for the spectral profile widget to look like the normal select dropdowns. I think just using `minimal=true` does that

2020-07-15 13:04 UTC, veggiesaurus commented on src/components/SpectralLineOverlay/SpectralLineOverlayComponent.scss
> +                padding: 5px 5px 5px 5px;
can just use `padding: 5px` can't you?

2020-07-15 13:56 UTC, duidae commented
fixed, please have a look, thanks.

2020-07-15 14:28 UTC, veggiesaurus requested changes
another couple of issues:

- the spectral profile often stays highlighted even after the selection is complete. This seems to happen more often when there's only one widget
- I think we should use a label and a proper BlueprintJS select for the spectral profile dropdown. It should look similar to the data source dropdown in the contour dialog
- Should we not automatically select a particular spectral profile by default? It's quite annoying to have to select a spectral profile widget even if there's only one of them (which will probably be the case fairly often)

2020-07-16 03:20 UTC, duidae commented
init selection with the 1st spectral widget & refined dropdown style.
@veggiesaurus what type & version of browser are u using? I cant reproduce the lasting highlight issue on chrome(81.0.4044.138 )/firefox(78.0.1) on ubuntu.

2020-07-20 14:54 UTC, duidae commented
added show line text when zoom-in to appropriate scale
 
![ddabe-9169g](https://user-images.githubusercontent.com/25971696/87951849-b2860e80-cadb-11ea-8ee5-432c0fdc7578.gif)

2020-07-21 05:44 UTC, kswang1029 commented
There are a couple of things for improvements:
- [ ] the textboxes, from, to, velocity/redshift, do not accept floating numbers. 
- [ ] should also request "Sij mu^2", "Sij" and "Aij" from the spatalogue and display them
<img width="298" alt="Screen Shot 2020-07-21 at 1 22 08 PM" src="https://user-images.githubusercontent.com/20819712/88016070-34664e00-cb55-11ea-9a80-c0c4903debc2.png">

- [ ] rename "Freq-MHz(rest frame, redshifted)" to "Rest Frequency"
- [ ] rename "Freq Err(rest frame, redshifted)" to "Rest Frequency Error"
- [ ] allowing users to resize the two tables in the vertical direction (cf catalog widget)
- [ ] rename "Meas Freq-MHz(rest frame, redshifted)" to "Measured Frequency"
- [ ] rename "Meas Freq Err(rest frame, redshifted)" to "Measured Frequency Error"
- [ ] the shifted frequency column should adopt the following logic: if "Rest Frequency" exists, use it for conversion of "Shifted Frequency". Otherwise, use "Measured Frequency" for conversion of "Shifted Frequency". Some entries do not have rest frequencies and only have measured frequencies. If both exists, use "Rest" for conversion. 
![Screen Shot 2020-07-21 at 1 29 51 PM](https://user-images.githubusercontent.com/20819712/88016763-b7d46f00-cb56-11ea-837e-c8ac960be4a0.png)

- [ ] add descriptions:
Species: Chemical formula of the species
Chemical name: Chemical name of the species
Shifted frequency: Shifted frequency according to the input velocity or redshift
Rest frequency: Frequency at the rest frame
Rest frequency error: Frequency error at the rest frame
Measured frequency: Frequency measured from laboratories
Measured frequency error: Frequency error measured from laboratories
Resolved QNs: Resolved quantum numbers
CDMS/JPL intensity: log10(intensity) at 300 K
E_L (cm^-1): Lower level energy in wave number
E_L (K): Lower level energy in K
E_U (cm^-1): Upper level energy in wave number
E_U (K): Upper level energy in K
Linelist: Originated catalogue

- [ ] add filtering and sorting functions.

2020-07-21 09:20 UTC, veggiesaurus commented
>  add filtering and sorting functions.

@kswang1029 sorting should be easy to do, but by filtering, do you mean similar to the catalog stuff? (which is done on the backend currently)

2020-07-21 09:29 UTC, kswang1029 commented
@veggiesaurus yes, similar to the catalog stuff. Any possibility to reuse the code via wasm?

2020-07-21 09:32 UTC, veggiesaurus commented
> @veggiesaurus yes, similar to the catalog stuff. Any possibility to reuse the code via wasm?

It would probably be easier to just handle in JS. I imagine you're not expecting millions of line ID results. But either way it's an added complexity. Could we leave the filtering for a future release, and just include sorting? That should be pretty simple to implement

2020-07-21 09:39 UTC, kswang1029 commented
what we obtained from spatalogue should be sorted in frequency. 

if it is risky to implement filtering, we can postpone it to v1.5.

2020-07-24 08:56 UTC, duidae commented
Mostly fixed.

2020-07-25 10:46 UTC, kswang1029 commented
I checked the spatalogue user manual and there is a table for description. So I suggest we just follow it. These include:

Sij Mu^2: Dipole-weighted transition dipole matrix elements (Debye^2)

Sij: Line strength

Aij: Base-10 logarithm of the Einstein A coefficient (s^-1)

Species: Descriptive formula of molecular species.

Chemical Name: Common chemical name for species

Resolved QNs: Rotational/rovibrational quantum numbers associated with the transition.

CDMS/JPL intensity: Boltzmann-weighted logarithmic intensity of transition, given at 300 K

Lovas/AST Intensity: Observed astronomical intensity for given transition

2020-07-26 06:17 UTC, duidae commented
Refined header & description.

2020-07-27 03:08 UTC, kswang1029 commented
<img width="882" alt="Screen Shot 2020-07-27 at 11 05 12 AM" src="https://user-images.githubusercontent.com/20819712/88499685-2e5eea00-cff9-11ea-9620-fb8f45ed755a.png">
@duidae Can we add a space before "v=..."? For example, "CH3CH2CNv=0" should be displayed as "CH3CH2CN v=0". The v=0 here means it is the vibrational ground state.

2020-07-27 03:11 UTC, kswang1029 commented
@duidae the line labels need to be included in the png output too.

2020-07-27 09:56 UTC, veggiesaurus approved these changes

2020-07-27 09:56 UTC, merged